project:
  type: website

website:
  title: "Data-as-Material-Class"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    toc-depth: 4  # Specify the depth of headers to include in the TOC
    

editor: visual

