{
  "hash": "fb8841c156f64ef6d8dff293d1a59df3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"(9) A3 - B.FA vs B.Des vs B.Voc\"\nauthor: \"Vasantha M\"\n---\n\n\n\n\n## Introduction\n\n.\n\nIn and around SMI campus, a person was found.\n\nTheir bachelors degree (B.Voc/B.Des/B.FA) was identified.\n\nA question on their last grade in Cycle 1 was asked.\n\nA coin was flipped.\n\nThere was a 50% chance that that person contributed to this data sample!\n\n.\n\n### Setup Chunk\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse) # Tidy data processing\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula) # Formula based plots\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: scales\n\nAttaching package: 'scales'\n\nThe following object is masked from 'package:purrr':\n\n    discard\n\nThe following object is masked from 'package:readr':\n\n    col_factor\n\nLoading required package: ggridges\n\nNew to ggformula?  Try the tutorials: \n\tlearnr::run_tutorial(\"introduction\", package = \"ggformula\")\n\tlearnr::run_tutorial(\"refining\", package = \"ggformula\")\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(mosaic) # Data inspection and Statistical Inference\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRegistered S3 method overwritten by 'mosaic':\n  method                           from   \n  fortify.SpatialPolygonsDataFrame ggplot2\n\nThe 'mosaic' package masks several functions from core packages in order to add \nadditional features.  The original behavior of these functions should not be affected by this.\n\nAttaching package: 'mosaic'\n\nThe following object is masked from 'package:Matrix':\n\n    mean\n\nThe following object is masked from 'package:scales':\n\n    rescale\n\nThe following objects are masked from 'package:dplyr':\n\n    count, do, tally\n\nThe following object is masked from 'package:purrr':\n\n    cross\n\nThe following object is masked from 'package:ggplot2':\n\n    stat\n\nThe following objects are masked from 'package:stats':\n\n    binom.test, cor, cor.test, cov, fivenum, IQR, median, prop.test,\n    quantile, sd, t.test, var\n\nThe following objects are masked from 'package:base':\n\n    max, mean, min, prod, range, sample, sum\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(broom) # Tidy outputs from Statistical Analyses\nlibrary(infer) # Statistical Inference, Permutation/Bootstrap\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'infer'\n\nThe following objects are masked from 'package:mosaic':\n\n    prop_test, t_test\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(patchwork) # Arranging Plots\nlibrary(ggprism) # Interesting Categorical Axes\nlibrary(supernova) # Beginner-Friendly ANOVA Tables\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'supernova'\n\nThe following object is masked from 'package:scales':\n\n    number\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(skimr)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'skimr'\n\nThe following object is masked from 'package:mosaic':\n\n    n_missing\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(DT)\nlibrary(DescTools)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'DescTools'\n\nThe following object is masked from 'package:mosaic':\n\n    MAD\n```\n\n\n:::\n:::\n\n\n\n\n.\n\n## Reading and Examining Data\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades <- read_csv(\"../../Data/grades.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 90 Columns: 7\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (4): Degree, Course, Letter Grade, Gender\ndbl (3): SN, Year, Score\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\ngrades %>%glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 90\nColumns: 7\n$ SN             <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, …\n$ Degree         <chr> \"B.Des\", \"B.Des\", \"B.Des\", \"B.Des\", \"B.Des\", \"B.Des\", \"…\n$ Course         <chr> \"CAC\", \"CAC\", \"IADP\", \"CE\", \"BSSD\", \"CAC\", \"PSD\", \"PSD\"…\n$ Year           <dbl> 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 3, 3, 2, 3, 3, 2, 2…\n$ `Letter Grade` <chr> \"A\", \"O\", \"A+\", \"O\", \"P\", \"O\", \"A+\", \"A+\", \"A+\", \"A+\", …\n$ Score          <dbl> 8.0, 9.6, 9.2, 9.8, 3.0, 9.5, 9.0, 9.0, 9.0, 9.0, 8.0, …\n$ Gender         <chr> \"F\", \"F\", \"F\", \"F\", \"M\", \"F\", \"F\", \"F\", \"F\", \"F\", \"F\", …\n```\n\n\n:::\n:::\n\n\n\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndatatable(grades, options = list(pageLength = 10))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-3b38abe4f1adcfecb4a2\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-3b38abe4f1adcfecb4a2\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\"],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90],[\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Des\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.Voc\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\",\"B.FA\"],[\"CAC\",\"CAC\",\"IADP\",\"CE\",\"BSSD\",\"CAC\",\"PSD\",\"PSD\",\"PSD\",\"BSSD\",\"VCSB\",\"VCSB\",\"IAIDP\",\"IAIDP\",\"VCSB\",\"HCD\",\"CAC\",\"VCSB\",\"CE\",\"CAC\",\"IADP\",\"IADP\",\"VCSB\",\"CE\",\"CAC\",\"CAC\",\"PSD\",\"PSD\",\"CAC\",\"HCD\",\"UIID\",\"UIID\",\"UIID\",\"UIID\",\"UIID\",\"UIID\",\"ID\",\"DMP\",\"DMP\",\"DMP\",\"DMP\",\"DMP\",\"DMP\",\"DMP\",\"DMP\",\"DMP\",\"UIID\",\"UIID\",\"UIID\",\"UIID\",\"UIID\",\"UIID\",\"UIID\",\"GADP\",\"GADP\",\"Film\",\"GADP\",\"GADP\",\"DMP\",\"DMP\",\"CAP\",\"CAP\",\"CAP\",\"DMA\",\"DMA\",\"DMA\",\"CAP\",\"CAP\",\"Film\",\"DMA\",\"DMA\",\"DMA\",\"DMA\",\"DMA\",\"DMA\",\"Film\",\"Film\",\"DMA\",\"DMA\",\"DMA\",\"DMA\",\"Film\",\"Film\",\"DMA\",\"DMA\",\"DMA\",\"DMA\",\"DMA\",\"DMA\",\"DMA\"],[2,2,2,2,2,2,2,2,2,3,2,2,3,3,2,3,3,2,2,2,2,3,3,2,3,3,3,3,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,1,1,1,1,1,1,2,1,2,3,3,3,2,2,3,3,3,2,2,2,2,2,3,2,2,2,2,2,2,3,3,2,2,2,2,2,3,2,2,2,2,2,2,2],[\"A\",\"O\",\"A+\",\"O\",\"P\",\"O\",\"A+\",\"A+\",\"A+\",\"A+\",\"A\",\"A\",\"A\",\"B+\",\"B+\",\"A+\",\"A+\",\"A\",\"A+\",\"A+\",\"A\",\"B+\",\"A+\",\"O\",\"A+\",\"A+\",\"B+\",\"A\",\"A+\",\"A\",\"O\",\"A+\",\"A+\",\"B+\",\"A\",\"A\",\"B+\",\"O\",\"B\",\"O\",\"O\",\"A+\",\"O\",\"O\",\"B\",\"C\",\"A+\",\"B\",\"B\",\"A\",\"A\",\"A+\",\"A\",\"A\",\"A\",\"A\",\"A+\",\"A+\",\"A\",\"A\",\"A\",\"A+\",\"A+\",\"A+\",\"A\",\"A\",\"A\",\"A+\",\"B\",\"A\",\"B+\",\"B+\",\"A\",\"B+\",\"B\",\"A\",\"A\",\"A\",\"A\",\"B+\",\"B+\",\"A\",\"B+\",\"A+\",\"A\",\"B+\",\"B+\",\"B+\",\"B+\",\"B+\"],[8,9.6,9.199999999999999,9.800000000000001,3,9.5,9,9,9,9,8,8,8,7,7,9,9.1,8,9,9,8,7,9,10,9,9,7,8,9,8,9.5,9,9,7,8,8,7,9.5,6.5,9.5,9.5,9,9.5,9.5,6.5,5,9,7,7,8,8,9,8,8,8,8,9,9,8,8,8,9,9,8.5,8,8,8,8,6,8,7,7,8,7,6,8,8,8,8,7,7,8,7,9,8,7,7,7,7,7],[\"F\",\"F\",\"F\",\"F\",\"M\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"M\",\"M\",\"F\",\"M\",\"F\",\"M\",\"F\",\"M\",\"F\",\"M\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"M\",\"M\",\"F\",\"F\",\"M\",\"M\",\"M\",\"M\",\"M\",\"M\",\"F\",\"F\",\"F\",\"M\",\"M\",\"F\",\"F\",\"F\",\"F\",\"F\",\"M\",\"F\",\"M\",\"M\",\"F\",\"F\",\"M\",\"M\",\"F\",\"M\",\"F\",\"M\",\"M\",\"F\",\"F\",\"F\",\"M\",\"F\",\"F\",\"F\",\"F\",\"F\",\"M\",\"M\",\"M\",\"M\",\"M\",\"F\",\"F\",\"F\",\"F\",\"F\",\"M\",\"F\",\"F\",\"M\",\"F\",\"F\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>SN<\\/th>\\n      <th>Degree<\\/th>\\n      <th>Course<\\/th>\\n      <th>Year<\\/th>\\n      <th>Letter Grade<\\/th>\\n      <th>Score<\\/th>\\n      <th>Gender<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":10,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,4,6]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"SN\",\"targets\":1},{\"name\":\"Degree\",\"targets\":2},{\"name\":\"Course\",\"targets\":3},{\"name\":\"Year\",\"targets\":4},{\"name\":\"Letter Grade\",\"targets\":5},{\"name\":\"Score\",\"targets\":6},{\"name\":\"Gender\",\"targets\":7}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades %>%inspect()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\ncategorical variables:  \n          name     class levels  n missing\n1       Degree character      3 90       0\n2       Course character     15 90       0\n3 Letter Grade character      7 90       0\n4       Gender character      2 90       0\n                                   distribution\n1 B.Des (33.3%), B.FA (33.3%) ...              \n2 DMA (22.2%), UIID (14.4%), DMP (12.2%) ...   \n3 A (33.3%), A+ (27.8%), B+ (18.9%) ...        \n4 F (63.3%), M (36.7%)                         \n\nquantitative variables:  \n   name   class min    Q1 median    Q3 max      mean         sd  n missing\n1    SN numeric   1 23.25   45.5 67.75  90 45.500000 26.1247010 90       0\n2  Year numeric   1  2.00    2.0  3.00   3  2.333333  0.6180797 90       0\n3 Score numeric   3  7.00    8.0  9.00  10  8.063333  1.1346880 90       0\n```\n\n\n:::\n:::\n\n\n\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades %>% skim()\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |           |\n|:------------------------|:----------|\n|Name                     |Piped data |\n|Number of rows           |90         |\n|Number of columns        |7          |\n|_______________________  |           |\n|Column type frequency:   |           |\n|character                |4          |\n|numeric                  |3          |\n|________________________ |           |\n|Group variables          |None       |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|Degree        |         0|             1|   4|   5|     0|        3|          0|\n|Course        |         0|             1|   2|   5|     0|       15|          0|\n|Letter Grade  |         0|             1|   1|   2|     0|        7|          0|\n|Gender        |         0|             1|   1|   1|     0|        2|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  mean|    sd| p0|   p25|  p50|   p75| p100|hist  |\n|:-------------|---------:|-------------:|-----:|-----:|--:|-----:|----:|-----:|----:|:-----|\n|SN            |         0|             1| 45.50| 26.12|  1| 23.25| 45.5| 67.75|   90|▇▇▇▇▇ |\n|Year          |         0|             1|  2.33|  0.62|  1|  2.00|  2.0|  3.00|    3|▁▁▇▁▆ |\n|Score         |         0|             1|  8.06|  1.13|  3|  7.00|  8.0|  9.00|   10|▁▁▆▇▇ |\n\n\n:::\n:::\n\n\n\n\n.\n\n### Clarifying Data:\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_mod <-grades %>% \n  mutate(\n   scores_rounded = \n     case_when(\n    `Letter Grade` == \"O\" ~ 10,\n    `Letter Grade` == \"A+\" ~ 9,\n    `Letter Grade` == \"A\" ~ 8,\n    `Letter Grade` == \"B+\" ~ 7,\n    `Letter Grade` == \"B\" ~ 6,\n    `Letter Grade` == \"C\" ~ 5,\n    `Letter Grade` == \"P\" ~ 3,\n  \n  ) )\ngrades_mod\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 90 × 8\n      SN Degree Course  Year `Letter Grade` Score Gender scores_rounded\n   <dbl> <chr>  <chr>  <dbl> <chr>          <dbl> <chr>           <dbl>\n 1     1 B.Des  CAC        2 A                8   F                   8\n 2     2 B.Des  CAC        2 O                9.6 F                  10\n 3     3 B.Des  IADP       2 A+               9.2 F                   9\n 4     4 B.Des  CE         2 O                9.8 F                  10\n 5     5 B.Des  BSSD       2 P                3   M                   3\n 6     6 B.Des  CAC        2 O                9.5 F                  10\n 7     7 B.Des  PSD        2 A+               9   F                   9\n 8     8 B.Des  PSD        2 A+               9   F                   9\n 9     9 B.Des  PSD        2 A+               9   F                   9\n10    10 B.Des  BSSD       3 A+               9   F                   9\n# ℹ 80 more rows\n```\n\n\n:::\n:::\n\n\n\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## means of each group in the sample\nmeans <-grades_mod %>% \n  mutate( Degree = as_factor(Degree)\n  \n) %>% \n  group_by(Degree) %>% \n  summarize(mean = count(Gender == \"M\"))\nmeans\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  Degree  mean\n  <fct>  <int>\n1 B.Des      7\n2 B.Voc     15\n3 B.FA      11\n```\n\n\n:::\n:::\n\n\n\n\n.\n\n### Data Dictionary\n\nThere are `90` rows and `7+1` columns in this data sample.\n\n.\n\n-   `SN`: A qualitative variable that keeps track of every individual participant.\n\n-   `Degree`: A qualitative variable that describes the Bachelors `Degree` of each participant, either `B.Des`, `B.Voc` or `B.FA`.\n\n-   `Course`: A qualitative variable that describes the Major Course of each participant within their `Degree`.\n\n-   `Year`: A qualitative variable that describes the year of study of each participant.\n\n-   `Letter Grade`: A qualitative variable that describes the most recent grade received by the participant.\n\n-   `Score`: A quantitative variable that describes the most recent score received by the participant.\n\n-   `Gender`: A qualitative variable indicating the gender of each participant, either male or female. It is not equally distributed amongst the `Degrees` and hence cannot be a categorizing factor. Out of 90 participants, there are only 33 males.\n\n-   `rounded_scores`: A quantitative variable that describes the most recent grade received by the participant, but as a numeral. It is essentially the rounded version of the `Score` column.\n\n.\n\n## Charting Data\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##\ngrades_mod %>% \ngf_histogram(~scores_rounded,\n  fill = ~Degree,\n  alpha = 0.5,\n  position = \"identity\",\n) %>%\n  gf_vline(xintercept = ~ mean(scores_rounded)) %>%\n  gf_labs(\n    title = \"Histograms of Score Distributions vs Degree\",\n    x = \"Scores\", y = \"Count\"\n  ) %>%\n  gf_text(7 ~ (mean(scores_rounded) + 2),\n    label = \"Overall Mean\"\n  ) %>%\n  gf_refine(guides(fill = guide_legend(title = \"Scores\")))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\n##\ngrades_mod %>% \ngf_histogram(~scores_rounded,\n  fill = ~Degree,\n  alpha = 0.5,\n) %>%\n  gf_facet_wrap(~Degree) %>% \n  gf_vline(xintercept = ~ mean(scores_rounded)) %>%\n  gf_labs(\n    title = \"Histograms of Score Distributions vs Degree\",\n    x = \"Scores\", y = \"Count\"\n  ) %>%\n  gf_text(7 ~ (mean(scores_rounded) + 2),\n    label = \"Overall Mean\"\n  ) %>%\n  gf_refine(guides(fill = guide_legend(title = \"Scores\")))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n:::\n\n\n\n\n.\n\n-   There is considerable overlaps in the `histograms` of the three groups in terms of grades. Due to the nature of modification done to the data, the histogram is not continuous and represents a bar graph.\n\n-   The modal value of B.Des is placed highest in terms of the three, at a score of 9, with B.Voc in the middle at a score of 8, and B.FA trailing at a score of 7. There also seems to be a low score outlier in the B.Des sample.\n\n    .\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##\ngrades_mod %>% \ngf_boxplot(\n  scores_rounded ~ Degree,\n  fill = ~Degree,\n  alpha = 0.5\n) %>%\n  gf_vline(xintercept = ~ mean(scores_rounded)) %>%\n  gf_labs(\n    title = \"Boxplots of Score Distributions vs Degree\",\n    x = \"Degree\", y = \"Score\",\n    caption = \"Using ggprism\"\n  ) %>%\n  gf_refine(\n    scale_x_discrete(guide = \"prism_bracket\"),\n    guides(fill = guide_legend(title = \"Score\"))\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: The S3 guide system was deprecated in ggplot2 3.5.0.\nℹ It has been replaced by a ggproto system that can be extended.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n\n\n.\n\n-   The `box-plots` indicate that the interquartile regions of the B.Des and B.Voc samples are the same, with the B.FA sample below them. Their medians however, are on opposite ends of each box, indicating that although they have a similar central range of data, the distribution is very different.\n\n-   The B.Des group has a very eveident left skew, signifying that there are more data points on the lower end. The B.Voc group is the opposite, with more data points above the median value.\n\n-   The median of the B.FA data sample is the same as that of the B.Voc data sample. However, the box lies completely below the median, unlike the B.Voc group. This indicates that overall, the central data range is lower than that of the other two, as well as that even within the group, there are more data points on the lower end.\n\n-   Though the whiskers are symmetrical on all three boxes, the B.Des and B.Voc groups show cases of outliers on the lower end. Even with the presence of more outliers in the B.Voc set, it remains a right-skew distribution.\n\n.\n\n## Research Question\n\n.\n\nBased on the sample data set at hand, how does viewer Score (`rounded_score`) vary with `Bachelors Degree`?\n\n.\n\n### Hypothesis\n\n.\n\nCase 0: Null Hypothesis - tested by ANOVA\n\n> mean(B.Des) = mean(B.Voc) = mean(B.FA)\n\nCase 1:\n\n> mean(B.Des) ≠ mean(B.Voc) = mean(B.FA)\n\nCase 2:\n\n> mean(B.Des) = mean(B.Voc) ≠ mean(B.FA)\n\nCase 3:\n\n> mean(B.Des) ≠ mean(B.Voc) ≠ mean(B.FA)\n\n## ANOVA\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_anova <- aov(scores_rounded ~ Degree, data = grades_mod)\n```\n:::\n\n\n\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\nsupernova::pairwise(grades_anova,\n  correction = \"Bonferroni\", # Try \"Tukey\"\n  alpha = 0.05, # 95% CI calculation\n  var_equal = TRUE, # We'll see\n  plot = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Pairwise t-tests with Bonferroni correction ─────────────────────────────────\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nModel: scores_rounded ~ Degree\n```\n\n\n:::\n\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDegree\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLevels: 3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFamily-wise error-rate: 0.049\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  group_1 group_2   diff pooled_se      t    df  lower  upper  p_adj\n  <chr>   <chr>    <dbl>     <dbl>  <dbl> <int>  <dbl>  <dbl>  <dbl>\n1 B.FA    B.Des   -0.733     0.224 -3.277    87 -1.217 -0.250  .0045\n2 B.Voc   B.Des   -0.200     0.224 -0.894    87 -0.684  0.284 1.0000\n3 B.Voc   B.FA     0.533     0.224  2.384    87  0.050  1.017  .0580\n```\n\n\n:::\n\n```{.r .cell-code}\n## trying with \"Tukey\"\n\nsupernova::pairwise(grades_anova,\n  correction = \"Tukey\", # Try \"Tukey\"\n  alpha = 0.05, # 95% CI calculation\n  var_equal = TRUE, # We'll see\n  plot = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Tukey's Honestly Significant Differences ────────────────────────────────────\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nModel: scores_rounded ~ Degree\n```\n\n\n:::\n\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDegree\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLevels: 3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFamily-wise error-rate: 0.05\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  group_1 group_2   diff pooled_se      q    df  lower upper p_adj\n  <chr>   <chr>    <dbl>     <dbl>  <dbl> <int>  <dbl> <dbl> <dbl>\n1 B.FA    B.Des   -0.733     0.224 -3.277    87 -1.488 0.021 .0586\n2 B.Voc   B.Des   -0.200     0.224 -0.894    87 -0.955 0.555 .8029\n3 B.Voc   B.FA     0.533     0.224  2.384    87 -0.221 1.288 .2165\n```\n\n\n:::\n:::\n\n\n\n\n.\n\nThis test reveals that\n\n-   The `mean difference` of B.FA v/s B.Des is -`0.733.` The negative value indicates that on average, the values in B.FA, the first group, are lower than that of B.Des, the second group. The confidence interval does not include 0, and the `p-value` of `0.0045` is well below the threshold of 0.05, indicating that any difference cab are statistically significant. The null hypothesis is rejected in this case.\n\n-   The `mean difference` of B.Voc v/s B.Des is -`0.200.` Once again, the negative value indicates that on average the values in B.Voc, the first group, are lower than that of B.Des, the second group. The confidence interval however, includes 0, and the `p-value` of `1.0000` is above the threshold of 0.05, indicating that any difference cab be likely due to chance. The null hypothesis cannot be rejected in this case.\n\n-   the `mean difference` of B.Voc v/s B.FA is `0.533`. The confidence interval does not include 0, and the `p-value` of `0.0580`is slightly above the threshold of 0.05, indicating that any difference is not a chance encounter. Ideally, one would use a larger sample size to prove the precision of the estimate, since it dances around the threshold, but the null hypothesis is not entirely rejected in this case.\n\n-   To conclude, at the 95% confidence level with [Boneferroni coreection]{.underline}, while B.Voc and B.Des don't have a difference in means, B,Des and B.FA have a statistically significant difference. B.Voc and B.FA, however need more evidence to conclude whether their difference is significant or not.\n\n-   However, with the [Tukey correction]{.underline}, the 95% confidence intervals for all three groups include 0, and the `p-value` for all three groups is above the threshold 0.05, signifying that the **null hypothesis cannot be rejected**.\n\n.\n\n## Stating the Model\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsupernova::equation(grades_anova)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFitted equation:\nscores_rounded = 8.4 + -0.7333333*DegreeB.FA + -0.2*DegreeB.Voc + e\n```\n\n\n:::\n:::\n\n\n\n\n.\n\nThis linear equation relates scores_rounded to bachelors degree says that:\n\nThe value of `8.4` acts as the reference mean, (in this case for B.Des, as identified earlier through grouping and summarizing). The equation tells us that on average, the scores in B.FA are `0.733` times lower than that of the reference, and the scores in B.Voc are `0.2` times lower than that of the reference. The constant `e` accounts for any error factor.\n\n.\n\n## Checking ANOVA Assumptions\n\n.\n\n### Checks for Normality\n\n.\n\nANOVA makes 3 fundamental assumptions:\n\na.  Data (and errors) are normally distributed.\n\nb.  Variances are equal.\n\nc.  Observations are independent.\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(x = grades_mod$scores_rounded)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  grades_mod$scores_rounded\nW = 0.9034, p-value = 5.762e-06\n```\n\n\n:::\n:::\n\n\n\n\n.\n\n-   The test statistic of `W`, valued for this data sample at `0.9034` suggests that the data might be normally distributed. This statistic is represented by a value always between 0-1, and the further the value is from 1, the further the data sample is being from normally distributed.\n\n-   Since the `p-value`, at `0.000005762` is much lower than that of the threshold of 0.05, Case0, the **first condition and assumption for ANOVA is not met.**\n\n-   Both these results together are indicative that this data sample **is not normally distributed**.\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_mod %>%\n  group_by(Degree) %>%\n  group_modify(~ .x %>%\n    select(scores_rounded) %>%\n    as_vector() %>%\n    shapiro.test() %>%\n    broom::tidy())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n# Groups:   Degree [3]\n  Degree statistic   p.value method                     \n  <chr>      <dbl>     <dbl> <chr>                      \n1 B.Des      0.765 0.0000162 Shapiro-Wilk normality test\n2 B.FA       0.873 0.00192   Shapiro-Wilk normality test\n3 B.Voc      0.903 0.0102    Shapiro-Wilk normality test\n```\n\n\n:::\n:::\n\n\n\n\n.\n\n-   Looking at the test results for each group, we can say that in all three groups data are definitely not normally distributed, as their `p-values` are much lesser than 0.05.\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##theoretical distribution vs sample distribution\ngrades_anova$residuals %>%\n  as_tibble() %>%\n  gf_dhistogram(~value, data = .) %>%\n  gf_fitdistr()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n\n```{.r .cell-code}\n##\ngrades_anova$residuals %>%\n  as_tibble() %>%\n  gf_qq(~value, data = .) %>%\n  gf_qqstep() %>%\n  gf_qqline()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-2.png){width=672}\n:::\n\n```{.r .cell-code}\n##\nshapiro.test(grades_anova$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  grades_anova$residuals\nW = 0.9166, p-value = 2.429e-05\n```\n\n\n:::\n:::\n\n\n\n\n.\n\n-   from both these graphs, it is clear to see that the distribution of the sample data is ill fitting of the lines that indicated the theoretical distribution. Now it can be safely concluded that the sample data is indeed, **not normally distributed.**\n\n.\n\n### Check for Similar Variance\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_mod %>%\n  group_by(Degree) %>%\n  summarise(variance = var(scores_rounded))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  Degree variance\n  <chr>     <dbl>\n1 B.Des     1.83 \n2 B.FA      0.713\n3 B.Voc     1.96 \n```\n\n\n:::\n\n```{.r .cell-code}\n# \nDescTools::LeveneTest(scores_rounded ~ Degree, data = grades_mod)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in LeveneTest.default(y = y, group = group, ...): group coerced to\nfactor.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLevene's Test for Homogeneity of Variance (center = median)\n      Df F value Pr(>F)\ngroup  2  1.3737 0.2586\n      87               \n```\n\n\n:::\n\n```{.r .cell-code}\n##\nfligner.test(scores_rounded ~ Degree, data = grades_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tFligner-Killeen test of homogeneity of variances\n\ndata:  scores_rounded by Degree\nFligner-Killeen:med chi-squared = 4.513, df = 2, p-value = 0.1047\n```\n\n\n:::\n:::\n\n\n\n\n.\n\n-   Though the maginitude of the variances as computed in the table seem to indicate that there is significant difference in the variance, at least in terms of B.FA and the other two groups, The Fligner-Killeen test of homogeneity of variances here, with a p-value of `0.1047` shows that those values are not statistically significant. Hence, the test implies that the **variances are homogeneous**, supporting the second assumption/condition for conducting ANOVA.\n\n.\n\n### Independent Observations\n\n.\n\nThe way in which the data was gathered ensured that each observation is Independent.\n\n.\n\nHence, two out of three ANOVA assumptions have been confirmed. It still makes sense to perform ANOVA, as it is typically robust against violations of normality, especially with balanced groups and sample sizes \\>=30 (which this sample fulfills.\n\n.\n\n## Effect Size\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#\ngrades_supernova <-\n  supernova::pairwise(grades_anova,\n    plot = TRUE,\n    alpha = 0.05,\n    correction = \"Bonferroni\"\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrades_supernova\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Pairwise t-tests with Bonferroni correction ─────────────────────────────────\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nModel: scores_rounded ~ Degree\n```\n\n\n:::\n\n\n::: {.cell-output .cell-output-stderr}\n\n```\nDegree\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLevels: 3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nFamily-wise error-rate: 0.049\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  group_1 group_2   diff pooled_se      t    df  lower  upper  p_adj\n  <chr>   <chr>    <dbl>     <dbl>  <dbl> <int>  <dbl>  <dbl>  <dbl>\n1 B.FA    B.Des   -0.733     0.224 -3.277    87 -1.217 -0.250  .0045\n2 B.Voc   B.Des   -0.200     0.224 -0.894    87 -0.684  0.284 1.0000\n3 B.Voc   B.FA     0.533     0.224  2.384    87  0.050  1.017  .0580\n```\n\n\n:::\n:::\n\n\n\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiff_values <- c(0.733, 0.200, 0.0533)\npooled_se <- 0.224\nsample_size <- 30\n\n# Calculate Cohen's d\nd_values <- diff_values / pooled_se * sqrt(1/sample_size + 1/sample_size)\nd_values\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8449098 0.2305347 0.0614375\n```\n\n\n:::\n\n```{.r .cell-code}\n## Interpreting Cohen’s d\n##Small effect: d≈0.2\n##Medium effect: d≈0.5\n##Large effect: d≈0.8\n```\n:::\n\n\n\n\n.\n\n-   The first comparison (B.FA vs. B.Des) strongly suggest that there are **meaningful differences** in the ratings, despite not achieving statistical significance. This could imply that, with a larger sample size or different study conditions, these differences might become significant.\n\n-   The second comparison (B.Voc vs B.Des) shows that there is essentially **no meaningful difference** in ratings, reinforcing the conclusion that these two cartoons are rated similarly by participants.\n\n-   The last comparison (B.FA vs B.Voc) again, (but not as strongly) suggest that there are **meaningful differences** in the ratings, despite not achieving statistical significance. This could imply that, with a larger sample size or different study conditions, these differences might become significant, and/or more insights can be gained.\n\n.\n\n## ANOVA using Permutation Test\n\n.\n\n-   Since the data is not normally distributed, a permutation test is a good option to check for significance.\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nobserved_infer <-\n  grades_mod %>%\n  specify(scores_rounded ~ Degree) %>%\n  hypothesise(null = \"independence\") %>%\n  calculate(stat = \"F\")\nobserved_infer\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nResponse: scores_rounded (numeric)\nExplanatory: Degree (factor)\nNull Hypothesis: independence\n# A tibble: 1 × 1\n   stat\n  <dbl>\n1  2.87\n```\n\n\n:::\n:::\n\n\n\n\n.\n\n-   The observed F- statistic is `2.870408.`\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnull_dist_infer <- grades_mod %>%\n  specify(scores_rounded ~ Degree) %>%\n  hypothesise(null = \"independence\") %>%\n  generate(reps = 4999, type = \"permute\") %>%\n  calculate(stat = \"F\")\n##\ndatatable(null_dist_infer, options = list(pageLength = 10))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-63e8691b35f6e5d93b32\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-63e8691b35f6e5d93b32\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\",\"17\",\"18\",\"19\",\"20\",\"21\",\"22\",\"23\",\"24\",\"25\",\"26\",\"27\",\"28\",\"29\",\"30\",\"31\",\"32\",\"33\",\"34\",\"35\",\"36\",\"37\",\"38\",\"39\",\"40\",\"41\",\"42\",\"43\",\"44\",\"45\",\"46\",\"47\",\"48\",\"49\",\"50\",\"51\",\"52\",\"53\",\"54\",\"55\",\"56\",\"57\",\"58\",\"59\",\"60\",\"61\",\"62\",\"63\",\"64\",\"65\",\"66\",\"67\",\"68\",\"69\",\"70\",\"71\",\"72\",\"73\",\"74\",\"75\",\"76\",\"77\",\"78\",\"79\",\"80\",\"81\",\"82\",\"83\",\"84\",\"85\",\"86\",\"87\",\"88\",\"89\",\"90\",\"91\",\"92\",\"93\",\"94\",\"95\",\"96\",\"97\",\"98\",\"99\",\"100\",\"101\",\"102\",\"103\",\"104\",\"105\",\"106\",\"107\",\"108\",\"109\",\"110\",\"111\",\"112\",\"113\",\"114\",\"115\",\"116\",\"117\",\"118\",\"119\",\"120\",\"121\",\"122\",\"123\",\"124\",\"125\",\"126\",\"127\",\"128\",\"129\",\"130\",\"131\",\"132\",\"133\",\"134\",\"135\",\"136\",\"137\",\"138\",\"139\",\"140\",\"141\",\"142\",\"143\",\"144\",\"145\",\"146\",\"147\",\"148\",\"149\",\"150\",\"151\",\"152\",\"153\",\"154\",\"155\",\"156\",\"157\",\"158\",\"159\",\"160\",\"161\",\"162\",\"163\",\"164\",\"165\",\"166\",\"167\",\"168\",\"169\",\"170\",\"171\",\"172\",\"173\",\"174\",\"175\",\"176\",\"177\",\"178\",\"179\",\"180\",\"181\",\"182\",\"183\",\"184\",\"185\",\"186\",\"187\",\"188\",\"189\",\"190\",\"191\",\"192\",\"193\",\"194\",\"195\",\"196\",\"197\",\"198\",\"199\",\"200\",\"201\",\"202\",\"203\",\"204\",\"205\",\"206\",\"207\",\"208\",\"209\",\"210\",\"211\",\"212\",\"213\",\"214\",\"215\",\"216\",\"217\",\"218\",\"219\",\"220\",\"221\",\"222\",\"223\",\"224\",\"225\",\"226\",\"227\",\"228\",\"229\",\"230\",\"231\",\"232\",\"233\",\"234\",\"235\",\"236\",\"237\",\"238\",\"239\",\"240\",\"241\",\"242\",\"243\",\"244\",\"245\",\"246\",\"247\",\"248\",\"249\",\"250\",\"251\",\"252\",\"253\",\"254\",\"255\",\"256\",\"257\",\"258\",\"259\",\"260\",\"261\",\"262\",\"263\",\"264\",\"265\",\"266\",\"267\",\"268\",\"269\",\"270\",\"271\",\"272\",\"273\",\"274\",\"275\",\"276\",\"277\",\"278\",\"279\",\"280\",\"281\",\"282\",\"283\",\"284\",\"285\",\"286\",\"287\",\"288\",\"289\",\"290\",\"291\",\"292\",\"293\",\"294\",\"295\",\"296\",\"297\",\"298\",\"299\",\"300\",\"301\",\"302\",\"303\",\"304\",\"305\",\"306\",\"307\",\"308\",\"309\",\"310\",\"311\",\"312\",\"313\",\"314\",\"315\",\"316\",\"317\",\"318\",\"319\",\"320\",\"321\",\"322\",\"323\",\"324\",\"325\",\"326\",\"327\",\"328\",\"329\",\"330\",\"331\",\"332\",\"333\",\"334\",\"335\",\"336\",\"337\",\"338\",\"339\",\"340\",\"341\",\"342\",\"343\",\"344\",\"345\",\"346\",\"347\",\"348\",\"349\",\"350\",\"351\",\"352\",\"353\",\"354\",\"355\",\"356\",\"357\",\"358\",\"359\",\"360\",\"361\",\"362\",\"363\",\"364\",\"365\",\"366\",\"367\",\"368\",\"369\",\"370\",\"371\",\"372\",\"373\",\"374\",\"375\",\"376\",\"377\",\"378\",\"379\",\"380\",\"381\",\"382\",\"383\",\"384\",\"385\",\"386\",\"387\",\"388\",\"389\",\"390\",\"391\",\"392\",\"393\",\"394\",\"395\",\"396\",\"397\",\"398\",\"399\",\"400\",\"401\",\"402\",\"403\",\"404\",\"405\",\"406\",\"407\",\"408\",\"409\",\"410\",\"411\",\"412\",\"413\",\"414\",\"415\",\"416\",\"417\",\"418\",\"419\",\"420\",\"421\",\"422\",\"423\",\"424\",\"425\",\"426\",\"427\",\"428\",\"429\",\"430\",\"431\",\"432\",\"433\",\"434\",\"435\",\"436\",\"437\",\"438\",\"439\",\"440\",\"441\",\"442\",\"443\",\"444\",\"445\",\"446\",\"447\",\"448\",\"449\",\"450\",\"451\",\"452\",\"453\",\"454\",\"455\",\"456\",\"457\",\"458\",\"459\",\"460\",\"461\",\"462\",\"463\",\"464\",\"465\",\"466\",\"467\",\"468\",\"469\",\"470\",\"471\",\"472\",\"473\",\"474\",\"475\",\"476\",\"477\",\"478\",\"479\",\"480\",\"481\",\"482\",\"483\",\"484\",\"485\",\"486\",\"487\",\"488\",\"489\",\"490\",\"491\",\"492\",\"493\",\"494\",\"495\",\"496\",\"497\",\"498\",\"499\",\"500\",\"501\",\"502\",\"503\",\"504\",\"505\",\"506\",\"507\",\"508\",\"509\",\"510\",\"511\",\"512\",\"513\",\"514\",\"515\",\"516\",\"517\",\"518\",\"519\",\"520\",\"521\",\"522\",\"523\",\"524\",\"525\",\"526\",\"527\",\"528\",\"529\",\"530\",\"531\",\"532\",\"533\",\"534\",\"535\",\"536\",\"537\",\"538\",\"539\",\"540\",\"541\",\"542\",\"543\",\"544\",\"545\",\"546\",\"547\",\"548\",\"549\",\"550\",\"551\",\"552\",\"553\",\"554\",\"555\",\"556\",\"557\",\"558\",\"559\",\"560\",\"561\",\"562\",\"563\",\"564\",\"565\",\"566\",\"567\",\"568\",\"569\",\"570\",\"571\",\"572\",\"573\",\"574\",\"575\",\"576\",\"577\",\"578\",\"579\",\"580\",\"581\",\"582\",\"583\",\"584\",\"585\",\"586\",\"587\",\"588\",\"589\",\"590\",\"591\",\"592\",\"593\",\"594\",\"595\",\"596\",\"597\",\"598\",\"599\",\"600\",\"601\",\"602\",\"603\",\"604\",\"605\",\"606\",\"607\",\"608\",\"609\",\"610\",\"611\",\"612\",\"613\",\"614\",\"615\",\"616\",\"617\",\"618\",\"619\",\"620\",\"621\",\"622\",\"623\",\"624\",\"625\",\"626\",\"627\",\"628\",\"629\",\"630\",\"631\",\"632\",\"633\",\"634\",\"635\",\"636\",\"637\",\"638\",\"639\",\"640\",\"641\",\"642\",\"643\",\"644\",\"645\",\"646\",\"647\",\"648\",\"649\",\"650\",\"651\",\"652\",\"653\",\"654\",\"655\",\"656\",\"657\",\"658\",\"659\",\"660\",\"661\",\"662\",\"663\",\"664\",\"665\",\"666\",\"667\",\"668\",\"669\",\"670\",\"671\",\"672\",\"673\",\"674\",\"675\",\"676\",\"677\",\"678\",\"679\",\"680\",\"681\",\"682\",\"683\",\"684\",\"685\",\"686\",\"687\",\"688\",\"689\",\"690\",\"691\",\"692\",\"693\",\"694\",\"695\",\"696\",\"697\",\"698\",\"699\",\"700\",\"701\",\"702\",\"703\",\"704\",\"705\",\"706\",\"707\",\"708\",\"709\",\"710\",\"711\",\"712\",\"713\",\"714\",\"715\",\"716\",\"717\",\"718\",\"719\",\"720\",\"721\",\"722\",\"723\",\"724\",\"725\",\"726\",\"727\",\"728\",\"729\",\"730\",\"731\",\"732\",\"733\",\"734\",\"735\",\"736\",\"737\",\"738\",\"739\",\"740\",\"741\",\"742\",\"743\",\"744\",\"745\",\"746\",\"747\",\"748\",\"749\",\"750\",\"751\",\"752\",\"753\",\"754\",\"755\",\"756\",\"757\",\"758\",\"759\",\"760\",\"761\",\"762\",\"763\",\"764\",\"765\",\"766\",\"767\",\"768\",\"769\",\"770\",\"771\",\"772\",\"773\",\"774\",\"775\",\"776\",\"777\",\"778\",\"779\",\"780\",\"781\",\"782\",\"783\",\"784\",\"785\",\"786\",\"787\",\"788\",\"789\",\"790\",\"791\",\"792\",\"793\",\"794\",\"795\",\"796\",\"797\",\"798\",\"799\",\"800\",\"801\",\"802\",\"803\",\"804\",\"805\",\"806\",\"807\",\"808\",\"809\",\"810\",\"811\",\"812\",\"813\",\"814\",\"815\",\"816\",\"817\",\"818\",\"819\",\"820\",\"821\",\"822\",\"823\",\"824\",\"825\",\"826\",\"827\",\"828\",\"829\",\"830\",\"831\",\"832\",\"833\",\"834\",\"835\",\"836\",\"837\",\"838\",\"839\",\"840\",\"841\",\"842\",\"843\",\"844\",\"845\",\"846\",\"847\",\"848\",\"849\",\"850\",\"851\",\"852\",\"853\",\"854\",\"855\",\"856\",\"857\",\"858\",\"859\",\"860\",\"861\",\"862\",\"863\",\"864\",\"865\",\"866\",\"867\",\"868\",\"869\",\"870\",\"871\",\"872\",\"873\",\"874\",\"875\",\"876\",\"877\",\"878\",\"879\",\"880\",\"881\",\"882\",\"883\",\"884\",\"885\",\"886\",\"887\",\"888\",\"889\",\"890\",\"891\",\"892\",\"893\",\"894\",\"895\",\"896\",\"897\",\"898\",\"899\",\"900\",\"901\",\"902\",\"903\",\"904\",\"905\",\"906\",\"907\",\"908\",\"909\",\"910\",\"911\",\"912\",\"913\",\"914\",\"915\",\"916\",\"917\",\"918\",\"919\",\"920\",\"921\",\"922\",\"923\",\"924\",\"925\",\"926\",\"927\",\"928\",\"929\",\"930\",\"931\",\"932\",\"933\",\"934\",\"935\",\"936\",\"937\",\"938\",\"939\",\"940\",\"941\",\"942\",\"943\",\"944\",\"945\",\"946\",\"947\",\"948\",\"949\",\"950\",\"951\",\"952\",\"953\",\"954\",\"955\",\"956\",\"957\",\"958\",\"959\",\"960\",\"961\",\"962\",\"963\",\"964\",\"965\",\"966\",\"967\",\"968\",\"969\",\"970\",\"971\",\"972\",\"973\",\"974\",\"975\",\"976\",\"977\",\"978\",\"979\",\"980\",\"981\",\"982\",\"983\",\"984\",\"985\",\"986\",\"987\",\"988\",\"989\",\"990\",\"991\",\"992\",\"993\",\"994\",\"995\",\"996\",\"997\",\"998\",\"999\",\"1000\",\"1001\",\"1002\",\"1003\",\"1004\",\"1005\",\"1006\",\"1007\",\"1008\",\"1009\",\"1010\",\"1011\",\"1012\",\"1013\",\"1014\",\"1015\",\"1016\",\"1017\",\"1018\",\"1019\",\"1020\",\"1021\",\"1022\",\"1023\",\"1024\",\"1025\",\"1026\",\"1027\",\"1028\",\"1029\",\"1030\",\"1031\",\"1032\",\"1033\",\"1034\",\"1035\",\"1036\",\"1037\",\"1038\",\"1039\",\"1040\",\"1041\",\"1042\",\"1043\",\"1044\",\"1045\",\"1046\",\"1047\",\"1048\",\"1049\",\"1050\",\"1051\",\"1052\",\"1053\",\"1054\",\"1055\",\"1056\",\"1057\",\"1058\",\"1059\",\"1060\",\"1061\",\"1062\",\"1063\",\"1064\",\"1065\",\"1066\",\"1067\",\"1068\",\"1069\",\"1070\",\"1071\",\"1072\",\"1073\",\"1074\",\"1075\",\"1076\",\"1077\",\"1078\",\"1079\",\"1080\",\"1081\",\"1082\",\"1083\",\"1084\",\"1085\",\"1086\",\"1087\",\"1088\",\"1089\",\"1090\",\"1091\",\"1092\",\"1093\",\"1094\",\"1095\",\"1096\",\"1097\",\"1098\",\"1099\",\"1100\",\"1101\",\"1102\",\"1103\",\"1104\",\"1105\",\"1106\",\"1107\",\"1108\",\"1109\",\"1110\",\"1111\",\"1112\",\"1113\",\"1114\",\"1115\",\"1116\",\"1117\",\"1118\",\"1119\",\"1120\",\"1121\",\"1122\",\"1123\",\"1124\",\"1125\",\"1126\",\"1127\",\"1128\",\"1129\",\"1130\",\"1131\",\"1132\",\"1133\",\"1134\",\"1135\",\"1136\",\"1137\",\"1138\",\"1139\",\"1140\",\"1141\",\"1142\",\"1143\",\"1144\",\"1145\",\"1146\",\"1147\",\"1148\",\"1149\",\"1150\",\"1151\",\"1152\",\"1153\",\"1154\",\"1155\",\"1156\",\"1157\",\"1158\",\"1159\",\"1160\",\"1161\",\"1162\",\"1163\",\"1164\",\"1165\",\"1166\",\"1167\",\"1168\",\"1169\",\"1170\",\"1171\",\"1172\",\"1173\",\"1174\",\"1175\",\"1176\",\"1177\",\"1178\",\"1179\",\"1180\",\"1181\",\"1182\",\"1183\",\"1184\",\"1185\",\"1186\",\"1187\",\"1188\",\"1189\",\"1190\",\"1191\",\"1192\",\"1193\",\"1194\",\"1195\",\"1196\",\"1197\",\"1198\",\"1199\",\"1200\",\"1201\",\"1202\",\"1203\",\"1204\",\"1205\",\"1206\",\"1207\",\"1208\",\"1209\",\"1210\",\"1211\",\"1212\",\"1213\",\"1214\",\"1215\",\"1216\",\"1217\",\"1218\",\"1219\",\"1220\",\"1221\",\"1222\",\"1223\",\"1224\",\"1225\",\"1226\",\"1227\",\"1228\",\"1229\",\"1230\",\"1231\",\"1232\",\"1233\",\"1234\",\"1235\",\"1236\",\"1237\",\"1238\",\"1239\",\"1240\",\"1241\",\"1242\",\"1243\",\"1244\",\"1245\",\"1246\",\"1247\",\"1248\",\"1249\",\"1250\",\"1251\",\"1252\",\"1253\",\"1254\",\"1255\",\"1256\",\"1257\",\"1258\",\"1259\",\"1260\",\"1261\",\"1262\",\"1263\",\"1264\",\"1265\",\"1266\",\"1267\",\"1268\",\"1269\",\"1270\",\"1271\",\"1272\",\"1273\",\"1274\",\"1275\",\"1276\",\"1277\",\"1278\",\"1279\",\"1280\",\"1281\",\"1282\",\"1283\",\"1284\",\"1285\",\"1286\",\"1287\",\"1288\",\"1289\",\"1290\",\"1291\",\"1292\",\"1293\",\"1294\",\"1295\",\"1296\",\"1297\",\"1298\",\"1299\",\"1300\",\"1301\",\"1302\",\"1303\",\"1304\",\"1305\",\"1306\",\"1307\",\"1308\",\"1309\",\"1310\",\"1311\",\"1312\",\"1313\",\"1314\",\"1315\",\"1316\",\"1317\",\"1318\",\"1319\",\"1320\",\"1321\",\"1322\",\"1323\",\"1324\",\"1325\",\"1326\",\"1327\",\"1328\",\"1329\",\"1330\",\"1331\",\"1332\",\"1333\",\"1334\",\"1335\",\"1336\",\"1337\",\"1338\",\"1339\",\"1340\",\"1341\",\"1342\",\"1343\",\"1344\",\"1345\",\"1346\",\"1347\",\"1348\",\"1349\",\"1350\",\"1351\",\"1352\",\"1353\",\"1354\",\"1355\",\"1356\",\"1357\",\"1358\",\"1359\",\"1360\",\"1361\",\"1362\",\"1363\",\"1364\",\"1365\",\"1366\",\"1367\",\"1368\",\"1369\",\"1370\",\"1371\",\"1372\",\"1373\",\"1374\",\"1375\",\"1376\",\"1377\",\"1378\",\"1379\",\"1380\",\"1381\",\"1382\",\"1383\",\"1384\",\"1385\",\"1386\",\"1387\",\"1388\",\"1389\",\"1390\",\"1391\",\"1392\",\"1393\",\"1394\",\"1395\",\"1396\",\"1397\",\"1398\",\"1399\",\"1400\",\"1401\",\"1402\",\"1403\",\"1404\",\"1405\",\"1406\",\"1407\",\"1408\",\"1409\",\"1410\",\"1411\",\"1412\",\"1413\",\"1414\",\"1415\",\"1416\",\"1417\",\"1418\",\"1419\",\"1420\",\"1421\",\"1422\",\"1423\",\"1424\",\"1425\",\"1426\",\"1427\",\"1428\",\"1429\",\"1430\",\"1431\",\"1432\",\"1433\",\"1434\",\"1435\",\"1436\",\"1437\",\"1438\",\"1439\",\"1440\",\"1441\",\"1442\",\"1443\",\"1444\",\"1445\",\"1446\",\"1447\",\"1448\",\"1449\",\"1450\",\"1451\",\"1452\",\"1453\",\"1454\",\"1455\",\"1456\",\"1457\",\"1458\",\"1459\",\"1460\",\"1461\",\"1462\",\"1463\",\"1464\",\"1465\",\"1466\",\"1467\",\"1468\",\"1469\",\"1470\",\"1471\",\"1472\",\"1473\",\"1474\",\"1475\",\"1476\",\"1477\",\"1478\",\"1479\",\"1480\",\"1481\",\"1482\",\"1483\",\"1484\",\"1485\",\"1486\",\"1487\",\"1488\",\"1489\",\"1490\",\"1491\",\"1492\",\"1493\",\"1494\",\"1495\",\"1496\",\"1497\",\"1498\",\"1499\",\"1500\",\"1501\",\"1502\",\"1503\",\"1504\",\"1505\",\"1506\",\"1507\",\"1508\",\"1509\",\"1510\",\"1511\",\"1512\",\"1513\",\"1514\",\"1515\",\"1516\",\"1517\",\"1518\",\"1519\",\"1520\",\"1521\",\"1522\",\"1523\",\"1524\",\"1525\",\"1526\",\"1527\",\"1528\",\"1529\",\"1530\",\"1531\",\"1532\",\"1533\",\"1534\",\"1535\",\"1536\",\"1537\",\"1538\",\"1539\",\"1540\",\"1541\",\"1542\",\"1543\",\"1544\",\"1545\",\"1546\",\"1547\",\"1548\",\"1549\",\"1550\",\"1551\",\"1552\",\"1553\",\"1554\",\"1555\",\"1556\",\"1557\",\"1558\",\"1559\",\"1560\",\"1561\",\"1562\",\"1563\",\"1564\",\"1565\",\"1566\",\"1567\",\"1568\",\"1569\",\"1570\",\"1571\",\"1572\",\"1573\",\"1574\",\"1575\",\"1576\",\"1577\",\"1578\",\"1579\",\"1580\",\"1581\",\"1582\",\"1583\",\"1584\",\"1585\",\"1586\",\"1587\",\"1588\",\"1589\",\"1590\",\"1591\",\"1592\",\"1593\",\"1594\",\"1595\",\"1596\",\"1597\",\"1598\",\"1599\",\"1600\",\"1601\",\"1602\",\"1603\",\"1604\",\"1605\",\"1606\",\"1607\",\"1608\",\"1609\",\"1610\",\"1611\",\"1612\",\"1613\",\"1614\",\"1615\",\"1616\",\"1617\",\"1618\",\"1619\",\"1620\",\"1621\",\"1622\",\"1623\",\"1624\",\"1625\",\"1626\",\"1627\",\"1628\",\"1629\",\"1630\",\"1631\",\"1632\",\"1633\",\"1634\",\"1635\",\"1636\",\"1637\",\"1638\",\"1639\",\"1640\",\"1641\",\"1642\",\"1643\",\"1644\",\"1645\",\"1646\",\"1647\",\"1648\",\"1649\",\"1650\",\"1651\",\"1652\",\"1653\",\"1654\",\"1655\",\"1656\",\"1657\",\"1658\",\"1659\",\"1660\",\"1661\",\"1662\",\"1663\",\"1664\",\"1665\",\"1666\",\"1667\",\"1668\",\"1669\",\"1670\",\"1671\",\"1672\",\"1673\",\"1674\",\"1675\",\"1676\",\"1677\",\"1678\",\"1679\",\"1680\",\"1681\",\"1682\",\"1683\",\"1684\",\"1685\",\"1686\",\"1687\",\"1688\",\"1689\",\"1690\",\"1691\",\"1692\",\"1693\",\"1694\",\"1695\",\"1696\",\"1697\",\"1698\",\"1699\",\"1700\",\"1701\",\"1702\",\"1703\",\"1704\",\"1705\",\"1706\",\"1707\",\"1708\",\"1709\",\"1710\",\"1711\",\"1712\",\"1713\",\"1714\",\"1715\",\"1716\",\"1717\",\"1718\",\"1719\",\"1720\",\"1721\",\"1722\",\"1723\",\"1724\",\"1725\",\"1726\",\"1727\",\"1728\",\"1729\",\"1730\",\"1731\",\"1732\",\"1733\",\"1734\",\"1735\",\"1736\",\"1737\",\"1738\",\"1739\",\"1740\",\"1741\",\"1742\",\"1743\",\"1744\",\"1745\",\"1746\",\"1747\",\"1748\",\"1749\",\"1750\",\"1751\",\"1752\",\"1753\",\"1754\",\"1755\",\"1756\",\"1757\",\"1758\",\"1759\",\"1760\",\"1761\",\"1762\",\"1763\",\"1764\",\"1765\",\"1766\",\"1767\",\"1768\",\"1769\",\"1770\",\"1771\",\"1772\",\"1773\",\"1774\",\"1775\",\"1776\",\"1777\",\"1778\",\"1779\",\"1780\",\"1781\",\"1782\",\"1783\",\"1784\",\"1785\",\"1786\",\"1787\",\"1788\",\"1789\",\"1790\",\"1791\",\"1792\",\"1793\",\"1794\",\"1795\",\"1796\",\"1797\",\"1798\",\"1799\",\"1800\",\"1801\",\"1802\",\"1803\",\"1804\",\"1805\",\"1806\",\"1807\",\"1808\",\"1809\",\"1810\",\"1811\",\"1812\",\"1813\",\"1814\",\"1815\",\"1816\",\"1817\",\"1818\",\"1819\",\"1820\",\"1821\",\"1822\",\"1823\",\"1824\",\"1825\",\"1826\",\"1827\",\"1828\",\"1829\",\"1830\",\"1831\",\"1832\",\"1833\",\"1834\",\"1835\",\"1836\",\"1837\",\"1838\",\"1839\",\"1840\",\"1841\",\"1842\",\"1843\",\"1844\",\"1845\",\"1846\",\"1847\",\"1848\",\"1849\",\"1850\",\"1851\",\"1852\",\"1853\",\"1854\",\"1855\",\"1856\",\"1857\",\"1858\",\"1859\",\"1860\",\"1861\",\"1862\",\"1863\",\"1864\",\"1865\",\"1866\",\"1867\",\"1868\",\"1869\",\"1870\",\"1871\",\"1872\",\"1873\",\"1874\",\"1875\",\"1876\",\"1877\",\"1878\",\"1879\",\"1880\",\"1881\",\"1882\",\"1883\",\"1884\",\"1885\",\"1886\",\"1887\",\"1888\",\"1889\",\"1890\",\"1891\",\"1892\",\"1893\",\"1894\",\"1895\",\"1896\",\"1897\",\"1898\",\"1899\",\"1900\",\"1901\",\"1902\",\"1903\",\"1904\",\"1905\",\"1906\",\"1907\",\"1908\",\"1909\",\"1910\",\"1911\",\"1912\",\"1913\",\"1914\",\"1915\",\"1916\",\"1917\",\"1918\",\"1919\",\"1920\",\"1921\",\"1922\",\"1923\",\"1924\",\"1925\",\"1926\",\"1927\",\"1928\",\"1929\",\"1930\",\"1931\",\"1932\",\"1933\",\"1934\",\"1935\",\"1936\",\"1937\",\"1938\",\"1939\",\"1940\",\"1941\",\"1942\",\"1943\",\"1944\",\"1945\",\"1946\",\"1947\",\"1948\",\"1949\",\"1950\",\"1951\",\"1952\",\"1953\",\"1954\",\"1955\",\"1956\",\"1957\",\"1958\",\"1959\",\"1960\",\"1961\",\"1962\",\"1963\",\"1964\",\"1965\",\"1966\",\"1967\",\"1968\",\"1969\",\"1970\",\"1971\",\"1972\",\"1973\",\"1974\",\"1975\",\"1976\",\"1977\",\"1978\",\"1979\",\"1980\",\"1981\",\"1982\",\"1983\",\"1984\",\"1985\",\"1986\",\"1987\",\"1988\",\"1989\",\"1990\",\"1991\",\"1992\",\"1993\",\"1994\",\"1995\",\"1996\",\"1997\",\"1998\",\"1999\",\"2000\",\"2001\",\"2002\",\"2003\",\"2004\",\"2005\",\"2006\",\"2007\",\"2008\",\"2009\",\"2010\",\"2011\",\"2012\",\"2013\",\"2014\",\"2015\",\"2016\",\"2017\",\"2018\",\"2019\",\"2020\",\"2021\",\"2022\",\"2023\",\"2024\",\"2025\",\"2026\",\"2027\",\"2028\",\"2029\",\"2030\",\"2031\",\"2032\",\"2033\",\"2034\",\"2035\",\"2036\",\"2037\",\"2038\",\"2039\",\"2040\",\"2041\",\"2042\",\"2043\",\"2044\",\"2045\",\"2046\",\"2047\",\"2048\",\"2049\",\"2050\",\"2051\",\"2052\",\"2053\",\"2054\",\"2055\",\"2056\",\"2057\",\"2058\",\"2059\",\"2060\",\"2061\",\"2062\",\"2063\",\"2064\",\"2065\",\"2066\",\"2067\",\"2068\",\"2069\",\"2070\",\"2071\",\"2072\",\"2073\",\"2074\",\"2075\",\"2076\",\"2077\",\"2078\",\"2079\",\"2080\",\"2081\",\"2082\",\"2083\",\"2084\",\"2085\",\"2086\",\"2087\",\"2088\",\"2089\",\"2090\",\"2091\",\"2092\",\"2093\",\"2094\",\"2095\",\"2096\",\"2097\",\"2098\",\"2099\",\"2100\",\"2101\",\"2102\",\"2103\",\"2104\",\"2105\",\"2106\",\"2107\",\"2108\",\"2109\",\"2110\",\"2111\",\"2112\",\"2113\",\"2114\",\"2115\",\"2116\",\"2117\",\"2118\",\"2119\",\"2120\",\"2121\",\"2122\",\"2123\",\"2124\",\"2125\",\"2126\",\"2127\",\"2128\",\"2129\",\"2130\",\"2131\",\"2132\",\"2133\",\"2134\",\"2135\",\"2136\",\"2137\",\"2138\",\"2139\",\"2140\",\"2141\",\"2142\",\"2143\",\"2144\",\"2145\",\"2146\",\"2147\",\"2148\",\"2149\",\"2150\",\"2151\",\"2152\",\"2153\",\"2154\",\"2155\",\"2156\",\"2157\",\"2158\",\"2159\",\"2160\",\"2161\",\"2162\",\"2163\",\"2164\",\"2165\",\"2166\",\"2167\",\"2168\",\"2169\",\"2170\",\"2171\",\"2172\",\"2173\",\"2174\",\"2175\",\"2176\",\"2177\",\"2178\",\"2179\",\"2180\",\"2181\",\"2182\",\"2183\",\"2184\",\"2185\",\"2186\",\"2187\",\"2188\",\"2189\",\"2190\",\"2191\",\"2192\",\"2193\",\"2194\",\"2195\",\"2196\",\"2197\",\"2198\",\"2199\",\"2200\",\"2201\",\"2202\",\"2203\",\"2204\",\"2205\",\"2206\",\"2207\",\"2208\",\"2209\",\"2210\",\"2211\",\"2212\",\"2213\",\"2214\",\"2215\",\"2216\",\"2217\",\"2218\",\"2219\",\"2220\",\"2221\",\"2222\",\"2223\",\"2224\",\"2225\",\"2226\",\"2227\",\"2228\",\"2229\",\"2230\",\"2231\",\"2232\",\"2233\",\"2234\",\"2235\",\"2236\",\"2237\",\"2238\",\"2239\",\"2240\",\"2241\",\"2242\",\"2243\",\"2244\",\"2245\",\"2246\",\"2247\",\"2248\",\"2249\",\"2250\",\"2251\",\"2252\",\"2253\",\"2254\",\"2255\",\"2256\",\"2257\",\"2258\",\"2259\",\"2260\",\"2261\",\"2262\",\"2263\",\"2264\",\"2265\",\"2266\",\"2267\",\"2268\",\"2269\",\"2270\",\"2271\",\"2272\",\"2273\",\"2274\",\"2275\",\"2276\",\"2277\",\"2278\",\"2279\",\"2280\",\"2281\",\"2282\",\"2283\",\"2284\",\"2285\",\"2286\",\"2287\",\"2288\",\"2289\",\"2290\",\"2291\",\"2292\",\"2293\",\"2294\",\"2295\",\"2296\",\"2297\",\"2298\",\"2299\",\"2300\",\"2301\",\"2302\",\"2303\",\"2304\",\"2305\",\"2306\",\"2307\",\"2308\",\"2309\",\"2310\",\"2311\",\"2312\",\"2313\",\"2314\",\"2315\",\"2316\",\"2317\",\"2318\",\"2319\",\"2320\",\"2321\",\"2322\",\"2323\",\"2324\",\"2325\",\"2326\",\"2327\",\"2328\",\"2329\",\"2330\",\"2331\",\"2332\",\"2333\",\"2334\",\"2335\",\"2336\",\"2337\",\"2338\",\"2339\",\"2340\",\"2341\",\"2342\",\"2343\",\"2344\",\"2345\",\"2346\",\"2347\",\"2348\",\"2349\",\"2350\",\"2351\",\"2352\",\"2353\",\"2354\",\"2355\",\"2356\",\"2357\",\"2358\",\"2359\",\"2360\",\"2361\",\"2362\",\"2363\",\"2364\",\"2365\",\"2366\",\"2367\",\"2368\",\"2369\",\"2370\",\"2371\",\"2372\",\"2373\",\"2374\",\"2375\",\"2376\",\"2377\",\"2378\",\"2379\",\"2380\",\"2381\",\"2382\",\"2383\",\"2384\",\"2385\",\"2386\",\"2387\",\"2388\",\"2389\",\"2390\",\"2391\",\"2392\",\"2393\",\"2394\",\"2395\",\"2396\",\"2397\",\"2398\",\"2399\",\"2400\",\"2401\",\"2402\",\"2403\",\"2404\",\"2405\",\"2406\",\"2407\",\"2408\",\"2409\",\"2410\",\"2411\",\"2412\",\"2413\",\"2414\",\"2415\",\"2416\",\"2417\",\"2418\",\"2419\",\"2420\",\"2421\",\"2422\",\"2423\",\"2424\",\"2425\",\"2426\",\"2427\",\"2428\",\"2429\",\"2430\",\"2431\",\"2432\",\"2433\",\"2434\",\"2435\",\"2436\",\"2437\",\"2438\",\"2439\",\"2440\",\"2441\",\"2442\",\"2443\",\"2444\",\"2445\",\"2446\",\"2447\",\"2448\",\"2449\",\"2450\",\"2451\",\"2452\",\"2453\",\"2454\",\"2455\",\"2456\",\"2457\",\"2458\",\"2459\",\"2460\",\"2461\",\"2462\",\"2463\",\"2464\",\"2465\",\"2466\",\"2467\",\"2468\",\"2469\",\"2470\",\"2471\",\"2472\",\"2473\",\"2474\",\"2475\",\"2476\",\"2477\",\"2478\",\"2479\",\"2480\",\"2481\",\"2482\",\"2483\",\"2484\",\"2485\",\"2486\",\"2487\",\"2488\",\"2489\",\"2490\",\"2491\",\"2492\",\"2493\",\"2494\",\"2495\",\"2496\",\"2497\",\"2498\",\"2499\",\"2500\",\"2501\",\"2502\",\"2503\",\"2504\",\"2505\",\"2506\",\"2507\",\"2508\",\"2509\",\"2510\",\"2511\",\"2512\",\"2513\",\"2514\",\"2515\",\"2516\",\"2517\",\"2518\",\"2519\",\"2520\",\"2521\",\"2522\",\"2523\",\"2524\",\"2525\",\"2526\",\"2527\",\"2528\",\"2529\",\"2530\",\"2531\",\"2532\",\"2533\",\"2534\",\"2535\",\"2536\",\"2537\",\"2538\",\"2539\",\"2540\",\"2541\",\"2542\",\"2543\",\"2544\",\"2545\",\"2546\",\"2547\",\"2548\",\"2549\",\"2550\",\"2551\",\"2552\",\"2553\",\"2554\",\"2555\",\"2556\",\"2557\",\"2558\",\"2559\",\"2560\",\"2561\",\"2562\",\"2563\",\"2564\",\"2565\",\"2566\",\"2567\",\"2568\",\"2569\",\"2570\",\"2571\",\"2572\",\"2573\",\"2574\",\"2575\",\"2576\",\"2577\",\"2578\",\"2579\",\"2580\",\"2581\",\"2582\",\"2583\",\"2584\",\"2585\",\"2586\",\"2587\",\"2588\",\"2589\",\"2590\",\"2591\",\"2592\",\"2593\",\"2594\",\"2595\",\"2596\",\"2597\",\"2598\",\"2599\",\"2600\",\"2601\",\"2602\",\"2603\",\"2604\",\"2605\",\"2606\",\"2607\",\"2608\",\"2609\",\"2610\",\"2611\",\"2612\",\"2613\",\"2614\",\"2615\",\"2616\",\"2617\",\"2618\",\"2619\",\"2620\",\"2621\",\"2622\",\"2623\",\"2624\",\"2625\",\"2626\",\"2627\",\"2628\",\"2629\",\"2630\",\"2631\",\"2632\",\"2633\",\"2634\",\"2635\",\"2636\",\"2637\",\"2638\",\"2639\",\"2640\",\"2641\",\"2642\",\"2643\",\"2644\",\"2645\",\"2646\",\"2647\",\"2648\",\"2649\",\"2650\",\"2651\",\"2652\",\"2653\",\"2654\",\"2655\",\"2656\",\"2657\",\"2658\",\"2659\",\"2660\",\"2661\",\"2662\",\"2663\",\"2664\",\"2665\",\"2666\",\"2667\",\"2668\",\"2669\",\"2670\",\"2671\",\"2672\",\"2673\",\"2674\",\"2675\",\"2676\",\"2677\",\"2678\",\"2679\",\"2680\",\"2681\",\"2682\",\"2683\",\"2684\",\"2685\",\"2686\",\"2687\",\"2688\",\"2689\",\"2690\",\"2691\",\"2692\",\"2693\",\"2694\",\"2695\",\"2696\",\"2697\",\"2698\",\"2699\",\"2700\",\"2701\",\"2702\",\"2703\",\"2704\",\"2705\",\"2706\",\"2707\",\"2708\",\"2709\",\"2710\",\"2711\",\"2712\",\"2713\",\"2714\",\"2715\",\"2716\",\"2717\",\"2718\",\"2719\",\"2720\",\"2721\",\"2722\",\"2723\",\"2724\",\"2725\",\"2726\",\"2727\",\"2728\",\"2729\",\"2730\",\"2731\",\"2732\",\"2733\",\"2734\",\"2735\",\"2736\",\"2737\",\"2738\",\"2739\",\"2740\",\"2741\",\"2742\",\"2743\",\"2744\",\"2745\",\"2746\",\"2747\",\"2748\",\"2749\",\"2750\",\"2751\",\"2752\",\"2753\",\"2754\",\"2755\",\"2756\",\"2757\",\"2758\",\"2759\",\"2760\",\"2761\",\"2762\",\"2763\",\"2764\",\"2765\",\"2766\",\"2767\",\"2768\",\"2769\",\"2770\",\"2771\",\"2772\",\"2773\",\"2774\",\"2775\",\"2776\",\"2777\",\"2778\",\"2779\",\"2780\",\"2781\",\"2782\",\"2783\",\"2784\",\"2785\",\"2786\",\"2787\",\"2788\",\"2789\",\"2790\",\"2791\",\"2792\",\"2793\",\"2794\",\"2795\",\"2796\",\"2797\",\"2798\",\"2799\",\"2800\",\"2801\",\"2802\",\"2803\",\"2804\",\"2805\",\"2806\",\"2807\",\"2808\",\"2809\",\"2810\",\"2811\",\"2812\",\"2813\",\"2814\",\"2815\",\"2816\",\"2817\",\"2818\",\"2819\",\"2820\",\"2821\",\"2822\",\"2823\",\"2824\",\"2825\",\"2826\",\"2827\",\"2828\",\"2829\",\"2830\",\"2831\",\"2832\",\"2833\",\"2834\",\"2835\",\"2836\",\"2837\",\"2838\",\"2839\",\"2840\",\"2841\",\"2842\",\"2843\",\"2844\",\"2845\",\"2846\",\"2847\",\"2848\",\"2849\",\"2850\",\"2851\",\"2852\",\"2853\",\"2854\",\"2855\",\"2856\",\"2857\",\"2858\",\"2859\",\"2860\",\"2861\",\"2862\",\"2863\",\"2864\",\"2865\",\"2866\",\"2867\",\"2868\",\"2869\",\"2870\",\"2871\",\"2872\",\"2873\",\"2874\",\"2875\",\"2876\",\"2877\",\"2878\",\"2879\",\"2880\",\"2881\",\"2882\",\"2883\",\"2884\",\"2885\",\"2886\",\"2887\",\"2888\",\"2889\",\"2890\",\"2891\",\"2892\",\"2893\",\"2894\",\"2895\",\"2896\",\"2897\",\"2898\",\"2899\",\"2900\",\"2901\",\"2902\",\"2903\",\"2904\",\"2905\",\"2906\",\"2907\",\"2908\",\"2909\",\"2910\",\"2911\",\"2912\",\"2913\",\"2914\",\"2915\",\"2916\",\"2917\",\"2918\",\"2919\",\"2920\",\"2921\",\"2922\",\"2923\",\"2924\",\"2925\",\"2926\",\"2927\",\"2928\",\"2929\",\"2930\",\"2931\",\"2932\",\"2933\",\"2934\",\"2935\",\"2936\",\"2937\",\"2938\",\"2939\",\"2940\",\"2941\",\"2942\",\"2943\",\"2944\",\"2945\",\"2946\",\"2947\",\"2948\",\"2949\",\"2950\",\"2951\",\"2952\",\"2953\",\"2954\",\"2955\",\"2956\",\"2957\",\"2958\",\"2959\",\"2960\",\"2961\",\"2962\",\"2963\",\"2964\",\"2965\",\"2966\",\"2967\",\"2968\",\"2969\",\"2970\",\"2971\",\"2972\",\"2973\",\"2974\",\"2975\",\"2976\",\"2977\",\"2978\",\"2979\",\"2980\",\"2981\",\"2982\",\"2983\",\"2984\",\"2985\",\"2986\",\"2987\",\"2988\",\"2989\",\"2990\",\"2991\",\"2992\",\"2993\",\"2994\",\"2995\",\"2996\",\"2997\",\"2998\",\"2999\",\"3000\",\"3001\",\"3002\",\"3003\",\"3004\",\"3005\",\"3006\",\"3007\",\"3008\",\"3009\",\"3010\",\"3011\",\"3012\",\"3013\",\"3014\",\"3015\",\"3016\",\"3017\",\"3018\",\"3019\",\"3020\",\"3021\",\"3022\",\"3023\",\"3024\",\"3025\",\"3026\",\"3027\",\"3028\",\"3029\",\"3030\",\"3031\",\"3032\",\"3033\",\"3034\",\"3035\",\"3036\",\"3037\",\"3038\",\"3039\",\"3040\",\"3041\",\"3042\",\"3043\",\"3044\",\"3045\",\"3046\",\"3047\",\"3048\",\"3049\",\"3050\",\"3051\",\"3052\",\"3053\",\"3054\",\"3055\",\"3056\",\"3057\",\"3058\",\"3059\",\"3060\",\"3061\",\"3062\",\"3063\",\"3064\",\"3065\",\"3066\",\"3067\",\"3068\",\"3069\",\"3070\",\"3071\",\"3072\",\"3073\",\"3074\",\"3075\",\"3076\",\"3077\",\"3078\",\"3079\",\"3080\",\"3081\",\"3082\",\"3083\",\"3084\",\"3085\",\"3086\",\"3087\",\"3088\",\"3089\",\"3090\",\"3091\",\"3092\",\"3093\",\"3094\",\"3095\",\"3096\",\"3097\",\"3098\",\"3099\",\"3100\",\"3101\",\"3102\",\"3103\",\"3104\",\"3105\",\"3106\",\"3107\",\"3108\",\"3109\",\"3110\",\"3111\",\"3112\",\"3113\",\"3114\",\"3115\",\"3116\",\"3117\",\"3118\",\"3119\",\"3120\",\"3121\",\"3122\",\"3123\",\"3124\",\"3125\",\"3126\",\"3127\",\"3128\",\"3129\",\"3130\",\"3131\",\"3132\",\"3133\",\"3134\",\"3135\",\"3136\",\"3137\",\"3138\",\"3139\",\"3140\",\"3141\",\"3142\",\"3143\",\"3144\",\"3145\",\"3146\",\"3147\",\"3148\",\"3149\",\"3150\",\"3151\",\"3152\",\"3153\",\"3154\",\"3155\",\"3156\",\"3157\",\"3158\",\"3159\",\"3160\",\"3161\",\"3162\",\"3163\",\"3164\",\"3165\",\"3166\",\"3167\",\"3168\",\"3169\",\"3170\",\"3171\",\"3172\",\"3173\",\"3174\",\"3175\",\"3176\",\"3177\",\"3178\",\"3179\",\"3180\",\"3181\",\"3182\",\"3183\",\"3184\",\"3185\",\"3186\",\"3187\",\"3188\",\"3189\",\"3190\",\"3191\",\"3192\",\"3193\",\"3194\",\"3195\",\"3196\",\"3197\",\"3198\",\"3199\",\"3200\",\"3201\",\"3202\",\"3203\",\"3204\",\"3205\",\"3206\",\"3207\",\"3208\",\"3209\",\"3210\",\"3211\",\"3212\",\"3213\",\"3214\",\"3215\",\"3216\",\"3217\",\"3218\",\"3219\",\"3220\",\"3221\",\"3222\",\"3223\",\"3224\",\"3225\",\"3226\",\"3227\",\"3228\",\"3229\",\"3230\",\"3231\",\"3232\",\"3233\",\"3234\",\"3235\",\"3236\",\"3237\",\"3238\",\"3239\",\"3240\",\"3241\",\"3242\",\"3243\",\"3244\",\"3245\",\"3246\",\"3247\",\"3248\",\"3249\",\"3250\",\"3251\",\"3252\",\"3253\",\"3254\",\"3255\",\"3256\",\"3257\",\"3258\",\"3259\",\"3260\",\"3261\",\"3262\",\"3263\",\"3264\",\"3265\",\"3266\",\"3267\",\"3268\",\"3269\",\"3270\",\"3271\",\"3272\",\"3273\",\"3274\",\"3275\",\"3276\",\"3277\",\"3278\",\"3279\",\"3280\",\"3281\",\"3282\",\"3283\",\"3284\",\"3285\",\"3286\",\"3287\",\"3288\",\"3289\",\"3290\",\"3291\",\"3292\",\"3293\",\"3294\",\"3295\",\"3296\",\"3297\",\"3298\",\"3299\",\"3300\",\"3301\",\"3302\",\"3303\",\"3304\",\"3305\",\"3306\",\"3307\",\"3308\",\"3309\",\"3310\",\"3311\",\"3312\",\"3313\",\"3314\",\"3315\",\"3316\",\"3317\",\"3318\",\"3319\",\"3320\",\"3321\",\"3322\",\"3323\",\"3324\",\"3325\",\"3326\",\"3327\",\"3328\",\"3329\",\"3330\",\"3331\",\"3332\",\"3333\",\"3334\",\"3335\",\"3336\",\"3337\",\"3338\",\"3339\",\"3340\",\"3341\",\"3342\",\"3343\",\"3344\",\"3345\",\"3346\",\"3347\",\"3348\",\"3349\",\"3350\",\"3351\",\"3352\",\"3353\",\"3354\",\"3355\",\"3356\",\"3357\",\"3358\",\"3359\",\"3360\",\"3361\",\"3362\",\"3363\",\"3364\",\"3365\",\"3366\",\"3367\",\"3368\",\"3369\",\"3370\",\"3371\",\"3372\",\"3373\",\"3374\",\"3375\",\"3376\",\"3377\",\"3378\",\"3379\",\"3380\",\"3381\",\"3382\",\"3383\",\"3384\",\"3385\",\"3386\",\"3387\",\"3388\",\"3389\",\"3390\",\"3391\",\"3392\",\"3393\",\"3394\",\"3395\",\"3396\",\"3397\",\"3398\",\"3399\",\"3400\",\"3401\",\"3402\",\"3403\",\"3404\",\"3405\",\"3406\",\"3407\",\"3408\",\"3409\",\"3410\",\"3411\",\"3412\",\"3413\",\"3414\",\"3415\",\"3416\",\"3417\",\"3418\",\"3419\",\"3420\",\"3421\",\"3422\",\"3423\",\"3424\",\"3425\",\"3426\",\"3427\",\"3428\",\"3429\",\"3430\",\"3431\",\"3432\",\"3433\",\"3434\",\"3435\",\"3436\",\"3437\",\"3438\",\"3439\",\"3440\",\"3441\",\"3442\",\"3443\",\"3444\",\"3445\",\"3446\",\"3447\",\"3448\",\"3449\",\"3450\",\"3451\",\"3452\",\"3453\",\"3454\",\"3455\",\"3456\",\"3457\",\"3458\",\"3459\",\"3460\",\"3461\",\"3462\",\"3463\",\"3464\",\"3465\",\"3466\",\"3467\",\"3468\",\"3469\",\"3470\",\"3471\",\"3472\",\"3473\",\"3474\",\"3475\",\"3476\",\"3477\",\"3478\",\"3479\",\"3480\",\"3481\",\"3482\",\"3483\",\"3484\",\"3485\",\"3486\",\"3487\",\"3488\",\"3489\",\"3490\",\"3491\",\"3492\",\"3493\",\"3494\",\"3495\",\"3496\",\"3497\",\"3498\",\"3499\",\"3500\",\"3501\",\"3502\",\"3503\",\"3504\",\"3505\",\"3506\",\"3507\",\"3508\",\"3509\",\"3510\",\"3511\",\"3512\",\"3513\",\"3514\",\"3515\",\"3516\",\"3517\",\"3518\",\"3519\",\"3520\",\"3521\",\"3522\",\"3523\",\"3524\",\"3525\",\"3526\",\"3527\",\"3528\",\"3529\",\"3530\",\"3531\",\"3532\",\"3533\",\"3534\",\"3535\",\"3536\",\"3537\",\"3538\",\"3539\",\"3540\",\"3541\",\"3542\",\"3543\",\"3544\",\"3545\",\"3546\",\"3547\",\"3548\",\"3549\",\"3550\",\"3551\",\"3552\",\"3553\",\"3554\",\"3555\",\"3556\",\"3557\",\"3558\",\"3559\",\"3560\",\"3561\",\"3562\",\"3563\",\"3564\",\"3565\",\"3566\",\"3567\",\"3568\",\"3569\",\"3570\",\"3571\",\"3572\",\"3573\",\"3574\",\"3575\",\"3576\",\"3577\",\"3578\",\"3579\",\"3580\",\"3581\",\"3582\",\"3583\",\"3584\",\"3585\",\"3586\",\"3587\",\"3588\",\"3589\",\"3590\",\"3591\",\"3592\",\"3593\",\"3594\",\"3595\",\"3596\",\"3597\",\"3598\",\"3599\",\"3600\",\"3601\",\"3602\",\"3603\",\"3604\",\"3605\",\"3606\",\"3607\",\"3608\",\"3609\",\"3610\",\"3611\",\"3612\",\"3613\",\"3614\",\"3615\",\"3616\",\"3617\",\"3618\",\"3619\",\"3620\",\"3621\",\"3622\",\"3623\",\"3624\",\"3625\",\"3626\",\"3627\",\"3628\",\"3629\",\"3630\",\"3631\",\"3632\",\"3633\",\"3634\",\"3635\",\"3636\",\"3637\",\"3638\",\"3639\",\"3640\",\"3641\",\"3642\",\"3643\",\"3644\",\"3645\",\"3646\",\"3647\",\"3648\",\"3649\",\"3650\",\"3651\",\"3652\",\"3653\",\"3654\",\"3655\",\"3656\",\"3657\",\"3658\",\"3659\",\"3660\",\"3661\",\"3662\",\"3663\",\"3664\",\"3665\",\"3666\",\"3667\",\"3668\",\"3669\",\"3670\",\"3671\",\"3672\",\"3673\",\"3674\",\"3675\",\"3676\",\"3677\",\"3678\",\"3679\",\"3680\",\"3681\",\"3682\",\"3683\",\"3684\",\"3685\",\"3686\",\"3687\",\"3688\",\"3689\",\"3690\",\"3691\",\"3692\",\"3693\",\"3694\",\"3695\",\"3696\",\"3697\",\"3698\",\"3699\",\"3700\",\"3701\",\"3702\",\"3703\",\"3704\",\"3705\",\"3706\",\"3707\",\"3708\",\"3709\",\"3710\",\"3711\",\"3712\",\"3713\",\"3714\",\"3715\",\"3716\",\"3717\",\"3718\",\"3719\",\"3720\",\"3721\",\"3722\",\"3723\",\"3724\",\"3725\",\"3726\",\"3727\",\"3728\",\"3729\",\"3730\",\"3731\",\"3732\",\"3733\",\"3734\",\"3735\",\"3736\",\"3737\",\"3738\",\"3739\",\"3740\",\"3741\",\"3742\",\"3743\",\"3744\",\"3745\",\"3746\",\"3747\",\"3748\",\"3749\",\"3750\",\"3751\",\"3752\",\"3753\",\"3754\",\"3755\",\"3756\",\"3757\",\"3758\",\"3759\",\"3760\",\"3761\",\"3762\",\"3763\",\"3764\",\"3765\",\"3766\",\"3767\",\"3768\",\"3769\",\"3770\",\"3771\",\"3772\",\"3773\",\"3774\",\"3775\",\"3776\",\"3777\",\"3778\",\"3779\",\"3780\",\"3781\",\"3782\",\"3783\",\"3784\",\"3785\",\"3786\",\"3787\",\"3788\",\"3789\",\"3790\",\"3791\",\"3792\",\"3793\",\"3794\",\"3795\",\"3796\",\"3797\",\"3798\",\"3799\",\"3800\",\"3801\",\"3802\",\"3803\",\"3804\",\"3805\",\"3806\",\"3807\",\"3808\",\"3809\",\"3810\",\"3811\",\"3812\",\"3813\",\"3814\",\"3815\",\"3816\",\"3817\",\"3818\",\"3819\",\"3820\",\"3821\",\"3822\",\"3823\",\"3824\",\"3825\",\"3826\",\"3827\",\"3828\",\"3829\",\"3830\",\"3831\",\"3832\",\"3833\",\"3834\",\"3835\",\"3836\",\"3837\",\"3838\",\"3839\",\"3840\",\"3841\",\"3842\",\"3843\",\"3844\",\"3845\",\"3846\",\"3847\",\"3848\",\"3849\",\"3850\",\"3851\",\"3852\",\"3853\",\"3854\",\"3855\",\"3856\",\"3857\",\"3858\",\"3859\",\"3860\",\"3861\",\"3862\",\"3863\",\"3864\",\"3865\",\"3866\",\"3867\",\"3868\",\"3869\",\"3870\",\"3871\",\"3872\",\"3873\",\"3874\",\"3875\",\"3876\",\"3877\",\"3878\",\"3879\",\"3880\",\"3881\",\"3882\",\"3883\",\"3884\",\"3885\",\"3886\",\"3887\",\"3888\",\"3889\",\"3890\",\"3891\",\"3892\",\"3893\",\"3894\",\"3895\",\"3896\",\"3897\",\"3898\",\"3899\",\"3900\",\"3901\",\"3902\",\"3903\",\"3904\",\"3905\",\"3906\",\"3907\",\"3908\",\"3909\",\"3910\",\"3911\",\"3912\",\"3913\",\"3914\",\"3915\",\"3916\",\"3917\",\"3918\",\"3919\",\"3920\",\"3921\",\"3922\",\"3923\",\"3924\",\"3925\",\"3926\",\"3927\",\"3928\",\"3929\",\"3930\",\"3931\",\"3932\",\"3933\",\"3934\",\"3935\",\"3936\",\"3937\",\"3938\",\"3939\",\"3940\",\"3941\",\"3942\",\"3943\",\"3944\",\"3945\",\"3946\",\"3947\",\"3948\",\"3949\",\"3950\",\"3951\",\"3952\",\"3953\",\"3954\",\"3955\",\"3956\",\"3957\",\"3958\",\"3959\",\"3960\",\"3961\",\"3962\",\"3963\",\"3964\",\"3965\",\"3966\",\"3967\",\"3968\",\"3969\",\"3970\",\"3971\",\"3972\",\"3973\",\"3974\",\"3975\",\"3976\",\"3977\",\"3978\",\"3979\",\"3980\",\"3981\",\"3982\",\"3983\",\"3984\",\"3985\",\"3986\",\"3987\",\"3988\",\"3989\",\"3990\",\"3991\",\"3992\",\"3993\",\"3994\",\"3995\",\"3996\",\"3997\",\"3998\",\"3999\",\"4000\",\"4001\",\"4002\",\"4003\",\"4004\",\"4005\",\"4006\",\"4007\",\"4008\",\"4009\",\"4010\",\"4011\",\"4012\",\"4013\",\"4014\",\"4015\",\"4016\",\"4017\",\"4018\",\"4019\",\"4020\",\"4021\",\"4022\",\"4023\",\"4024\",\"4025\",\"4026\",\"4027\",\"4028\",\"4029\",\"4030\",\"4031\",\"4032\",\"4033\",\"4034\",\"4035\",\"4036\",\"4037\",\"4038\",\"4039\",\"4040\",\"4041\",\"4042\",\"4043\",\"4044\",\"4045\",\"4046\",\"4047\",\"4048\",\"4049\",\"4050\",\"4051\",\"4052\",\"4053\",\"4054\",\"4055\",\"4056\",\"4057\",\"4058\",\"4059\",\"4060\",\"4061\",\"4062\",\"4063\",\"4064\",\"4065\",\"4066\",\"4067\",\"4068\",\"4069\",\"4070\",\"4071\",\"4072\",\"4073\",\"4074\",\"4075\",\"4076\",\"4077\",\"4078\",\"4079\",\"4080\",\"4081\",\"4082\",\"4083\",\"4084\",\"4085\",\"4086\",\"4087\",\"4088\",\"4089\",\"4090\",\"4091\",\"4092\",\"4093\",\"4094\",\"4095\",\"4096\",\"4097\",\"4098\",\"4099\",\"4100\",\"4101\",\"4102\",\"4103\",\"4104\",\"4105\",\"4106\",\"4107\",\"4108\",\"4109\",\"4110\",\"4111\",\"4112\",\"4113\",\"4114\",\"4115\",\"4116\",\"4117\",\"4118\",\"4119\",\"4120\",\"4121\",\"4122\",\"4123\",\"4124\",\"4125\",\"4126\",\"4127\",\"4128\",\"4129\",\"4130\",\"4131\",\"4132\",\"4133\",\"4134\",\"4135\",\"4136\",\"4137\",\"4138\",\"4139\",\"4140\",\"4141\",\"4142\",\"4143\",\"4144\",\"4145\",\"4146\",\"4147\",\"4148\",\"4149\",\"4150\",\"4151\",\"4152\",\"4153\",\"4154\",\"4155\",\"4156\",\"4157\",\"4158\",\"4159\",\"4160\",\"4161\",\"4162\",\"4163\",\"4164\",\"4165\",\"4166\",\"4167\",\"4168\",\"4169\",\"4170\",\"4171\",\"4172\",\"4173\",\"4174\",\"4175\",\"4176\",\"4177\",\"4178\",\"4179\",\"4180\",\"4181\",\"4182\",\"4183\",\"4184\",\"4185\",\"4186\",\"4187\",\"4188\",\"4189\",\"4190\",\"4191\",\"4192\",\"4193\",\"4194\",\"4195\",\"4196\",\"4197\",\"4198\",\"4199\",\"4200\",\"4201\",\"4202\",\"4203\",\"4204\",\"4205\",\"4206\",\"4207\",\"4208\",\"4209\",\"4210\",\"4211\",\"4212\",\"4213\",\"4214\",\"4215\",\"4216\",\"4217\",\"4218\",\"4219\",\"4220\",\"4221\",\"4222\",\"4223\",\"4224\",\"4225\",\"4226\",\"4227\",\"4228\",\"4229\",\"4230\",\"4231\",\"4232\",\"4233\",\"4234\",\"4235\",\"4236\",\"4237\",\"4238\",\"4239\",\"4240\",\"4241\",\"4242\",\"4243\",\"4244\",\"4245\",\"4246\",\"4247\",\"4248\",\"4249\",\"4250\",\"4251\",\"4252\",\"4253\",\"4254\",\"4255\",\"4256\",\"4257\",\"4258\",\"4259\",\"4260\",\"4261\",\"4262\",\"4263\",\"4264\",\"4265\",\"4266\",\"4267\",\"4268\",\"4269\",\"4270\",\"4271\",\"4272\",\"4273\",\"4274\",\"4275\",\"4276\",\"4277\",\"4278\",\"4279\",\"4280\",\"4281\",\"4282\",\"4283\",\"4284\",\"4285\",\"4286\",\"4287\",\"4288\",\"4289\",\"4290\",\"4291\",\"4292\",\"4293\",\"4294\",\"4295\",\"4296\",\"4297\",\"4298\",\"4299\",\"4300\",\"4301\",\"4302\",\"4303\",\"4304\",\"4305\",\"4306\",\"4307\",\"4308\",\"4309\",\"4310\",\"4311\",\"4312\",\"4313\",\"4314\",\"4315\",\"4316\",\"4317\",\"4318\",\"4319\",\"4320\",\"4321\",\"4322\",\"4323\",\"4324\",\"4325\",\"4326\",\"4327\",\"4328\",\"4329\",\"4330\",\"4331\",\"4332\",\"4333\",\"4334\",\"4335\",\"4336\",\"4337\",\"4338\",\"4339\",\"4340\",\"4341\",\"4342\",\"4343\",\"4344\",\"4345\",\"4346\",\"4347\",\"4348\",\"4349\",\"4350\",\"4351\",\"4352\",\"4353\",\"4354\",\"4355\",\"4356\",\"4357\",\"4358\",\"4359\",\"4360\",\"4361\",\"4362\",\"4363\",\"4364\",\"4365\",\"4366\",\"4367\",\"4368\",\"4369\",\"4370\",\"4371\",\"4372\",\"4373\",\"4374\",\"4375\",\"4376\",\"4377\",\"4378\",\"4379\",\"4380\",\"4381\",\"4382\",\"4383\",\"4384\",\"4385\",\"4386\",\"4387\",\"4388\",\"4389\",\"4390\",\"4391\",\"4392\",\"4393\",\"4394\",\"4395\",\"4396\",\"4397\",\"4398\",\"4399\",\"4400\",\"4401\",\"4402\",\"4403\",\"4404\",\"4405\",\"4406\",\"4407\",\"4408\",\"4409\",\"4410\",\"4411\",\"4412\",\"4413\",\"4414\",\"4415\",\"4416\",\"4417\",\"4418\",\"4419\",\"4420\",\"4421\",\"4422\",\"4423\",\"4424\",\"4425\",\"4426\",\"4427\",\"4428\",\"4429\",\"4430\",\"4431\",\"4432\",\"4433\",\"4434\",\"4435\",\"4436\",\"4437\",\"4438\",\"4439\",\"4440\",\"4441\",\"4442\",\"4443\",\"4444\",\"4445\",\"4446\",\"4447\",\"4448\",\"4449\",\"4450\",\"4451\",\"4452\",\"4453\",\"4454\",\"4455\",\"4456\",\"4457\",\"4458\",\"4459\",\"4460\",\"4461\",\"4462\",\"4463\",\"4464\",\"4465\",\"4466\",\"4467\",\"4468\",\"4469\",\"4470\",\"4471\",\"4472\",\"4473\",\"4474\",\"4475\",\"4476\",\"4477\",\"4478\",\"4479\",\"4480\",\"4481\",\"4482\",\"4483\",\"4484\",\"4485\",\"4486\",\"4487\",\"4488\",\"4489\",\"4490\",\"4491\",\"4492\",\"4493\",\"4494\",\"4495\",\"4496\",\"4497\",\"4498\",\"4499\",\"4500\",\"4501\",\"4502\",\"4503\",\"4504\",\"4505\",\"4506\",\"4507\",\"4508\",\"4509\",\"4510\",\"4511\",\"4512\",\"4513\",\"4514\",\"4515\",\"4516\",\"4517\",\"4518\",\"4519\",\"4520\",\"4521\",\"4522\",\"4523\",\"4524\",\"4525\",\"4526\",\"4527\",\"4528\",\"4529\",\"4530\",\"4531\",\"4532\",\"4533\",\"4534\",\"4535\",\"4536\",\"4537\",\"4538\",\"4539\",\"4540\",\"4541\",\"4542\",\"4543\",\"4544\",\"4545\",\"4546\",\"4547\",\"4548\",\"4549\",\"4550\",\"4551\",\"4552\",\"4553\",\"4554\",\"4555\",\"4556\",\"4557\",\"4558\",\"4559\",\"4560\",\"4561\",\"4562\",\"4563\",\"4564\",\"4565\",\"4566\",\"4567\",\"4568\",\"4569\",\"4570\",\"4571\",\"4572\",\"4573\",\"4574\",\"4575\",\"4576\",\"4577\",\"4578\",\"4579\",\"4580\",\"4581\",\"4582\",\"4583\",\"4584\",\"4585\",\"4586\",\"4587\",\"4588\",\"4589\",\"4590\",\"4591\",\"4592\",\"4593\",\"4594\",\"4595\",\"4596\",\"4597\",\"4598\",\"4599\",\"4600\",\"4601\",\"4602\",\"4603\",\"4604\",\"4605\",\"4606\",\"4607\",\"4608\",\"4609\",\"4610\",\"4611\",\"4612\",\"4613\",\"4614\",\"4615\",\"4616\",\"4617\",\"4618\",\"4619\",\"4620\",\"4621\",\"4622\",\"4623\",\"4624\",\"4625\",\"4626\",\"4627\",\"4628\",\"4629\",\"4630\",\"4631\",\"4632\",\"4633\",\"4634\",\"4635\",\"4636\",\"4637\",\"4638\",\"4639\",\"4640\",\"4641\",\"4642\",\"4643\",\"4644\",\"4645\",\"4646\",\"4647\",\"4648\",\"4649\",\"4650\",\"4651\",\"4652\",\"4653\",\"4654\",\"4655\",\"4656\",\"4657\",\"4658\",\"4659\",\"4660\",\"4661\",\"4662\",\"4663\",\"4664\",\"4665\",\"4666\",\"4667\",\"4668\",\"4669\",\"4670\",\"4671\",\"4672\",\"4673\",\"4674\",\"4675\",\"4676\",\"4677\",\"4678\",\"4679\",\"4680\",\"4681\",\"4682\",\"4683\",\"4684\",\"4685\",\"4686\",\"4687\",\"4688\",\"4689\",\"4690\",\"4691\",\"4692\",\"4693\",\"4694\",\"4695\",\"4696\",\"4697\",\"4698\",\"4699\",\"4700\",\"4701\",\"4702\",\"4703\",\"4704\",\"4705\",\"4706\",\"4707\",\"4708\",\"4709\",\"4710\",\"4711\",\"4712\",\"4713\",\"4714\",\"4715\",\"4716\",\"4717\",\"4718\",\"4719\",\"4720\",\"4721\",\"4722\",\"4723\",\"4724\",\"4725\",\"4726\",\"4727\",\"4728\",\"4729\",\"4730\",\"4731\",\"4732\",\"4733\",\"4734\",\"4735\",\"4736\",\"4737\",\"4738\",\"4739\",\"4740\",\"4741\",\"4742\",\"4743\",\"4744\",\"4745\",\"4746\",\"4747\",\"4748\",\"4749\",\"4750\",\"4751\",\"4752\",\"4753\",\"4754\",\"4755\",\"4756\",\"4757\",\"4758\",\"4759\",\"4760\",\"4761\",\"4762\",\"4763\",\"4764\",\"4765\",\"4766\",\"4767\",\"4768\",\"4769\",\"4770\",\"4771\",\"4772\",\"4773\",\"4774\",\"4775\",\"4776\",\"4777\",\"4778\",\"4779\",\"4780\",\"4781\",\"4782\",\"4783\",\"4784\",\"4785\",\"4786\",\"4787\",\"4788\",\"4789\",\"4790\",\"4791\",\"4792\",\"4793\",\"4794\",\"4795\",\"4796\",\"4797\",\"4798\",\"4799\",\"4800\",\"4801\",\"4802\",\"4803\",\"4804\",\"4805\",\"4806\",\"4807\",\"4808\",\"4809\",\"4810\",\"4811\",\"4812\",\"4813\",\"4814\",\"4815\",\"4816\",\"4817\",\"4818\",\"4819\",\"4820\",\"4821\",\"4822\",\"4823\",\"4824\",\"4825\",\"4826\",\"4827\",\"4828\",\"4829\",\"4830\",\"4831\",\"4832\",\"4833\",\"4834\",\"4835\",\"4836\",\"4837\",\"4838\",\"4839\",\"4840\",\"4841\",\"4842\",\"4843\",\"4844\",\"4845\",\"4846\",\"4847\",\"4848\",\"4849\",\"4850\",\"4851\",\"4852\",\"4853\",\"4854\",\"4855\",\"4856\",\"4857\",\"4858\",\"4859\",\"4860\",\"4861\",\"4862\",\"4863\",\"4864\",\"4865\",\"4866\",\"4867\",\"4868\",\"4869\",\"4870\",\"4871\",\"4872\",\"4873\",\"4874\",\"4875\",\"4876\",\"4877\",\"4878\",\"4879\",\"4880\",\"4881\",\"4882\",\"4883\",\"4884\",\"4885\",\"4886\",\"4887\",\"4888\",\"4889\",\"4890\",\"4891\",\"4892\",\"4893\",\"4894\",\"4895\",\"4896\",\"4897\",\"4898\",\"4899\",\"4900\",\"4901\",\"4902\",\"4903\",\"4904\",\"4905\",\"4906\",\"4907\",\"4908\",\"4909\",\"4910\",\"4911\",\"4912\",\"4913\",\"4914\",\"4915\",\"4916\",\"4917\",\"4918\",\"4919\",\"4920\",\"4921\",\"4922\",\"4923\",\"4924\",\"4925\",\"4926\",\"4927\",\"4928\",\"4929\",\"4930\",\"4931\",\"4932\",\"4933\",\"4934\",\"4935\",\"4936\",\"4937\",\"4938\",\"4939\",\"4940\",\"4941\",\"4942\",\"4943\",\"4944\",\"4945\",\"4946\",\"4947\",\"4948\",\"4949\",\"4950\",\"4951\",\"4952\",\"4953\",\"4954\",\"4955\",\"4956\",\"4957\",\"4958\",\"4959\",\"4960\",\"4961\",\"4962\",\"4963\",\"4964\",\"4965\",\"4966\",\"4967\",\"4968\",\"4969\",\"4970\",\"4971\",\"4972\",\"4973\",\"4974\",\"4975\",\"4976\",\"4977\",\"4978\",\"4979\",\"4980\",\"4981\",\"4982\",\"4983\",\"4984\",\"4985\",\"4986\",\"4987\",\"4988\",\"4989\",\"4990\",\"4991\",\"4992\",\"4993\",\"4994\",\"4995\",\"4996\",\"4997\",\"4998\",\"4999\"],[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767,768,769,770,771,772,773,774,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799,800,801,802,803,804,805,806,807,808,809,810,811,812,813,814,815,816,817,818,819,820,821,822,823,824,825,826,827,828,829,830,831,832,833,834,835,836,837,838,839,840,841,842,843,844,845,846,847,848,849,850,851,852,853,854,855,856,857,858,859,860,861,862,863,864,865,866,867,868,869,870,871,872,873,874,875,876,877,878,879,880,881,882,883,884,885,886,887,888,889,890,891,892,893,894,895,896,897,898,899,900,901,902,903,904,905,906,907,908,909,910,911,912,913,914,915,916,917,918,919,920,921,922,923,924,925,926,927,928,929,930,931,932,933,934,935,936,937,938,939,940,941,942,943,944,945,946,947,948,949,950,951,952,953,954,955,956,957,958,959,960,961,962,963,964,965,966,967,968,969,970,971,972,973,974,975,976,977,978,979,980,981,982,983,984,985,986,987,988,989,990,991,992,993,994,995,996,997,998,999,1000,1001,1002,1003,1004,1005,1006,1007,1008,1009,1010,1011,1012,1013,1014,1015,1016,1017,1018,1019,1020,1021,1022,1023,1024,1025,1026,1027,1028,1029,1030,1031,1032,1033,1034,1035,1036,1037,1038,1039,1040,1041,1042,1043,1044,1045,1046,1047,1048,1049,1050,1051,1052,1053,1054,1055,1056,1057,1058,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073,1074,1075,1076,1077,1078,1079,1080,1081,1082,1083,1084,1085,1086,1087,1088,1089,1090,1091,1092,1093,1094,1095,1096,1097,1098,1099,1100,1101,1102,1103,1104,1105,1106,1107,1108,1109,1110,1111,1112,1113,1114,1115,1116,1117,1118,1119,1120,1121,1122,1123,1124,1125,1126,1127,1128,1129,1130,1131,1132,1133,1134,1135,1136,1137,1138,1139,1140,1141,1142,1143,1144,1145,1146,1147,1148,1149,1150,1151,1152,1153,1154,1155,1156,1157,1158,1159,1160,1161,1162,1163,1164,1165,1166,1167,1168,1169,1170,1171,1172,1173,1174,1175,1176,1177,1178,1179,1180,1181,1182,1183,1184,1185,1186,1187,1188,1189,1190,1191,1192,1193,1194,1195,1196,1197,1198,1199,1200,1201,1202,1203,1204,1205,1206,1207,1208,1209,1210,1211,1212,1213,1214,1215,1216,1217,1218,1219,1220,1221,1222,1223,1224,1225,1226,1227,1228,1229,1230,1231,1232,1233,1234,1235,1236,1237,1238,1239,1240,1241,1242,1243,1244,1245,1246,1247,1248,1249,1250,1251,1252,1253,1254,1255,1256,1257,1258,1259,1260,1261,1262,1263,1264,1265,1266,1267,1268,1269,1270,1271,1272,1273,1274,1275,1276,1277,1278,1279,1280,1281,1282,1283,1284,1285,1286,1287,1288,1289,1290,1291,1292,1293,1294,1295,1296,1297,1298,1299,1300,1301,1302,1303,1304,1305,1306,1307,1308,1309,1310,1311,1312,1313,1314,1315,1316,1317,1318,1319,1320,1321,1322,1323,1324,1325,1326,1327,1328,1329,1330,1331,1332,1333,1334,1335,1336,1337,1338,1339,1340,1341,1342,1343,1344,1345,1346,1347,1348,1349,1350,1351,1352,1353,1354,1355,1356,1357,1358,1359,1360,1361,1362,1363,1364,1365,1366,1367,1368,1369,1370,1371,1372,1373,1374,1375,1376,1377,1378,1379,1380,1381,1382,1383,1384,1385,1386,1387,1388,1389,1390,1391,1392,1393,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403,1404,1405,1406,1407,1408,1409,1410,1411,1412,1413,1414,1415,1416,1417,1418,1419,1420,1421,1422,1423,1424,1425,1426,1427,1428,1429,1430,1431,1432,1433,1434,1435,1436,1437,1438,1439,1440,1441,1442,1443,1444,1445,1446,1447,1448,1449,1450,1451,1452,1453,1454,1455,1456,1457,1458,1459,1460,1461,1462,1463,1464,1465,1466,1467,1468,1469,1470,1471,1472,1473,1474,1475,1476,1477,1478,1479,1480,1481,1482,1483,1484,1485,1486,1487,1488,1489,1490,1491,1492,1493,1494,1495,1496,1497,1498,1499,1500,1501,1502,1503,1504,1505,1506,1507,1508,1509,1510,1511,1512,1513,1514,1515,1516,1517,1518,1519,1520,1521,1522,1523,1524,1525,1526,1527,1528,1529,1530,1531,1532,1533,1534,1535,1536,1537,1538,1539,1540,1541,1542,1543,1544,1545,1546,1547,1548,1549,1550,1551,1552,1553,1554,1555,1556,1557,1558,1559,1560,1561,1562,1563,1564,1565,1566,1567,1568,1569,1570,1571,1572,1573,1574,1575,1576,1577,1578,1579,1580,1581,1582,1583,1584,1585,1586,1587,1588,1589,1590,1591,1592,1593,1594,1595,1596,1597,1598,1599,1600,1601,1602,1603,1604,1605,1606,1607,1608,1609,1610,1611,1612,1613,1614,1615,1616,1617,1618,1619,1620,1621,1622,1623,1624,1625,1626,1627,1628,1629,1630,1631,1632,1633,1634,1635,1636,1637,1638,1639,1640,1641,1642,1643,1644,1645,1646,1647,1648,1649,1650,1651,1652,1653,1654,1655,1656,1657,1658,1659,1660,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727,1728,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1785,1786,1787,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1914,1915,1916,1917,1918,1919,1920,1921,1922,1923,1924,1925,1926,1927,1928,1929,1930,1931,1932,1933,1934,1935,1936,1937,1938,1939,1940,1941,1942,1943,1944,1945,1946,1947,1948,1949,1950,1951,1952,1953,1954,1955,1956,1957,1958,1959,1960,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025,2026,2027,2028,2029,2030,2031,2032,2033,2034,2035,2036,2037,2038,2039,2040,2041,2042,2043,2044,2045,2046,2047,2048,2049,2050,2051,2052,2053,2054,2055,2056,2057,2058,2059,2060,2061,2062,2063,2064,2065,2066,2067,2068,2069,2070,2071,2072,2073,2074,2075,2076,2077,2078,2079,2080,2081,2082,2083,2084,2085,2086,2087,2088,2089,2090,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100,2101,2102,2103,2104,2105,2106,2107,2108,2109,2110,2111,2112,2113,2114,2115,2116,2117,2118,2119,2120,2121,2122,2123,2124,2125,2126,2127,2128,2129,2130,2131,2132,2133,2134,2135,2136,2137,2138,2139,2140,2141,2142,2143,2144,2145,2146,2147,2148,2149,2150,2151,2152,2153,2154,2155,2156,2157,2158,2159,2160,2161,2162,2163,2164,2165,2166,2167,2168,2169,2170,2171,2172,2173,2174,2175,2176,2177,2178,2179,2180,2181,2182,2183,2184,2185,2186,2187,2188,2189,2190,2191,2192,2193,2194,2195,2196,2197,2198,2199,2200,2201,2202,2203,2204,2205,2206,2207,2208,2209,2210,2211,2212,2213,2214,2215,2216,2217,2218,2219,2220,2221,2222,2223,2224,2225,2226,2227,2228,2229,2230,2231,2232,2233,2234,2235,2236,2237,2238,2239,2240,2241,2242,2243,2244,2245,2246,2247,2248,2249,2250,2251,2252,2253,2254,2255,2256,2257,2258,2259,2260,2261,2262,2263,2264,2265,2266,2267,2268,2269,2270,2271,2272,2273,2274,2275,2276,2277,2278,2279,2280,2281,2282,2283,2284,2285,2286,2287,2288,2289,2290,2291,2292,2293,2294,2295,2296,2297,2298,2299,2300,2301,2302,2303,2304,2305,2306,2307,2308,2309,2310,2311,2312,2313,2314,2315,2316,2317,2318,2319,2320,2321,2322,2323,2324,2325,2326,2327,2328,2329,2330,2331,2332,2333,2334,2335,2336,2337,2338,2339,2340,2341,2342,2343,2344,2345,2346,2347,2348,2349,2350,2351,2352,2353,2354,2355,2356,2357,2358,2359,2360,2361,2362,2363,2364,2365,2366,2367,2368,2369,2370,2371,2372,2373,2374,2375,2376,2377,2378,2379,2380,2381,2382,2383,2384,2385,2386,2387,2388,2389,2390,2391,2392,2393,2394,2395,2396,2397,2398,2399,2400,2401,2402,2403,2404,2405,2406,2407,2408,2409,2410,2411,2412,2413,2414,2415,2416,2417,2418,2419,2420,2421,2422,2423,2424,2425,2426,2427,2428,2429,2430,2431,2432,2433,2434,2435,2436,2437,2438,2439,2440,2441,2442,2443,2444,2445,2446,2447,2448,2449,2450,2451,2452,2453,2454,2455,2456,2457,2458,2459,2460,2461,2462,2463,2464,2465,2466,2467,2468,2469,2470,2471,2472,2473,2474,2475,2476,2477,2478,2479,2480,2481,2482,2483,2484,2485,2486,2487,2488,2489,2490,2491,2492,2493,2494,2495,2496,2497,2498,2499,2500,2501,2502,2503,2504,2505,2506,2507,2508,2509,2510,2511,2512,2513,2514,2515,2516,2517,2518,2519,2520,2521,2522,2523,2524,2525,2526,2527,2528,2529,2530,2531,2532,2533,2534,2535,2536,2537,2538,2539,2540,2541,2542,2543,2544,2545,2546,2547,2548,2549,2550,2551,2552,2553,2554,2555,2556,2557,2558,2559,2560,2561,2562,2563,2564,2565,2566,2567,2568,2569,2570,2571,2572,2573,2574,2575,2576,2577,2578,2579,2580,2581,2582,2583,2584,2585,2586,2587,2588,2589,2590,2591,2592,2593,2594,2595,2596,2597,2598,2599,2600,2601,2602,2603,2604,2605,2606,2607,2608,2609,2610,2611,2612,2613,2614,2615,2616,2617,2618,2619,2620,2621,2622,2623,2624,2625,2626,2627,2628,2629,2630,2631,2632,2633,2634,2635,2636,2637,2638,2639,2640,2641,2642,2643,2644,2645,2646,2647,2648,2649,2650,2651,2652,2653,2654,2655,2656,2657,2658,2659,2660,2661,2662,2663,2664,2665,2666,2667,2668,2669,2670,2671,2672,2673,2674,2675,2676,2677,2678,2679,2680,2681,2682,2683,2684,2685,2686,2687,2688,2689,2690,2691,2692,2693,2694,2695,2696,2697,2698,2699,2700,2701,2702,2703,2704,2705,2706,2707,2708,2709,2710,2711,2712,2713,2714,2715,2716,2717,2718,2719,2720,2721,2722,2723,2724,2725,2726,2727,2728,2729,2730,2731,2732,2733,2734,2735,2736,2737,2738,2739,2740,2741,2742,2743,2744,2745,2746,2747,2748,2749,2750,2751,2752,2753,2754,2755,2756,2757,2758,2759,2760,2761,2762,2763,2764,2765,2766,2767,2768,2769,2770,2771,2772,2773,2774,2775,2776,2777,2778,2779,2780,2781,2782,2783,2784,2785,2786,2787,2788,2789,2790,2791,2792,2793,2794,2795,2796,2797,2798,2799,2800,2801,2802,2803,2804,2805,2806,2807,2808,2809,2810,2811,2812,2813,2814,2815,2816,2817,2818,2819,2820,2821,2822,2823,2824,2825,2826,2827,2828,2829,2830,2831,2832,2833,2834,2835,2836,2837,2838,2839,2840,2841,2842,2843,2844,2845,2846,2847,2848,2849,2850,2851,2852,2853,2854,2855,2856,2857,2858,2859,2860,2861,2862,2863,2864,2865,2866,2867,2868,2869,2870,2871,2872,2873,2874,2875,2876,2877,2878,2879,2880,2881,2882,2883,2884,2885,2886,2887,2888,2889,2890,2891,2892,2893,2894,2895,2896,2897,2898,2899,2900,2901,2902,2903,2904,2905,2906,2907,2908,2909,2910,2911,2912,2913,2914,2915,2916,2917,2918,2919,2920,2921,2922,2923,2924,2925,2926,2927,2928,2929,2930,2931,2932,2933,2934,2935,2936,2937,2938,2939,2940,2941,2942,2943,2944,2945,2946,2947,2948,2949,2950,2951,2952,2953,2954,2955,2956,2957,2958,2959,2960,2961,2962,2963,2964,2965,2966,2967,2968,2969,2970,2971,2972,2973,2974,2975,2976,2977,2978,2979,2980,2981,2982,2983,2984,2985,2986,2987,2988,2989,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999,3000,3001,3002,3003,3004,3005,3006,3007,3008,3009,3010,3011,3012,3013,3014,3015,3016,3017,3018,3019,3020,3021,3022,3023,3024,3025,3026,3027,3028,3029,3030,3031,3032,3033,3034,3035,3036,3037,3038,3039,3040,3041,3042,3043,3044,3045,3046,3047,3048,3049,3050,3051,3052,3053,3054,3055,3056,3057,3058,3059,3060,3061,3062,3063,3064,3065,3066,3067,3068,3069,3070,3071,3072,3073,3074,3075,3076,3077,3078,3079,3080,3081,3082,3083,3084,3085,3086,3087,3088,3089,3090,3091,3092,3093,3094,3095,3096,3097,3098,3099,3100,3101,3102,3103,3104,3105,3106,3107,3108,3109,3110,3111,3112,3113,3114,3115,3116,3117,3118,3119,3120,3121,3122,3123,3124,3125,3126,3127,3128,3129,3130,3131,3132,3133,3134,3135,3136,3137,3138,3139,3140,3141,3142,3143,3144,3145,3146,3147,3148,3149,3150,3151,3152,3153,3154,3155,3156,3157,3158,3159,3160,3161,3162,3163,3164,3165,3166,3167,3168,3169,3170,3171,3172,3173,3174,3175,3176,3177,3178,3179,3180,3181,3182,3183,3184,3185,3186,3187,3188,3189,3190,3191,3192,3193,3194,3195,3196,3197,3198,3199,3200,3201,3202,3203,3204,3205,3206,3207,3208,3209,3210,3211,3212,3213,3214,3215,3216,3217,3218,3219,3220,3221,3222,3223,3224,3225,3226,3227,3228,3229,3230,3231,3232,3233,3234,3235,3236,3237,3238,3239,3240,3241,3242,3243,3244,3245,3246,3247,3248,3249,3250,3251,3252,3253,3254,3255,3256,3257,3258,3259,3260,3261,3262,3263,3264,3265,3266,3267,3268,3269,3270,3271,3272,3273,3274,3275,3276,3277,3278,3279,3280,3281,3282,3283,3284,3285,3286,3287,3288,3289,3290,3291,3292,3293,3294,3295,3296,3297,3298,3299,3300,3301,3302,3303,3304,3305,3306,3307,3308,3309,3310,3311,3312,3313,3314,3315,3316,3317,3318,3319,3320,3321,3322,3323,3324,3325,3326,3327,3328,3329,3330,3331,3332,3333,3334,3335,3336,3337,3338,3339,3340,3341,3342,3343,3344,3345,3346,3347,3348,3349,3350,3351,3352,3353,3354,3355,3356,3357,3358,3359,3360,3361,3362,3363,3364,3365,3366,3367,3368,3369,3370,3371,3372,3373,3374,3375,3376,3377,3378,3379,3380,3381,3382,3383,3384,3385,3386,3387,3388,3389,3390,3391,3392,3393,3394,3395,3396,3397,3398,3399,3400,3401,3402,3403,3404,3405,3406,3407,3408,3409,3410,3411,3412,3413,3414,3415,3416,3417,3418,3419,3420,3421,3422,3423,3424,3425,3426,3427,3428,3429,3430,3431,3432,3433,3434,3435,3436,3437,3438,3439,3440,3441,3442,3443,3444,3445,3446,3447,3448,3449,3450,3451,3452,3453,3454,3455,3456,3457,3458,3459,3460,3461,3462,3463,3464,3465,3466,3467,3468,3469,3470,3471,3472,3473,3474,3475,3476,3477,3478,3479,3480,3481,3482,3483,3484,3485,3486,3487,3488,3489,3490,3491,3492,3493,3494,3495,3496,3497,3498,3499,3500,3501,3502,3503,3504,3505,3506,3507,3508,3509,3510,3511,3512,3513,3514,3515,3516,3517,3518,3519,3520,3521,3522,3523,3524,3525,3526,3527,3528,3529,3530,3531,3532,3533,3534,3535,3536,3537,3538,3539,3540,3541,3542,3543,3544,3545,3546,3547,3548,3549,3550,3551,3552,3553,3554,3555,3556,3557,3558,3559,3560,3561,3562,3563,3564,3565,3566,3567,3568,3569,3570,3571,3572,3573,3574,3575,3576,3577,3578,3579,3580,3581,3582,3583,3584,3585,3586,3587,3588,3589,3590,3591,3592,3593,3594,3595,3596,3597,3598,3599,3600,3601,3602,3603,3604,3605,3606,3607,3608,3609,3610,3611,3612,3613,3614,3615,3616,3617,3618,3619,3620,3621,3622,3623,3624,3625,3626,3627,3628,3629,3630,3631,3632,3633,3634,3635,3636,3637,3638,3639,3640,3641,3642,3643,3644,3645,3646,3647,3648,3649,3650,3651,3652,3653,3654,3655,3656,3657,3658,3659,3660,3661,3662,3663,3664,3665,3666,3667,3668,3669,3670,3671,3672,3673,3674,3675,3676,3677,3678,3679,3680,3681,3682,3683,3684,3685,3686,3687,3688,3689,3690,3691,3692,3693,3694,3695,3696,3697,3698,3699,3700,3701,3702,3703,3704,3705,3706,3707,3708,3709,3710,3711,3712,3713,3714,3715,3716,3717,3718,3719,3720,3721,3722,3723,3724,3725,3726,3727,3728,3729,3730,3731,3732,3733,3734,3735,3736,3737,3738,3739,3740,3741,3742,3743,3744,3745,3746,3747,3748,3749,3750,3751,3752,3753,3754,3755,3756,3757,3758,3759,3760,3761,3762,3763,3764,3765,3766,3767,3768,3769,3770,3771,3772,3773,3774,3775,3776,3777,3778,3779,3780,3781,3782,3783,3784,3785,3786,3787,3788,3789,3790,3791,3792,3793,3794,3795,3796,3797,3798,3799,3800,3801,3802,3803,3804,3805,3806,3807,3808,3809,3810,3811,3812,3813,3814,3815,3816,3817,3818,3819,3820,3821,3822,3823,3824,3825,3826,3827,3828,3829,3830,3831,3832,3833,3834,3835,3836,3837,3838,3839,3840,3841,3842,3843,3844,3845,3846,3847,3848,3849,3850,3851,3852,3853,3854,3855,3856,3857,3858,3859,3860,3861,3862,3863,3864,3865,3866,3867,3868,3869,3870,3871,3872,3873,3874,3875,3876,3877,3878,3879,3880,3881,3882,3883,3884,3885,3886,3887,3888,3889,3890,3891,3892,3893,3894,3895,3896,3897,3898,3899,3900,3901,3902,3903,3904,3905,3906,3907,3908,3909,3910,3911,3912,3913,3914,3915,3916,3917,3918,3919,3920,3921,3922,3923,3924,3925,3926,3927,3928,3929,3930,3931,3932,3933,3934,3935,3936,3937,3938,3939,3940,3941,3942,3943,3944,3945,3946,3947,3948,3949,3950,3951,3952,3953,3954,3955,3956,3957,3958,3959,3960,3961,3962,3963,3964,3965,3966,3967,3968,3969,3970,3971,3972,3973,3974,3975,3976,3977,3978,3979,3980,3981,3982,3983,3984,3985,3986,3987,3988,3989,3990,3991,3992,3993,3994,3995,3996,3997,3998,3999,4000,4001,4002,4003,4004,4005,4006,4007,4008,4009,4010,4011,4012,4013,4014,4015,4016,4017,4018,4019,4020,4021,4022,4023,4024,4025,4026,4027,4028,4029,4030,4031,4032,4033,4034,4035,4036,4037,4038,4039,4040,4041,4042,4043,4044,4045,4046,4047,4048,4049,4050,4051,4052,4053,4054,4055,4056,4057,4058,4059,4060,4061,4062,4063,4064,4065,4066,4067,4068,4069,4070,4071,4072,4073,4074,4075,4076,4077,4078,4079,4080,4081,4082,4083,4084,4085,4086,4087,4088,4089,4090,4091,4092,4093,4094,4095,4096,4097,4098,4099,4100,4101,4102,4103,4104,4105,4106,4107,4108,4109,4110,4111,4112,4113,4114,4115,4116,4117,4118,4119,4120,4121,4122,4123,4124,4125,4126,4127,4128,4129,4130,4131,4132,4133,4134,4135,4136,4137,4138,4139,4140,4141,4142,4143,4144,4145,4146,4147,4148,4149,4150,4151,4152,4153,4154,4155,4156,4157,4158,4159,4160,4161,4162,4163,4164,4165,4166,4167,4168,4169,4170,4171,4172,4173,4174,4175,4176,4177,4178,4179,4180,4181,4182,4183,4184,4185,4186,4187,4188,4189,4190,4191,4192,4193,4194,4195,4196,4197,4198,4199,4200,4201,4202,4203,4204,4205,4206,4207,4208,4209,4210,4211,4212,4213,4214,4215,4216,4217,4218,4219,4220,4221,4222,4223,4224,4225,4226,4227,4228,4229,4230,4231,4232,4233,4234,4235,4236,4237,4238,4239,4240,4241,4242,4243,4244,4245,4246,4247,4248,4249,4250,4251,4252,4253,4254,4255,4256,4257,4258,4259,4260,4261,4262,4263,4264,4265,4266,4267,4268,4269,4270,4271,4272,4273,4274,4275,4276,4277,4278,4279,4280,4281,4282,4283,4284,4285,4286,4287,4288,4289,4290,4291,4292,4293,4294,4295,4296,4297,4298,4299,4300,4301,4302,4303,4304,4305,4306,4307,4308,4309,4310,4311,4312,4313,4314,4315,4316,4317,4318,4319,4320,4321,4322,4323,4324,4325,4326,4327,4328,4329,4330,4331,4332,4333,4334,4335,4336,4337,4338,4339,4340,4341,4342,4343,4344,4345,4346,4347,4348,4349,4350,4351,4352,4353,4354,4355,4356,4357,4358,4359,4360,4361,4362,4363,4364,4365,4366,4367,4368,4369,4370,4371,4372,4373,4374,4375,4376,4377,4378,4379,4380,4381,4382,4383,4384,4385,4386,4387,4388,4389,4390,4391,4392,4393,4394,4395,4396,4397,4398,4399,4400,4401,4402,4403,4404,4405,4406,4407,4408,4409,4410,4411,4412,4413,4414,4415,4416,4417,4418,4419,4420,4421,4422,4423,4424,4425,4426,4427,4428,4429,4430,4431,4432,4433,4434,4435,4436,4437,4438,4439,4440,4441,4442,4443,4444,4445,4446,4447,4448,4449,4450,4451,4452,4453,4454,4455,4456,4457,4458,4459,4460,4461,4462,4463,4464,4465,4466,4467,4468,4469,4470,4471,4472,4473,4474,4475,4476,4477,4478,4479,4480,4481,4482,4483,4484,4485,4486,4487,4488,4489,4490,4491,4492,4493,4494,4495,4496,4497,4498,4499,4500,4501,4502,4503,4504,4505,4506,4507,4508,4509,4510,4511,4512,4513,4514,4515,4516,4517,4518,4519,4520,4521,4522,4523,4524,4525,4526,4527,4528,4529,4530,4531,4532,4533,4534,4535,4536,4537,4538,4539,4540,4541,4542,4543,4544,4545,4546,4547,4548,4549,4550,4551,4552,4553,4554,4555,4556,4557,4558,4559,4560,4561,4562,4563,4564,4565,4566,4567,4568,4569,4570,4571,4572,4573,4574,4575,4576,4577,4578,4579,4580,4581,4582,4583,4584,4585,4586,4587,4588,4589,4590,4591,4592,4593,4594,4595,4596,4597,4598,4599,4600,4601,4602,4603,4604,4605,4606,4607,4608,4609,4610,4611,4612,4613,4614,4615,4616,4617,4618,4619,4620,4621,4622,4623,4624,4625,4626,4627,4628,4629,4630,4631,4632,4633,4634,4635,4636,4637,4638,4639,4640,4641,4642,4643,4644,4645,4646,4647,4648,4649,4650,4651,4652,4653,4654,4655,4656,4657,4658,4659,4660,4661,4662,4663,4664,4665,4666,4667,4668,4669,4670,4671,4672,4673,4674,4675,4676,4677,4678,4679,4680,4681,4682,4683,4684,4685,4686,4687,4688,4689,4690,4691,4692,4693,4694,4695,4696,4697,4698,4699,4700,4701,4702,4703,4704,4705,4706,4707,4708,4709,4710,4711,4712,4713,4714,4715,4716,4717,4718,4719,4720,4721,4722,4723,4724,4725,4726,4727,4728,4729,4730,4731,4732,4733,4734,4735,4736,4737,4738,4739,4740,4741,4742,4743,4744,4745,4746,4747,4748,4749,4750,4751,4752,4753,4754,4755,4756,4757,4758,4759,4760,4761,4762,4763,4764,4765,4766,4767,4768,4769,4770,4771,4772,4773,4774,4775,4776,4777,4778,4779,4780,4781,4782,4783,4784,4785,4786,4787,4788,4789,4790,4791,4792,4793,4794,4795,4796,4797,4798,4799,4800,4801,4802,4803,4804,4805,4806,4807,4808,4809,4810,4811,4812,4813,4814,4815,4816,4817,4818,4819,4820,4821,4822,4823,4824,4825,4826,4827,4828,4829,4830,4831,4832,4833,4834,4835,4836,4837,4838,4839,4840,4841,4842,4843,4844,4845,4846,4847,4848,4849,4850,4851,4852,4853,4854,4855,4856,4857,4858,4859,4860,4861,4862,4863,4864,4865,4866,4867,4868,4869,4870,4871,4872,4873,4874,4875,4876,4877,4878,4879,4880,4881,4882,4883,4884,4885,4886,4887,4888,4889,4890,4891,4892,4893,4894,4895,4896,4897,4898,4899,4900,4901,4902,4903,4904,4905,4906,4907,4908,4909,4910,4911,4912,4913,4914,4915,4916,4917,4918,4919,4920,4921,4922,4923,4924,4925,4926,4927,4928,4929,4930,4931,4932,4933,4934,4935,4936,4937,4938,4939,4940,4941,4942,4943,4944,4945,4946,4947,4948,4949,4950,4951,4952,4953,4954,4955,4956,4957,4958,4959,4960,4961,4962,4963,4964,4965,4966,4967,4968,4969,4970,4971,4972,4973,4974,4975,4976,4977,4978,4979,4980,4981,4982,4983,4984,4985,4986,4987,4988,4989,4990,4991,4992,4993,4994,4995,4996,4997,4998,4999],[0.3427399903521461,0.1113243761996158,0.4275012083131968,3.469509043927654,0.09040767386091134,0.7914230019493165,0.6408450704225376,0.3427399903521458,0.09040767386091089,1.493069306930695,2.425214754926734,0.6408450704225379,0.6408450704225324,1.227362204724409,0.0486344034499275,0.7698490014612763,0.04863440344992814,0.7267639902676393,0.2162097162097188,2.518227848101263,0.3638996138996172,1.515354135710751,0.2162097162097201,3.252057613168729,0.9430317848410776,1.874937593609586,0.04863440344992728,2.518227848101264,0.4700048379293679,0.4275012083131953,1.761952191235066,11.34972842486423,0.1951923076923077,0.1113243761996158,0.02777777777777809,1.404150197628467,0.1322611617858847,0.3427399903521471,0.7698490014612779,0.3638996138996113,0.1113243761996168,0.2162097162097184,0.09040767386091014,0.04863440344992823,0.7698490014612729,1.604714640198516,0.8779296874999972,0.4700048379293664,1.559990084283588,0.705252918287936,0.7267639902676413,1.739422598307617,0.8779296875000017,0.02777777777777792,0.216209716209714,0.5125907990314732,0.9430317848410763,1.943000000000006,3.180020544427331,0.8779296875000033,0.1951923076923081,0.555259331071255,0.7698490014612798,2.286397984886646,0.3427399903521501,0.5552593310712565,0.9430317848410789,1.784504235176883,4.766595857673933,0.1741950985103313,1.761952191235063,0.3427399903521462,0.3427399903521474,0.8779296875000013,0.09040767386091,2.125502008032128,0.258305247953782,0.1951923076923092,4.613287453679205,0.3427399903521474,0.1741950985103294,0.6408450704225362,2.94149207971386,2.98900255754476,2.518227848101276,0.04863440344992836,0.6837627613028707,2.564875823618852,0.8779296874999977,0.9865394028389548,1.515354135710748,0.3427399903521465,0.9865394028389597,4.536997885835096,0.6837627613028714,0.7914230019493161,0.4275012083131921,0.899609184171961,2.309475806451617,1.073810691515448,2.51822784810126,0.533914728682173,1.249384539635647,0.342739990352144,0.3427399903521435,1.161425061425063,0.6837627613028699,1.161425061425065,0.3427399903521498,0.006941120153183253,0.1322611617858855,2.471674253920082,1.649528067560852,1.117574864997552,0.3427399903521472,0.2583052479537776,1.293494332183344,0.5125907990314791,0.4700048379293658,1.426347009391988,2.471674253920085,8.883861671469754,1.38197530864197,1.55999008428359,1.404150197628466,0.3004819277108458,1.205361534677821,1.784504235176877,0.2162097162097162,6.852354570637126,0.04863440344992804,0.132261161785886,0.4487427466150873,0.4700048379293657,0.6408450704225367,2.658456069070596,1.493069306930698,0.7052529182879378,0.363899613899612,0.5125907990314824,2.989002557544766,1.161425061425063,0.1113243761996155,1.404150197628459,4.66428192898781,3.132119035402767,0.8996091841719558,0.1322611617858858,0.048634403449928,0.7698490014612774,2.51822784810127,1.073810691515447,0.3638996138996162,1.249384539635644,0.3004819277108401,1.874937593609587,1.073810691515451,1.559990084283591,0.1322611617858847,0.1322611617858849,0.2583052479537811,0.006941120153183443,0.8562713518789684,1.051960784313719,0.3427399903521455,1.404150197628454,2.011266900350524,0.3427399903521475,0.3004819277108438,0.7267639902676398,0.04863440344992852,1.205361534677815,0.6837627613028677,0.5125907990314814,0.6837627613028668,0.3638996138996114,0.7698490014612767,0.3427399903521471,0.3638996138996132,2.011266900350529,1.761952191235057,0.8779296874999928,0.02777777777777808,0.877929687500002,1.426347009391987,0.02777777777777847,1.227362204724406,0.2583052479537824,2.681910569105698,0.9865394028389648,0.5339147286821752,0.1741950985103315,0.02777777777777689,3.060450819672131,0.8562713518789689,3.180020544427337,0.7914230019493189,0.09040767386090992,0.09040767386091179,0.006941120153183816,0.02777777777777816,0.3427399903521451,1.249384539635645,4.86934539648751,0.4700048379293662,0.1322611617858863,1.784504235176886,1.073810691515455,0.8996091841719629,0.555259331071252,0.2162097162097165,0.9430317848410824,1.051960784313728,2.989002557544763,0.6408450704225302,0.6408450704225338,1.493069306930699,2.681910569105693,1.559990084283592,0.5339147286821718,2.194318753142289,3.836458333333332,2.870408163265313,0.5339147286821718,1.249384539635645,0.3427399903521466,2.011266900350534,2.10260913196187,1.965732866433212,1.426347009391993,3.861125586242832,0.4275012083131968,0.7698490014612777,0.3427399903521449,1.205361534677819,0.2583052479537805,0.1113243761996162,2.011266900350526,0.1741950985103306,0.3004819277108458,0.006941120153183601,0.1322611617858858,1.426347009391993,0.7914230019493177,1.051960784313728,0.04863440344992854,0.5339147286821746,0.5125907990314786,0.5552593310712566,0.3004819277108443,0.1951923076923064,1.051960784313719,1.426347009391996,2.378849066128215,0.3638996138996174,0.3638996138996141,0.6837627613028648,0.5552593310712566,1.073810691515435,3.132119035402773,1.205361534677821,2.125502008032124,0.2583052479537811,0.7267639902676457,2.965235173824149,0.7267639902676444,1.874937593609596,0.09040767386091129,0.2162097162097175,0.1322611617858857,0.1741950985103314,1.227362204724412,0.4275012083131908,0.6408450704225253,2.941492079713853,0.3427399903521471,0.8779296874999991,0.5552593310712516,1.874937593609586,0.5552593310712559,0.1322611617858854,4.034518828451891,0.1113243761996203,0.04863440344992592,0.7698490014612793,0.6408450704225354,0.174195098510333,0.7698490014612793,0.4275012083131948,0.2162097162097157,0.9865394028389622,0.2162097162097213,0.6408450704225362,0.3004819277108454,1.559990084283589,0.1322611617858877,1.515354135710752,0.555259331071253,0.5339147286821733,0.6408450704225347,1.784504235176881,0.8779296875000047,0.4487427466150857,0.4487427466150884,1.559990084283591,0.7052529182879373,1.761952191235062,1.227362204724411,0.1951923076923071,0.5125907990314807,0.8779296875000022,0.1951923076923083,1.073810691515447,0.04863440344992805,0.09040767386091109,1.227362204724416,0.1322611617858868,1.559990084283598,2.752417302798978,1.16142506142506,1.249384539635646,3.132119035402781,0.2162097162097172,1.559990084283591,4.034518828451878,0.3638996138996147,0.4275012083131988,1.404150197628458,0.3004819277108464,1.293494332183341,0.9430317848410811,0.6837627613028684,0.9430317848410762,4.209186351706036,0.1741950985103295,0.3427399903521474,0.4700048379293611,0.1951923076923071,2.125502008032147,1.852295409181637,1.739422598307619,2.799541518084566,1.227362204724412,1.073810691515446,1.227362204724402,1.874937593609584,2.286397984886651,2.518227848101267,1.051960784313729,0.8779296875000009,1.874937593609591,0.5125907990314817,0.8996091841719593,0.3004819277108455,0.174195098510331,0.9865394028389638,2.564875823618856,0.8562713518789673,0.3638996138996102,0.6408450704225372,1.051960784313727,0.04863440344992878,1.40415019762846,0.5125907990314775,0.5125907990314792,1.649528067560855,4.03451882845189,1.852295409181635,0.4275012083131939,0.6408450704225325,0.3004819277108431,0.7698490014612784,0.8996091841719581,0.5125907990314823,1.205361534677821,1.784504235176879,2.194318753142294,0.6408450704225321,2.425214754926739,0.09040767386091243,0.3427399903521487,0.1113243761996162,0.9865394028389638,1.073810691515446,0.6837627613028684,1.38197530864198,0.7914230019493191,0.9430317848410763,1.965732866433218,0.8779296875000012,0.986539402838969,0.6408450704225365,0.3427399903521485,0.3638996138996146,0.5339147286821727,0.899609184171962,0.5339147286821692,0.448742746615089,0.6408450704225356,0.1322611617858823,1.051960784313725,0.2583052479537786,0.5339147286821729,0.04863440344992823,3.518106570098306,0.5125907990314773,2.989002557544759,0.8779296875000022,0.3638996138996141,0.342739990352149,0.3638996138996166,0.3427399903521446,1.559990084283594,0.04863440344992905,0.216209716209715,1.559990084283599,0.2162097162097167,0.2162097162097159,0.9430317848410751,0.3427399903521497,0.8779296875000022,1.649528067560863,1.161425061425061,0.9430317848410797,1.739422598307624,1.493069306930696,0.09040767386091131,2.194318753142285,2.194318753142287,1.073810691515449,0.1322611617858842,2.471674253920078,0.1951923076923095,0.4275012083131992,0.1113243761996162,0.1322611617858843,1.205361534677815,0.2583052479537838,0.4700048379293683,1.515354135710752,0.5552593310712564,0.2162097162097163,2.12550200803213,1.051960784313723,0.7698490014612678,1.42634700939199,0.5125907990314784,3.518106570098303,0.5125907990314793,0.7267639902676397,0.7914230019493235,0.006941120153183193,0.5125907990314761,1.404150197628468,0.1113243761996166,0.1741950985103317,1.161425061425071,0.7914230019493109,0.5339147286821716,2.518227848101264,2.6584560690706,2.011266900350524,2.870408163265299,0.1322611617858863,0.1322611617858859,1.965732866433226,0.7267639902676469,1.051960784313728,2.989002557544755,0.3638996138996172,0.2162097162097142,1.761952191235062,0.2583052479537801,1.205361534677818,0.09040767386091145,0.3638996138996179,0.5339147286821707,0.5552593310712601,4.25932737782449,0.04863440344992759,0.3427399903521496,2.05689223057644,0.1322611617858853,0.7914230019493164,0.5552593310712561,0.02777777777777782,0.6408450704225368,1.404150197628458,0.2162097162097162,0.4700048379293649,2.564875823618856,0.2583052479537767,1.559990084283591,0.2162097162097142,1.73942259830762,0.1951923076923098,1.559990084283588,0.09040767386091061,0.4275012083131952,0.2162097162097191,3.132119035402771,0.2162097162097152,0.6837627613028664,0.7267639902676403,1.739422598307608,0.640845070422538,0.3427399903521489,0.2583052479537783,2.98900255754476,0.769849001461275,1.249384539635649,0.3427399903521487,1.24938453963565,0.006941120153183332,0.3004819277108409,0.006941120153183303,2.10260913196187,0.448742746615084,1.426347009391994,1.249384539635649,0.1322611617858862,0.3638996138996143,1.604714640198498,0.6408450704225336,0.9430317848410777,0.4275012083131976,0.5339147286821702,0.4700048379293633,0.8996091841719601,0.6408450704225311,2.240312028183193,0.5125907990314763,0.8996091841719618,0.1322611617858853,0.6408450704225359,1.249384539635646,0.2162097162097158,1.381975308641984,3.060450819672141,0.1951923076923073,0.04863440344992787,0.1951923076923057,0.6408450704225389,1.161425061425068,3.762610504420196,2.870408163265312,2.518227848101256,0.3004819277108444,0.1951923076923063,1.874937593609586,0.04863440344992762,0.4275012083131988,0.3004819277108418,0.04863440344992848,2.425214754926744,0.09040767386091195,0.3427399903521461,0.9430317848410762,0.1322611617858866,0.6837627613028717,1.55999008428359,1.227362204724407,0.5125907990314768,3.036610343061954,0.9865394028389661,0.3427399903521466,2.011266900350532,0.7698490014612734,0.1951923076923087,0.448742746615089,2.194318753142289,0.09040767386091161,0.7698490014612804,0.1951923076923068,1.942999999999999,0.3427399903521433,0.7267639902676407,0.7267639902676403,0.006941120153183399,1.249384539635648,0.09040767386091181,1.559990084283586,0.7267639902676413,0.76984900146128,0.04863440344992797,0.640845070422537,0.5339147286821718,0.04863440344992696,0.6408450704225399,1.073810691515449,0.04863440344992798,0.1322611617858867,1.739422598307613,2.378849066128232,0.5339147286821719,0.1322611617858859,0.4700048379293654,0.899609184171951,0.5125907990314754,0.006941120153183174,0.6837627613028695,0.1322611617858851,1.784504235176868,0.512590799031481,1.965732866433214,0.4275012083131937,3.180020544427326,0.5339147286821719,0.6837627613028694,2.425214754926731,0.1951923076923086,1.38197530864197,1.117574864997548,1.381975308641978,1.051960784313732,0.6408450704225366,0.3427399903521476,1.161425061425065,1.942999999999994,2.752417302798985,0.09040767386091095,1.249384539635651,0.1113243761996156,0.02777777777777833,1.051960784313732,0.2162097162097159,2.21730382293763,1.559990084283593,0.6408450704225354,0.726763990267643,0.7052529182879403,1.515354135710749,1.739422598307613,0.70525291828794,4.536997885835097,5.284755770263012,1.293494332183338,2.194318753142288,0.5125907990314718,0.9865394028389696,0.769849001461277,1.784504235176872,3.615603939865215,0.1951923076923101,2.425214754926727,0.3427399903521492,0.8996091841719586,2.240312028183201,3.180020544427332,3.518106570098289,0.3004819277108429,0.1951923076923047,4.843617021276589,0.3638996138996128,0.8996091841719568,0.1951923076923115,0.9865394028389705,0.1113243761996174,0.8779296875000006,0.1741950985103311,1.784504235176887,1.205361534677813,0.2162097162097172,1.381975308641976,1.874937593609586,2.870408163265301,0.3638996138996117,3.180020544427325,0.174195098510331,1.205361534677815,1.965732866433219,0.986539402838969,0.9865394028389697,1.649528067560863,0.4275012083131932,0.9865394028389691,2.989002557544771,0.09040767386091107,0.5339147286821705,0.4487427466150875,0.4275012083131922,1.965732866433221,0.8562713518789677,1.784504235176885,2.471674253920086,0.5125907990314778,0.3427399903521475,1.739422598307621,0.3004819277108451,0.4700048379293661,0.2162097162097172,0.4700048379293669,3.566804764370798,0.04863440344992757,0.1322611617858857,0.4275012083131965,0.1322611617858839,1.784504235176876,0.111324376199615,0.6837627613028735,1.227362204724413,0.04863440344992791,0.04863440344992817,0.3638996138996138,0.342739990352149,0.9865394028389686,0.3427399903521461,0.5125907990314762,0.3427399903521454,0.1322611617858854,0.5125907990314762,0.1113243761996163,1.761952191235065,0.427501208313192,1.649528067560863,0.006941120153183549,0.3004819277108447,0.0904076738609095,1.227362204724406,1.117574864997542,0.8779296875000019,1.404150197628468,0.9430317848410735,0.4700048379293684,0.6408450704225418,0.6408450704225425,1.117574864997547,1.161425061425068,3.25205761316872,1.381975308641984,3.518106570098283,1.515354135710749,1.161425061425063,0.6408450704225392,0.555259331071254,0.02777777777777754,0.7914230019493177,0.006941120153183065,0.9865394028389685,1.227362204724414,1.649528067560857,0.5552593310712577,1.761952191235059,0.1322611617858859,0.4275012083131927,1.205361534677819,2.102609131961867,0.5339147286821718,0.2583052479537805,0.9430317848410757,0.04863440344992907,0.3004819277108428,2.658456069070585,2.51822784810127,0.5552593310712577,0.3427399903521456,1.404150197628462,0.132261161785886,0.7052529182879336,1.739422598307617,0.3638996138996155,0.4275012083131921,0.53391472868217,0.3427399903521466,2.286397984886653,0.6408450704225394,0.4487427466150908,1.381975308641968,0.3638996138996169,0.7914230019493194,1.404150197628462,0.7052529182879365,0.4700048379293685,1.05196078431373,1.965732866433217,0.4275012083131946,0.8779296875000018,0.7052529182879413,3.61560393986523,0.4700048379293672,1.6047146401985,1.051960784313735,1.739422598307612,0.1951923076923079,0.6837627613028686,0.2583052479537774,2.217303822937627,0.1951923076923053,0.2583052479537785,0.111324376199616,1.40415019762846,1.051960784313727,0.1951923076923063,0.8779296875000002,0.9430317848410796,0.5339147286821714,1.117574864997551,1.761952191235063,0.5125907990314749,0.5339147286821712,0.09040767386091079,1.943000000000003,0.6408450704225384,3.615603939865211,1.649528067560852,1.205361534677821,0.8779296874999983,0.7914230019493194,0.04863440344992843,2.70538891713269,0.2583052479537779,2.70538891713269,1.515354135710755,2.989002557544766,1.852295409181642,1.205361534677815,1.515354135710752,0.02777777777777795,0.9430317848410802,0.04863440344992745,0.9865394028389587,2.102609131961873,0.5552593310712552,0.7698490014612785,0.1113243761996155,1.227362204724413,0.6837627613028692,0.1322611617858858,0.2583052479537812,0.470004837929369,0.8779296875000017,0.7914230019493211,0.640845070422535,0.342739990352147,1.559990084283593,0.1951923076923111,0.8996091841719609,2.286397984886654,1.051960784313726,0.9865394028389618,0.2162097162097148,1.051960784313722,0.04863440344992855,3.036610343061971,2.125502008032125,0.4487427466150876,0.04863440344992962,0.4275012083131963,1.559990084283593,0.7914230019493218,0.1951923076923075,0.4275012083131985,0.2583052479537792,0.8779296875000003,0.4275012083131947,0.5552593310712569,0.1951923076923081,0.09040767386091242,1.784504235176881,2.125502008032127,1.227362204724405,0.7914230019493158,0.111324376199614,0.02777777777777826,2.681910569105703,0.3427399903521469,0.3004819277108423,0.4700048379293684,0.09040767386091288,0.04863440344992814,0.132261161785886,0.4487427466150838,0.04863440344992864,0.5552593310712534,0.555259331071258,0.7914230019493179,0.7267639902676413,2.309475806451598,0.1951923076923059,0.2583052479537771,0.3638996138996129,0.943031784841075,0.9430317848410715,0.1741950985103323,3.738045738045748,0.9430317848410728,0.8779296875000044,0.3427399903521488,0.7698490014612752,0.6408450704225321,2.056892230576441,0.5339147286821684,0.342739990352149,0.1951923076923092,1.205361534677818,0.04863440344992843,0.6408450704225361,0.1322611617858825,1.852295409181632,0.4700048379293664,0.8996091841719573,0.769849001461275,1.227362204724412,2.378849066128223,2.425214754926723,0.7267639902676372,0.877929687500001,0.006941120153184332,0.04863440344992773,0.4700048379293686,1.05196078431373,3.228020565552704,2.125502008032134,1.051960784313726,1.205361534677816,0.19519230769231,0.09040767386091098,1.559990084283598,0.3427399903521479,1.784504235176883,0.04863440344992839,0.00694112015318282,0.5339147286821713,1.55999008428359,0.6408450704225351,0.7914230019493194,0.791423001949317,1.42634700939199,0.216209716209716,0.1951923076923067,0.8779296875000022,2.194318753142278,0.3638996138996143,0.5552593310712545,2.425214754926729,0.04863440344992817,0.5125907990314781,0.7267639902676361,0.6408450704225352,0.8562713518789692,2.194318753142281,0.3638996138996106,0.1951923076923081,3.132119035402778,0.4275012083131943,1.965732866433215,3.518106570098285,0.9865394028389718,0.2162097162097127,0.006941120153183682,0.986539402838965,1.073810691515451,0.7698490014612799,1.40415019762846,1.381975308641978,0.8996091841719671,1.493069306930694,1.559990084283597,0.8996091841719619,1.559990084283594,0.363899613899614,0.1322611617858876,0.1951923076923085,0.7267639902676424,0.1322611617858846,0.3427399903521475,1.249384539635663,2.658456069070601,2.870408163265304,1.604714640198512,1.874937593609589,0.04863440344992746,0.9430317848410817,1.965732866433227,0.726763990267639,1.78450423517688,0.1322611617858853,1.404150197628459,1.559990084283589,0.8996091841719597,0.9865394028389632,0.6408450704225375,0.3004819277108411,0.1951923076923086,1.051960784313727,2.125502008032125,0.1741950985103326,0.1322611617858857,1.942999999999997,0.3638996138996154,0.5339147286821699,0.09040767386091283,0.7267639902676419,0.5125907990314768,1.205361534677816,0.006941120153183203,0.3638996138996137,0.1951923076923078,1.293494332183337,0.7698490014612825,1.649528067560858,4.359926276987884,0.4487427466150871,0.111324376199617,1.205361534677821,1.965732866433218,0.1322611617858857,0.3638996138996172,0.3427399903521471,0.4275012083131943,1.404150197628453,0.3427399903521496,0.7267639902676382,0.04863440344992775,0.2583052479537857,0.8996091841719572,1.24938453963565,1.426347009391991,2.011266900350543,0.25830524795378,0.6837627613028653,2.011266900350535,0.04863440344992761,0.8562713518789659,3.060450819672131,0.5125907990314787,0.4487427466150888,2.989002557544751,1.559990084283592,0.3638996138996161,0.09040767386091327,0.006941120153183467,1.784504235176881,0.09040767386091111,0.6837627613028653,0.470004837929366,0.09040767386091085,0.2583052479537771,0.1951923076923077,0.1322611617858858,0.640845070422536,1.38197530864198,0.8779296875000008,0.6408450704225308,0.1322611617858843,1.426347009391993,1.85229540918164,1.426347009391995,0.342739990352147,1.784504235176884,1.293494332183338,0.04863440344992878,0.1951923076923055,0.5125907990314758,0.9865394028389618,0.174195098510334,0.1322611617858862,0.0486344034499281,1.649528067560857,0.3004819277108434,0.2583052479537772,3.252057613168725,1.249384539635642,0.8779296874999967,3.348453608247427,0.3427399903521478,5.54803022126282,0.9430317848410773,1.51535413571075,2.752417302798984,1.739422598307609,0.3004819277108427,0.6837627613028752,1.293494332183343,1.426347009391995,0.6408450704225337,0.04863440344992938,0.3638996138996152,0.3427399903521487,0.3427399903521435,0.1951923076923087,0.2162097162097176,2.240312028183192,0.2162097162097147,0.09040767386091204,2.681910569105681,1.293494332183341,3.960052219321151,0.006941120153183428,1.942999999999996,3.252057613168723,1.559990084283591,2.309475806451609,1.55999008428359,0.1951923076923098,1.64952806756086,0.2162097162097147,1.493069306930694,0.09040767386091177,0.3427399903521436,0.04863440344992744,0.1322611617858869,1.515354135710745,3.664504411001557,3.73804573804575,1.60471464019851,4.359926276987896,0.7698490014612779,0.3427399903521458,1.051960784313727,2.705388917132683,2.194318753142296,0.6837627613028702,0.1322611617858851,0.1951923076923071,0.4275012083131953,0.2583052479537798,0.216209716209719,1.604714640198516,2.21730382293763,1.40415019762846,0.5339147286821715,0.04863440344992701,2.217303822937629,0.4700048379293669,0.5552593310712535,0.8996091841719526,0.3004819277108449,1.249384539635649,2.564875823618848,0.3427399903521465,1.20536153467782,0.7052529182879403,0.7698490014612754,0.3004819277108456,0.4275012083131942,0.7914230019493186,0.6837627613028698,0.04863440344992841,2.658456069070594,1.227362204724412,0.9430317848410782,0.2583052479537841,1.293494332183341,0.3004819277108445,1.784504235176871,1.739422598307613,3.615603939865216,0.3004819277108425,3.738045738045738,2.989002557544764,0.1322611617858871,0.8996091841719538,0.4700048379293706,0.6408450704225326,0.9865394028389691,2.681910569105696,0.04863440344992791,0.640845070422538,1.381975308641977,0.5552593310712551,0.5339147286821716,0.5125907990314829,0.02777777777777751,1.161425061425057,0.2162097162097149,3.180020544427336,0.6408450704225369,0.4487427466150894,0.899609184171965,0.3427399903521483,1.874937593609587,2.658456069070604,0.4700048379293627,1.852295409181634,0.111324376199618,0.6408450704225338,0.2162097162097163,0.9430317848410757,1.784504235176884,0.1322611617858859,1.051960784313727,2.681910569105688,1.117574864997545,0.2162097162097139,0.6837627613028726,0.02777777777777745,1.381975308641982,1.205361534677815,4.869345396487497,0.943031784841079,0.7267639902676387,0.3004819277108463,1.515354135710747,0.9430317848410741,0.3004819277108466,0.3427399903521481,0.04863440344992763,1.649528067560864,1.559990084283587,0.5125907990314797,1.493069306930693,1.761952191235061,0.5125907990314749,3.421011874032004,4.920884389984001,0.04863440344992709,0.8996091841719586,1.493069306930706,0.2583052479537808,0.8779296874999962,2.194318753142288,0.3427399903521441,0.3638996138996143,0.09040767386091203,0.04863440344992777,1.24938453963565,0.5125907990314749,0.4700048379293695,0.6408450704225404,0.1951923076923085,0.470004837929366,0.1322611617858864,0.006941120153183328,0.1322611617858865,1.943000000000003,0.2162097162097148,0.8996091841719546,0.2162097162097165,1.073810691515453,2.011266900350525,0.8996091841719616,2.518227848101275,1.05196078431373,1.249384539635648,1.874937593609585,0.7914230019493186,0.1322611617858853,1.227362204724409,3.518106570098302,0.7052529182879379,1.515354135710747,1.739422598307621,0.7267639902676465,1.493069306930688,0.342739990352147,0.1951923076923074,1.784504235176872,1.24938453963565,0.726763990267642,0.1113243761996164,0.2162097162097189,0.1951923076923083,1.559990084283597,0.7267639902676353,4.209186351706045,0.7052529182879397,0.04863440344992925,1.16142506142506,0.7698490014612815,1.852295409181638,0.8779296875000034,1.249384539635656,0.1322611617858853,1.117574864997546,0.132261161785886,0.2583052479537806,0.300481927710844,0.7267639902676449,0.2583052479537807,0.7914230019493164,1.515354135710749,0.09040767386090993,0.512590799031472,0.3427399903521459,0.006941120153183815,5.707363291824583,0.6408450704225388,0.258305247953782,0.1741950985103335,0.1322611617858861,0.09040767386091113,0.4275012083131949,1.117574864997549,1.404150197628455,1.559990084283589,1.604714640198518,1.051960784313722,0.0904076738609117,0.5339147286821654,1.515354135710746,0.09040767386091191,0.640845070422534,0.1951923076923077,0.1322611617858847,0.04863440344992808,0.1741950985103324,1.559990084283597,0.04863440344992781,0.258305247953781,1.381975308641977,4.359926276987884,0.3427399903521464,0.6408450704225382,0.5339147286821706,1.404150197628459,0.9865394028389665,2.705388917132693,0.8562713518789656,3.615603939865216,1.249384539635647,0.7267639902676372,0.3427399903521449,2.425214754926725,0.1322611617858841,0.5125907990314744,2.217303822937622,3.566804764370784,0.2583052479537815,1.649528067560857,0.6408450704225408,0.2162097162097168,0.4487427466150902,0.8562713518789653,1.249384539635652,0.5552593310712594,0.09040767386091221,0.3427399903521458,0.09040767386091127,1.073810691515452,1.205361534677818,0.9430317848410789,0.7698490014612798,0.89960918417196,1.381975308641979,0.8779296874999964,0.5125907990314775,0.5125907990314786,0.5125907990314755,0.02777777777777816,0.09040767386091067,0.4487427466150876,1.649528067560855,3.132119035402773,0.1113243761996165,0.72676399026764,1.161425061425067,1.381975308641978,0.006941120153183104,0.00694112015318338,0.1951923076923079,0.6837627613028724,1.051960784313721,5.389725658956435,1.761952191235058,0.09040767386090913,0.258305247953779,2.194318753142279,1.07381069151545,2.240312028183188,0.5339147286821678,0.3427399903521482,0.9430317848410735,0.7914230019493207,1.874937593609589,1.073810691515449,0.4700048379293673,0.5125907990314784,5.232439678284196,2.564875823618847,2.989002557544758,0.877929687499993,2.681910569105705,0.8996091841719591,1.051960784313728,0.3427399903521447,4.35992627698791,0.4275012083131922,0.51259079903148,0.1113243761996181,1.117574864997549,0.02777777777777829,2.378849066128216,4.109219486642223,0.3638996138996122,1.942999999999997,1.60471464019851,0.7914230019493146,0.4700048379293676,0.09040767386091204,0.3638996138996145,0.2583052479537823,0.04863440344992799,0.3427399903521475,0.1113243761996162,0.0486344034499277,1.20536153467782,0.8562713518789702,0.006941120153183647,0.04863440344992772,0.2583052479537765,0.258305247953782,0.02777777777777809,1.117574864997548,2.056892230576438,0.00694112015318332,0.09040767386091,0.1322611617858871,2.102609131961867,0.5339147286821717,0.4275012083131949,1.11757486499755,0.5339147286821693,0.09040767386091071,1.874937593609594,1.559990084283595,0.5339147286821696,0.7914230019493178,1.205361534677818,0.2162097162097172,0.5552593310712582,1.85229540918164,0.4700048379293621,0.3004819277108449,0.8562713518789667,3.180020544427325,1.205361534677825,0.02777777777777735,2.011266900350522,0.5125907990314787,3.228020565552703,1.404150197628462,1.515354135710757,1.404150197628459,0.8562713518789679,0.3638996138996102,0.3427399903521466,0.1322611617858857,1.381975308641975,0.7698490014612793,2.194318753142279,0.9430317848410762,2.309475806451614,0.2583052479537813,0.09040767386090978,1.227362204724409,0.3427399903521453,1.051960784313723,5.389725658956433,0.640845070422539,0.195192307692309,1.117574864997547,0.6408450704225284,2.011266900350526,0.5125907990314783,0.2583052479537799,0.3427399903521455,1.161425061425063,0.4275012083131998,1.874937593609587,0.2583052479537809,0.1113243761996149,0.3427399903521482,4.009670674333512,0.7267639902676377,2.471674253920066,0.6408450704225372,1.60471464019851,1.604714640198514,0.5125907990314762,0.6837627613028676,0.4275012083131919,0.2162097162097154,0.4700048379293649,0.3004819277108407,0.6408450704225368,0.6408450704225366,1.205361534677815,0.006941120153182964,0.09040767386091146,1.942999999999991,2.870408163265321,0.555259331071258,1.073810691515448,0.132261161785888,0.640845070422535,1.943,0.2583052479537797,0.1113243761996154,0.8779296874999881,0.2162097162097173,0.3427399903521484,1.161425061425061,2.518227848101275,0.4700048379293674,3.518106570098297,0.2162097162097167,1.426347009391995,0.5552593310712548,0.09040767386091099,1.073810691515448,0.04863440344992855,0.09040767386091157,1.404150197628458,1.965732866433214,1.051960784313725,3.664504411001556,0.9865394028389575,0.1113243761996182,1.559990084283596,1.874937593609588,0.6837627613028692,0.986539402838965,0.132261161785886,4.511621764395132,0.3004819277108448,0.3427399903521444,0.132261161785883,0.4700048379293684,0.8779296874999962,0.7698490014612815,0.5552593310712571,0.1951923076923083,0.3427399903521479,0.5552593310712572,0.9430317848410726,4.209186351706028,1.559990084283591,1.87493759360959,0.2583052479537795,0.4487427466150897,4.25932737782449,3.566804764370796,1.761952191235062,0.7267639902676398,2.056892230576452,0.3004819277108447,2.658456069070591,0.5552593310712554,0.09040767386091111,0.8562713518789682,0.769849001461279,0.1951923076923099,1.381975308641978,0.3427399903521455,2.658456069070602,0.216209716209715,0.3638996138996125,0.7914230019493182,1.073810691515453,1.874937593609582,2.056892230576446,0.2162097162097212,1.649528067560854,3.228020565552701,1.404150197628476,1.117574864997543,0.53391472868217,1.07381069151545,0.2162097162097188,0.555259331071255,0.04863440344992801,0.98653940283896,1.227362204724411,1.22736220472441,0.4275012083131921,1.117574864997545,0.6837627613028692,0.6408450704225357,2.194318753142277,0.3638996138996111,0.9430317848410789,1.73942259830761,2.125502008032127,0.02777777777777804,0.1322611617858879,4.613287453679191,1.515354135710748,3.518106570098297,0.9430317848410777,0.1951923076923051,0.4700048379293715,3.861125586242836,0.3004819277108445,0.899609184171964,0.9865394028389677,0.6408450704225382,1.404150197628462,1.515354135710747,2.56487582361885,1.117574864997549,0.8996091841719558,0.6837627613028702,1.051960784313718,2.240312028183197,1.761952191235064,0.2162097162097155,0.533914728682169,1.20536153467782,1.649528067560852,0.3427399903521482,0.7698490014612754,0.4700048379293673,1.404150197628465,0.7698490014612768,1.965732866433218,0.7267639902676396,1.249384539635651,0.1951923076923054,1.874937593609592,2.194318753142282,0.8996091841719499,3.51810657009829,3.132119035402769,1.604714640198509,0.5339147286821712,1.161425061425061,0.090407673860911,4.209186351706038,0.8996091841719588,0.3427399903521471,0.2583052479537781,0.3638996138996127,1.381975308641977,0.7698490014612768,0.2162097162097176,0.1322611617858884,0.3004819277108409,0.9865394028389641,1.117574864997547,0.3427399903521461,2.518227848101269,0.6837627613028711,1.965732866433217,1.515354135710749,0.7914230019493247,0.7267639902676454,0.6837627613028699,0.5339147286821755,1.073810691515443,0.5125907990314796,0.640845070422534,0.3004819277108459,0.2162097162097192,4.20918635170603,0.640845070422534,0.1951923076923098,2.518227848101278,0.6837627613028714,2.47167425392008,0.4275012083131947,1.117574864997552,3.762610504420175,1.784504235176892,1.965732866433214,8.227945361411512,3.836458333333325,1.515354135710756,0.258305247953779,0.04863440344992862,3.836458333333328,0.5339147286821728,0.8996091841719649,0.2162097162097181,0.7698490014612769,0.4275012083131904,0.5125907990314816,0.3638996138996127,0.9865394028389667,1.117574864997548,1.293494332183346,0.1322611617858859,1.559990084283589,1.117574864997539,3.86112558624286,1.784504235176882,2.05689223057644,2.378849066128227,0.04863440344992784,1.559990084283591,0.1951923076923058,1.07381069151545,0.3004819277108397,0.006941120153182966,1.05196078431373,2.240312028183199,3.518106570098287,1.559990084283592,1.649528067560853,1.249384539635648,0.9865394028389635,0.1113243761996167,1.205361534677817,1.604714640198519,0.4275012083131967,0.4275012083131956,0.3004819277108423,0.3427399903521472,0.4487427466150868,0.34273999035215,0.02777777777777758,0.4487427466150853,0.5339147286821709,0.5125907990314754,0.1322611617858861,0.02777777777777836,0.09040767386091154,0.6408450704225327,0.1322611617858845,0.6408450704225404,1.87493759360958,1.051960784313722,0.1322611617858852,1.227362204724407,2.19431875314229,1.559990084283589,0.02777777777777733,1.161425061425062,0.7698490014612752,1.293494332183342,1.739422598307622,1.784504235176885,0.1951923076923062,0.04863440344992784,0.258305247953782,0.5125907990314779,0.342739990352144,0.5339147286821722,4.410384818133879,1.073810691515452,2.752417302798986,0.1113243761996152,0.555259331071252,0.6408450704225328,0.1951923076923089,0.5339147286821698,0.9430317848410769,0.09040767386091104,0.3427399903521443,0.6408450704225354,0.006941120153183212,1.073810691515451,0.9430317848410803,0.8996091841719581,0.3427399903521532,0.2583052479537801,1.293494332183337,0.7914230019493218,1.739422598307618,0.6408450704225309,0.8996091841719602,1.205361534677814,0.04863440344992765,0.8996091841719556,0.2162097162097171,1.051960784313729,0.5552593310712518,0.1322611617858854,1.55999008428359,1.381975308641974,1.404150197628459,0.5125907990314769,0.5125907990314863,0.1951923076923058,0.1741950985103317,0.09040767386091131,0.7052529182879362,0.9430317848410764,0.6408450704225368,0.1951923076923096,0.04863440344992846,0.6408450704225319,1.559990084283591,0.8996091841719621,2.658456069070597,0.7052529182879379,2.194318753142283,0.2583052479537795,3.469509043927644,3.518106570098296,0.9430317848410712,2.240312028183195,0.02777777777777803,0.2162097162097155,0.09040767386091175,2.102609131961877,0.5339147286821712,0.09040767386091161,0.1322611617858858,2.102609131961876,1.227362204724409,0.09040767386091116,1.965732866433214,1.227362204724412,1.404150197628452,0.2162097162097175,2.378849066128219,0.3427399903521431,1.784504235176888,2.518227848101275,0.3427399903521491,2.194318753142284,0.09040767386091129,2.681910569105693,0.7698490014612768,0.02777777777777831,0.5552593310712554,0.5552593310712611,1.559990084283591,0.1322611617858863,0.3427399903521504,0.6408450704225367,3.228020565552693,0.5339147286821696,0.09040767386091046,0.640845070422531,1.874937593609584,1.117574864997551,0.3004819277108403,1.426347009391995,1.051960784313728,0.7914230019493182,2.799541518084564,0.9430317848410754,0.6837627613028738,2.286397984886653,1.073810691515448,1.205361534677819,0.4487427466150885,0.3638996138996166,0.1322611617858833,0.4275012083131915,0.3004819277108415,0.9430317848410721,0.6408450704225341,0.4700048379293646,0.8996091841719583,0.3427399903521452,0.6408450704225379,0.09040767386091215,0.1322611617858863,0.8996091841719593,3.566804764370802,0.9865394028389644,1.381975308641971,0.5552593310712557,2.37884906612821,0.2583052479537811,0.2162097162097167,0.4275012083131934,0.1741950985103328,3.132119035402774,1.874937593609588,0.9430317848410755,0.1322611617858846,0.2583052479537801,0.7052529182879373,0.6837627613028696,0.04863440344992886,1.739422598307608,0.9430317848410743,0.3638996138996116,1.426347009391996,0.986539402838965,3.132119035402769,0.1951923076923061,0.006941120153183459,0.7914230019493181,1.515354135710748,1.051960784313728,0.2583052479537803,1.874937593609583,0.6837627613028693,0.4700048379293636,1.559990084283585,0.04863440344992713,0.132261161785886,0.6408450704225374,2.309475806451614,1.117574864997549,2.705388917132696,0.7052529182879407,0.2162097162097152,4.359926276987884,0.9865394028389617,0.195192307692306,0.7052529182879391,1.426347009391994,0.1113243761996177,0.7914230019493161,0.2162097162097157,0.006941120153183094,1.249384539635649,0.1322611617858845,1.559990084283591,0.006941120153183399,0.04863440344992802,0.7698490014612763,0.04863440344992853,0.132261161785885,0.02777777777777793,0.1113243761996156,0.7267639902676373,0.09040767386091098,0.1951923076923044,0.258305247953781,0.02777777777777814,1.784504235176882,2.21730382293762,1.205361534677819,2.42521475492673,0.04863440344992824,3.348453608247415,1.381975308641984,0.1113243761996158,0.4487427466150866,0.4275012083131959,0.8779296875000018,1.404150197628468,0.1322611617858848,1.249384539635651,0.04863440344992796,0.3427399903521491,0.111324376199617,1.051960784313723,0.943031784841076,0.9865394028389626,0.006941120153183807,1.381975308641977,0.1741950985103326,0.8562713518789639,0.2162097162097168,1.227362204724417,0.04863440344992766,0.8779296874999987,0.4700048379293646,0.6837627613028681,0.5125907990314772,0.006941120153183469,0.4275012083131942,1.227362204724421,0.5125907990314801,0.5552593310712574,3.132119035402771,0.6837627613028675,0.3427399903521454,1.161425061425066,1.161425061425064,0.1741950985103318,1.739422598307621,2.056892230576442,0.1951923076923084,0.4700048379293654,2.471674253920078,0.4700048379293729,0.6408450704225368,3.518106570098294,1.05196078431372,3.640041493775927,0.6408450704225311,0.09040767386091032,1.293494332183344,0.006941120153183117,0.3427399903521477,0.5339147286821672,0.3427399903521471,1.161425061425061,0.6837627613028711,0.09040767386091322,0.5552593310712545,0.6837627613028699,0.04863440344992863,0.8779296874999967,0.3638996138996092,0.2162097162097175,0.1322611617858851,0.9865394028389632,0.5125907990314799,3.421011874031999,0.04863440344992853,2.378849066128221,0.1113243761996155,1.227362204724408,0.6408450704225377,1.227362204724408,0.258305247953779,2.194318753142282,1.161425061425057,0.5552593310712552,1.051960784313727,0.1322611617858866,1.381975308641976,1.117574864997548,3.060450819672126,0.1951923076923099,0.2583052479537792,0.2162097162097152,1.761952191235071,0.2162097162097192,6.657836644591621,0.6837627613028699,0.6408450704225359,1.40415019762846,0.8562713518789592,1.649528067560856,0.1951923076923097,0.3638996138996126,1.784504235176879,1.205361534677817,0.9430317848410704,0.1741950985103322,2.240312028183187,0.6837627613028688,0.8996091841719629,3.664504411001553,0.1113243761996152,0.2162097162097165,0.9430317848410753,1.161425061425063,0.470004837929366,0.5125907990314773,0.5339147286821746,1.24938453963565,3.861125586242828,0.6837627613028716,0.3427399903521475,0.2162097162097148,1.493069306930696,2.056892230576442,0.0486344034499285,0.09040767386091071,0.4700048379293697,1.604714640198513,0.5552593310712545,0.6408450704225354,3.180020544427328,1.515354135710743,0.6408450704225356,0.1741950985103318,1.205361534677808,1.404150197628464,0.7698490014612753,0.1951923076923086,0.6408450704225324,2.194318753142277,0.8779296874999963,0.512590799031476,0.3638996138996148,0.3638996138996135,0.1741950985103322,2.102609131961871,0.1322611617858868,3.469509043927658,1.426347009391998,2.011266900350513,0.6837627613028623,0.3427399903521464,2.194318753142291,0.8779296875000007,4.209186351706044,0.5125907990314762,0.7267639902676402,0.300481927710843,0.943031784841079,2.870408163265302,0.04863440344992787,0.7267639902676397,0.5339147286821657,1.293494332183342,0.2583052479537782,0.3427399903521471,1.965732866433223,0.9430317848410754,0.3638996138996145,0.6837627613028656,1.051960784313717,0.8779296875000007,1.426347009391996,0.4487427466150845,1.205361534677812,0.470004837929369,0.726763990267638,3.228020565552709,0.1951923076923068,0.00694112015318374,0.3638996138996139,2.989002557544766,2.681910569105702,0.5339147286821704,0.9865394028389625,0.006941120153183513,0.8996091841719643,1.85229540918165,2.799541518084569,0.6837627613028703,0.7052529182879389,1.649528067560861,0.2162097162097154,0.4275012083131939,0.3427399903521511,0.7914230019493195,3.421011874032021,2.681910569105689,0.258305247953778,2.705388917132702,0.09040767386090812,1.073810691515456,0.8779296874999953,0.027777777777778,0.1113243761996138,0.1113243761996162,1.205361534677812,0.6408450704225398,1.604714640198515,0.1322611617858846,0.640845070422534,0.5125907990314768,0.1741950985103305,0.3427399903521455,0.0486344034499285,0.132261161785887,0.9430317848410775,0.9430317848410712,0.4700048379293705,0.1322611617858846,2.941492079713851,0.1322611617858865,0.02777777777777798,0.7052529182879435,1.649528067560852,1.739422598307619,1.051960784313723,0.09040767386091003,0.9865394028389671,1.426347009391997,1.381975308641965,0.1951923076923087,0.1741950985103324,2.705388917132694,0.5339147286821724,0.3638996138996133,1.64952806756086,2.658456069070601,2.240312028183189,0.7914230019493242,0.1741950985103324,0.1951923076923071,3.469509043927651,1.073810691515454,0.3427399903521488,1.761952191235063,2.309475806451621,0.9430317848410759,1.649528067560851,0.006941120153183362,4.209186351706045,0.4487427466150839,0.2162097162097169,1.559990084283598,2.19431875314228,0.9430317848410732,0.7698490014612814,0.3004819277108478,0.3638996138996121,1.559990084283584,0.09040767386091179,1.493069306930694,0.5339147286821708,1.874937593609579,0.216209716209716,0.986539402838969,0.6837627613028727,0.216209716209717,0.1322611617858845,0.1951923076923072,0.04863440344992786,0.3427399903521465,1.874937593609588,3.348453608247422,0.1741950985103334,1.117574864997548,1.965732866433211,0.7914230019493165,2.681910569105696,0.2583052479537806,1.559990084283591,2.518227848101282,0.3427399903521481,1.205361534677817,1.249384539635652,0.7914230019493191,0.3638996138996128,0.9865394028389727,1.381975308641971,2.240312028183201,1.205361534677818,0.470004837929363,0.5125907990314786,1.761952191235061,2.68191056910569,0.5339147286821683,0.04863440344992803,0.3427399903521476,1.874937593609598,0.3004819277108416,1.784504235176882,0.8779296875000004,0.7914230019493174,0.9430317848410773,0.258305247953782,0.0277777777777777,1.381975308641979,1.76195219123506,0.4700048379293645,0.3638996138996133,2.011266900350522,0.4275012083131975,2.425214754926741,0.5339147286821715,2.518227848101271,3.762610504420185,0.4700048379293698,0.2162097162097162,0.6408450704225367,1.073810691515454,1.426347009392,0.9430317848410741,0.8779296874999997,1.073810691515455,1.381975308641978,0.2162097162097127,1.515354135710749,0.1322611617858865,0.2162097162097164,0.1322611617858857,0.006941120153182975,0.2583052479537775,0.09040767386091207,1.559990084283591,1.205361534677817,1.965732866433229,1.784504235176879,0.0277777777777779,2.518227848101275,0.5339147286821689,0.5339147286821692,0.3427399903521452,0.7698490014612779,0.02777777777777688,4.869345396487497,1.249384539635647,3.180020544427331,0.8996091841719586,2.658456069070592,0.09040767386090934,0.8562713518789681,0.1322611617858896,0.3427399903521449,0.4275012083131979,0.9430317848410807,1.07381069151545,0.6837627613028718,1.404150197628458,0.2583052479537761,0.1322611617858855,1.426347009391991,1.784504235176889,1.404150197628467,0.006941120153183261,1.293494332183348,0.1951923076923081,0.6408450704225265,0.3427399903521473,0.2583052479537779,3.615603939865216,0.4700048379293691,1.161425061425062,0.4275012083131915,1.493069306930697,0.02777777777777718,0.4275012083131939,0.3638996138996107,1.20536153467782,2.42521475492673,0.1322611617858843,0.1741950985103314,1.404150197628451,0.533914728682168,2.752417302798986,0.300481927710843,1.249384539635655,0.4275012083131924,0.5339147286821688,0.4700048379293668,1.965732866433218,0.1741950985103309,0.02777777777777794,0.25830524795378,0.1741950985103294,0.04863440344992818,2.658456069070589,4.259327377824484,0.640845070422534,1.293494332183341,1.205361534677811,1.739422598307613,0.7698490014612784,0.1322611617858861,0.02777777777777835,0.3427399903521434,2.752417302798988,2.125502008032125,0.4700048379293681,0.705252918287942,0.1741950985103328,1.76195219123506,0.5125907990314813,0.09040767386091013,2.378849066128226,0.899609184171958,0.09040767386091167,0.8562713518789674,0.1113243761996166,0.9865394028389626,0.470004837929368,0.04863440344992791,0.5125907990314748,1.073810691515445,0.4487427466150877,0.111324376199617,2.28639798488665,2.309475806451615,0.5125907990314786,1.07381069151545,0.6408450704225329,0.1322611617858843,0.8996091841719599,2.194318753142282,1.493069306930691,3.132119035402775,0.1741950985103312,1.249384539635648,0.6408450704225369,2.752417302798992,0.4275012083131972,2.471674253920088,0.3004819277108416,1.249384539635649,0.5125907990314758,0.2162097162097162,1.649528067560855,1.40415019762846,0.9865394028389642,10.12005899705015,1.293494332183339,0.5552593310712562,1.161425061425061,0.09040767386091252,0.2162097162097165,0.7698490014612767,0.0486344034499281,2.011266900350533,0.09040767386091161,1.29349433218334,0.09040767386090902,0.1113243761996158,1.559990084283595,0.8996091841719606,1.49306930693069,0.3427399903521459,1.117574864997538,3.566804764370797,0.7698490014612746,3.640041493775938,1.42634700939199,0.3638996138996189,0.09040767386091215,0.258305247953779,0.5339147286821705,0.5552593310712546,0.342739990352147,0.769849001461277,0.02777777777777795,4.259327377824479,0.1951923076923079,0.006941120153183037,2.425214754926733,0.195192307692306,1.493069306930686,0.1322611617858861,0.3638996138996128,1.227362204724407,0.1113243761996179,0.3638996138996132,1.852295409181634,3.861125586242843,0.09040767386091125,1.22736220472441,0.5552593310712528,0.8779296874999986,0.9865394028389635,1.227362204724409,0.1951923076923068,0.006941120153183338,0.8996091841719623,0.3004819277108431,0.9865394028389629,0.9430317848410779,1.426347009391993,1.381975308641974,0.3004819277108421,0.943031784841082,1.293494332183339,0.2583052479537832,2.102609131961859,1.051960784313727,0.3427399903521496,0.09040767386091113,0.8779296874999997,0.3004819277108428,0.6408450704225424,0.6408450704225346,1.784504235176878,3.762610504420177,1.205361534677823,1.073810691515448,0.006941120153183418,0.8996091841719622,0.7698490014612782,0.174195098510332,1.117574864997542,1.205361534677817,5.232439678284189,2.705388917132696,1.07381069151545,1.649528067560863,0.1113243761996155,0.3638996138996154,0.9865394028389671,1.559990084283587,0.9430317848410782,1.051960784313724,0.9865394028389599,2.658456069070603,0.9430317848410713,0.04863440344992826,1.874937593609595,0.1951923076923058,1.515354135710746,0.02777777777777741,0.7267639902676356,4.511621764395147,0.555259331071261,0.1951923076923061,0.006941120153183216,0.4275012083131945,0.09040767386091089,1.559990084283594,0.1322611617858866,1.24938453963566,2.194318753142279,0.7267639902676416,1.515354135710751,0.2583052479537782,0.5339147286821699,0.3638996138996135,0.19519230769231,0.3638996138996123,0.2583052479537805,0.8996091841719641,0.5339147286821744,0.9430317848410716,0.1951923076923088,2.658456069070588,0.1113243761996161,0.6837627613028694,0.8996091841719625,0.132261161785888,1.205361534677823,0.9430317848410703,0.1113243761996163,0.6408450704225361,1.117574864997542,1.205361534677813,2.217303822937623,3.615603939865206,0.3004819277108427,0.0904076738609112,0.5125907990314773,0.470004837929366,1.117574864997547,0.4700048379293695,0.4700048379293665,0.6408450704225391,1.784504235176884,0.04863440344992828,0.4487427466150845,0.5552593310712509,1.293494332183343,1.559990084283595,1.761952191235064,2.286397984886642,1.404150197628461,0.048634403449928,0.2162097162097185,0.3638996138996164,1.852295409181642,0.6408450704225328,0.2162097162097168,0.09040767386091132,1.426347009391981,0.3427399903521476,0.3004819277108424,0.4275012083131957,0.856271351878968,0.8779296874999971,4.511621764395151,0.1322611617858859,1.205361534677822,0.877929687500001,0.3004819277108435,1.205361534677818,1.559990084283599,0.5125907990314759,1.761952191235063,0.04863440344992826,1.943000000000009,1.60471464019851,0.4275012083131913,0.1741950985103345,0.02777777777777696,0.6408450704225351,0.877929687500004,0.2162097162097175,0.5125907990314782,1.249384539635654,0.6408450704225394,3.036610343061959,0.6837627613028694,1.073810691515445,1.404150197628457,0.006941120153182841,3.132119035402778,2.94149207971385,1.205361534677817,0.1113243761996166,1.161425061425063,0.2583052479537796,1.739422598307619,0.8779296875000044,0.3638996138996125,0.1741950985103315,0.7914230019493237,1.404150197628451,1.293494332183346,2.194318753142285,0.5552593310712532,1.761952191235042,2.217303822937631,0.09040767386091242,2.471674253920083,0.6837627613028741,0.769849001461276,3.132119035402758,2.564875823618863,0.09040767386091113,0.1322611617858863,2.941492079713854,0.1113243761996165,0.5552593310712551,0.02777777777777722,1.493069306930695,1.404150197628458,0.512590799031482,0.1951923076923087,0.4700048379293656,1.739422598307626,0.5125907990314787,0.1951923076923062,0.3638996138996151,0.7698490014612752,0.1322611617858873,0.7914230019493156,0.1113243761996166,0.1322611617858854,1.739422598307607,0.4700048379293679,0.4275012083131888,0.2162097162097165,1.227362204724409,0.006941120153183268,0.09040767386091179,0.5125907990314811,0.6408450704225346,1.161425061425065,0.2583052479537797,0.5125907990314763,0.2583052479537797,1.117574864997553,0.1113243761996152,1.761952191235057,0.2583052479537787,0.4275012083131924,0.2583052479537757,0.09040767386091088,0.9865394028389619,0.09040767386090871,0.02777777777777764,0.0277777777777782,0.3427399903521486,0.111324376199619,1.515354135710747,0.9430317848410777,1.55999008428359,0.216209716209719,1.293494332183344,0.5552593310712556,1.942999999999999,0.02777777777777766,1.852295409181642,0.04863440344992771,0.7267639902676433,0.72676399026764,0.9430317848410764,0.3004819277108433,0.470004837929368,0.1951923076923082,2.658456069070604,1.426347009391993,1.404150197628453,0.04863440344992731,0.3004819277108465,1.073810691515452,0.04863440344992926,1.559990084283589,2.194318753142284,1.051960784313721,1.559990084283597,0.4700048379293666,1.965732866433216,0.8779296874999988,0.4275012083131945,0.7698490014612747,0.02777777777777831,0.04863440344992711,0.7698490014612733,0.216209716209714,0.5552593310712534,0.132261161785887,0.8996091841719568,0.791423001949323,0.2162097162097164,1.943000000000001,1.051960784313723,1.493069306930688,1.404150197628463,0.3427399903521486,1.78450423517688,0.1951923076923046,1.381975308641974,1.227362204724415,0.3427399903521471,1.293494332183342,0.1322611617858847,0.9430317848410776,0.9430317848410803,1.42634700939199,2.965235173824119,0.8562713518789691,0.1951923076923062,0.1951923076923099,2.194318753142293,0.7698490014612782,0.9430317848410718,0.09040767386091043,1.515354135710751,0.4487427466150868,0.1113243761996154,0.7698490014612844,0.3004819277108433,0.3427399903521468,0.09040767386091214,0.6408450704225357,0.9430317848410739,1.761952191235064,2.056892230576445,0.02777777777777731,0.6837627613028663,0.9430317848410761,1.784504235176887,0.7698490014612772,0.2583052479537805,0.3638996138996149,0.1741950985103323,0.04863440344992916,1.161425061425057,0.2162097162097225,0.4700048379293681,0.3638996138996146,7.217633928571418,1.649528067560853,2.37884906612822,1.649528067560851,0.7698490014612758,0.5339147286821686,0.9430317848410755,0.4275012083131926,0.6837627613028721,0.555259331071255,1.943000000000001,2.378849066128209,0.00694112015318314,0.5552593310712571,1.161425061425067,0.3638996138996142,0.5125907990314751,4.159150498164665,0.006941120153182801,1.205361534677815,1.29349433218334,1.051960784313728,1.493069306930693,1.11757486499755,0.9430317848410756,2.658456069070596,0.2162097162097164,0.7698490014612781,0.1951923076923089,1.249384539635651,0.1951923076923067,2.425214754926738,2.194318753142284,1.293494332183337,0.02777777777777839,0.5125907990314793,0.006941120153183793,1.64952806756085,0.1322611617858861,0.6408450704225316,0.8996091841719647,0.4275012083131975,0.2162097162097174,0.3427399903521456,0.8779296875000031,0.4700048379293675,2.125502008032131,1.404150197628458,0.3427399903521482,0.300481927710849,0.216209716209713,0.1322611617858861,0.640845070422537,0.4700048379293683,0.02777777777777836,0.09040767386091114,0.02777777777777728,1.874937593609594,0.2583052479537796,3.518106570098301,0.2162097162097146,0.3427399903521446,1.051960784313732,1.426347009392001,0.3004819277108405,2.75241730279898,0.4275012083131937,1.161425061425057,0.7267639902676448,1.051960784313728,1.852295409181643,0.9430317848410756,1.381975308641971,0.02777777777777799,0.02777777777777793,0.04863440344992915,0.006941120153183214,2.056892230576445,0.2583052479537807,0.2583052479537838,0.9865394028389602,0.3004819277108448,0.04863440344992655,0.3638996138996137,1.40415019762846,0.7698490014612799,0.3004819277108431,1.22736220472441,0.8562713518789623,0.1951923076923086,0.04863440344992789,0.174195098510332,0.006941120153183196,0.6837627613028707,0.9865394028389599,4.209186351706037,0.6408450704225295,0.9865394028389638,0.5125907990314728,0.04863440344992909,0.09040767386091045,2.94149207971385,2.471674253920094,1.559990084283588,1.051960784313725,1.051960784313726,0.2162097162097157,0.8779296874999906,0.04863440344992805,0.6408450704225345,0.3427399903521463,0.09040767386091182,0.3427399903521443,0.7914230019493205,0.470004837929369,0.1741950985103292,0.1741950985103295,0.7698490014612788,0.04863440344992785,0.1741950985103324,0.4700048379293676,0.3427399903521459,1.051960784313734,0.3638996138996126,2.286397984886649,1.205361534677815,0.04863440344992868,0.1951923076923109,0.048634403449928,0.8779296874999986,3.180020544427323,1.16142506142506,1.07381069151545,0.300481927710844,0.2583052479537774,1.493069306930693,1.293494332183343,0.4700048379293648,0.04863440344992814,2.286397984886646,0.7267639902676456,1.249384539635655,1.117574864997539,0.7052529182879357,0.9430317848410757,0.3004819277108456,3.615603939865221,2.378849066128235,2.989002557544766,1.784504235176873,0.09040767386091239,0.3638996138996126,0.04863440344992843,0.006941120153183164,3.180020544427326,1.051960784313728,4.159150498164665,0.4275012083131995,2.518227848101268,0.6408450704225408,4.715384615384617,1.404150197628452,0.7267639902676406,0.4487427466150852,0.5125907990314746,0.5552593310712602,0.7267639902676354,2.681910569105702,0.5552593310712547,1.227362204724408,1.739422598307616,0.4700048379293699,0.04863440344992743,0.09040767386091145,0.5125907990314807,2.378849066128218,0.2162097162097195,1.73942259830762,2.309475806451621,1.051960784313728,0.5339147286821694,2.194318753142277,2.240312028183189,1.073810691515453,0.6408450704225356,0.04863440344992809,1.117574864997545,0.3427399903521497,3.252057613168734,1.60471464019852,1.965732866433223,1.649528067560856,4.259327377824495,0.9865394028389618,1.205361534677817,0.8562713518789679,0.9430317848410745,1.739422598307616,0.09040767386091189,0.02777777777777856,0.6837627613028696,0.3427399903521482,4.259327377824492,0.7267639902676433,1.559990084283592,0.04863440344992725,0.006941120153183294,2.799541518084563,2.056892230576441,1.49306930693069,0.2583052479537771,1.205361534677821,1.739422598307615,0.1741950985103297,0.111324376199616,0.8779296875000037,3.615603939865217,0.04863440344992961,0.04863440344992857,0.02777777777777861,0.427501208313199,2.056892230576447,1.761952191235061,0.5552593310712588,0.3004819277108432,0.4275012083131962,1.161425061425063,0.1951923076923081,0.8779296875,0.09040767386091121,2.518227848101268,0.5552593310712541,2.681910569105697,0.6408450704225329,1.161425061425066,0.1113243761996192,0.6408450704225356,0.2162097162097191,2.378849066128215,1.161425061425062,0.7052529182879345,0.9430317848410786,0.2162097162097165,0.9865394028389506,1.604714640198513,0.195192307692308,0.1741950985103319,0.3638996138996135,0.1113243761996161,1.07381069151545,0.2162097162097158,0.3004819277108474,0.2162097162097184,0.7698490014612772,0.79142300194931,0.258305247953778,0.9430317848410721,1.249384539635647,0.7698490014612782,0.1322611617858858,6.029155313351505,1.20536153467782,0.4487427466150916,3.18002054442734,0.6837627613028674,1.649528067560865,0.8779296875000026,0.4487427466150881,2.194318753142285,0.1741950985103333,0.9430317848410772,2.056892230576447,0.1322611617858845,0.3638996138996174,2.378849066128212,0.8996091841719592,0.5125907990314754,0.8996091841719557,0.006941120153183511,1.515354135710747,0.9865394028389701,1.404150197628464,2.989002557544766,2.518227848101271,0.132261161785885,1.205361534677818,0.5339147286821736,0.4275012083131993,1.426347009391998,0.3638996138996144,2.102609131961867,2.011266900350527,0.6408450704225338,1.739422598307617,0.4275012083131939,1.051960784313725,2.941492079713854,0.4700048379293668,0.89960918417195,0.9865394028389635,1.161425061425055,1.943000000000001,1.559990084283593,1.205361534677822,0.2583052479537802,0.3427399903521464,0.4275012083131972,0.2583052479537795,2.681910569105706,0.986539402838964,2.217303822937627,0.04863440344992854,1.073810691515451,3.276119402985078,1.404150197628464,1.559990084283589,0.3427399903521473,0.3004819277108405,0.6837627613028694,0.1113243761996156,0.640845070422537,0.7698490014612839,0.7052529182879422,1.161425061425065,0.1741950985103295,0.726763990267649,0.6408450704225389,0.2162097162097155,0.04863440344992845,0.1741950985103329,0.1322611617858843,0.1322611617858861,1.205361534677817,0.5339147286821713,1.761952191235059,1.874937593609586,0.9865394028389664,0.09040767386091285,0.4700048379293644,0.3638996138996118,1.404150197628462,3.06045081967212,0.02777777777777845,0.769849001461272,2.94149207971385,1.515354135710749,1.426347009391997,0.09040767386091202,0.5125907990314759,1.739422598307625,2.217303822937619,3.421011874032005,1.404150197628457,0.7914230019493189,0.3638996138996142,0.5339147286821709,0.5125907990314771,0.6408450704225387,2.681910569105697,1.852295409181648,1.11757486499755,0.1322611617858885,1.293494332183345,3.518106570098292,0.9430317848410735,0.5125907990314805,0.6837627613028687,0.02777777777777768,1.784504235176884,0.683762761302865,1.739422598307622,1.117574864997548,0.1322611617858867,0.1113243761996178,0.258305247953783,0.7698490014612751,5.760704607046077,2.564875823618859,2.752417302798984,0.3638996138996185,1.51535413571075,0.3427399903521478,0.9430317848410835,0.1951923076923085,0.3427399903521485,0.1113243761996169,0.4700048379293694,2.681910569105699,1.073810691515448,0.6837627613028762,0.6408450704225347,0.7914230019493182,0.2162097162097178,0.1741950985103312,0.3638996138996124,2.471674253920079,1.205361534677815,0.1113243761996168,0.09040767386091174,1.874937593609588,0.04863440344992787,0.5125907990314776,2.705388917132703,1.249384539635655,1.426347009391997,2.518227848101272,0.3004819277108433,0.09040767386091167,0.3638996138996155,1.87493759360959,0.8996091841719589,0.5552593310712545,1.117574864997537,0.9430317848410759,0.5125907990314762,0.2162097162097158,0.1322611617858863,0.3638996138996133,0.7914230019493196,0.8779296875000028,0.25830524795378,0.09040767386091153,0.5339147286821725,3.664504411001564,2.240312028183193,0.04863440344992801,2.564875823618861,1.784504235176887,0.195192307692307,3.180020544427335,0.5125907990314752,1.117574864997543,1.874937593609587,0.363899613899612,0.3427399903521464,0.2583052479537762,1.404150197628461,1.559990084283579,1.205361534677813,0.1322611617858855,1.227362204724403,0.3427399903521463,0.132261161785885,0.7698490014612807,2.425214754926733,0.3427399903521478,0.1322611617858875,5.975231355470862,0.1951923076923074,1.051960784313733,1.16142506142506,2.125502008032137,1.161425061425064,2.125502008032124,0.9430317848410781,0.1322611617858855,0.8996091841719608,0.8562713518789656,0.6408450704225329,2.68191056910569,0.1322611617858894,0.1741950985103324,0.2162097162097189,0.6408450704225362,0.6408450704225367,3.252057613168734,2.286397984886649,2.286397984886651,0.791423001949324,0.1322611617858857,0.1113243761996166,0.5552593310712585,0.02777777777777795,0.04863440344992826,0.1113243761996168,0.8562713518789659,0.6837627613028706,1.852295409181637,0.3427399903521465,0.3427399903521451,0.5339147286821679,0.3638996138996115,1.381975308641975,2.989002557544753,0.02777777777777795,1.051960784313729,0.2162097162097171,0.04863440344992766,0.2162097162097198,0.8779296874999992,1.381975308641976,0.3638996138996125,0.7267639902676405,2.471674253920074,0.5339147286821686,0.6837627613028694,0.8996091841719573,1.784504235176886,0.986539402838963,0.6408450704225315,0.006941120153183839,1.07381069151545,0.6837627613028697,0.1322611617858844,0.9430317848410732,1.227362204724407,0.3004819277108451,0.1951923076923096,0.3427399903521492,2.194318753142286,0.1951923076923109,0.6837627613028623,3.61560393986523,0.2583052479537798,0.2583052479537793,0.5339147286821704,3.180020544427324,0.02777777777777696,2.194318753142291,0.7698490014612762,0.5125907990314802,0.300481927710847,1.073810691515449,0.3004819277108447,0.09040767386091182,0.7267639902676408,0.6408450704225359,2.011266900350533,0.1322611617858852,1.227362204724413,4.410384818133912,0.04863440344992801,1.761952191235061,0.8779296875000049,2.286397984886643,2.011266900350529,1.426347009391997,0.3638996138996175,1.965732866433215,0.1741950985103316,1.426347009391988,1.249384539635649,0.7267639902676396,0.04863440344992836,0.6408450704225401,3.615603939865223,0.6408450704225384,0.1741950985103317,0.1322611617858857,1.249384539635646,0.1113243761996171,0.9430317848410767,1.249384539635643,1.965732866433217,1.161425061425063,0.9430317848410713,1.739422598307607,2.378849066128218,1.227362204724412,0.3427399903521468,0.3638996138996115,7.359541130386107,0.1951923076923081,5.050213675213676,0.1322611617858867,0.6837627613028705,0.9430317848410751,0.04863440344992739,2.286397984886655,2.471674253920082,0.6837627613028696,0.1113243761996157,2.37884906612822,0.006941120153183614,0.04863440344992768,0.9430317848410733,0.9430317848410721,0.02777777777777818,0.3427399903521455,0.1951923076923088,0.5339147286821724,1.05196078431373,0.3427399903521463,0.7267639902676389,0.2162097162097144,0.3427399903521458,0.7052529182879408,0.4275012083131986,0.00694112015318377,1.404150197628456,0.640845070422538,3.518106570098307,1.249384539635643,0.3427399903521469,0.09040767386091189,1.965732866433217,2.309475806451614,2.240312028183201,1.60471464019852,0.3004819277108442,0.76984900146127,0.4700048379293673,0.0486344034499283,2.425214754926733,2.658456069070623,1.117574864997547,0.3638996138996151,0.4700048379293678,0.9865394028389645,1.874937593609596,1.161425061425066,0.4487427466150876,1.761952191235059,0.1322611617858877,0.3638996138996137,0.4487427466150855,0.8996091841719595,0.5339147286821708,0.6837627613028626,0.2583052479537796,1.227362204724414,0.006941120153183338,1.559990084283592,1.559990084283596,0.2162097162097196,1.404150197628461,1.205361534677819,1.426347009391997,1.381975308641975,1.161425061425055,2.056892230576447,0.0277777777777767,0.3638996138996137,0.9430317848410679,0.4487427466150873,2.989002557544759,0.4700048379293631,0.04863440344992821,3.518106570098297,0.2583052479537791,0.9430317848410755,3.469509043927654,0.09040767386091025,2.518227848101274,0.6837627613028681,0.1113243761996154,1.073810691515446,0.8996091841719621,0.342739990352147,0.3004819277108439,0.6408450704225371,0.1322611617858846,0.3427399903521492,0.3427399903521474,1.073810691515449,1.249384539635651,0.7267639902676448,0.1113243761996155,0.3427399903521466,0.4700048379293686,1.051960784313724,0.09040767386091142,1.515354135710749,0.640845070422537,0.8996091841719589,1.784504235176887,0.4487427466150838,0.7698490014612763,1.205361534677821,1.051960784313726,4.511621764395152,0.1951923076923086,4.359926276987896,2.941492079713853,0.02777777777777803,0.1322611617858844,2.217303822937625,0.09040767386090999,0.6408450704225348,0.8779296874999973,0.3004819277108442,0.5552593310712554,0.3004819277108437,0.7914230019493187,1.49306930693069,0.1951923076923097,2.989002557544776,0.6408450704225377,1.943000000000002,0.5339147286821719,1.205361534677825,2.425214754926732,0.3004819277108468,0.7267639902676408,1.761952191235062,0.4700048379293693,2.194318753142285,0.4700048379293663,0.4275012083131918,1.205361534677816,0.09040767386091111,0.04863440344992829,1.784504235176889,0.9430317848410757,0.4700048379293673,0.6837627613028735,2.194318753142289,1.161425061425059,0.2162097162097175,0.5125907990314797,0.8562713518789672,2.989002557544756,0.258305247953781,0.2583052479537765,1.293494332183348,0.1322611617858843,1.205361534677818,0.04863440344992949,2.564875823618853,4.972533333333345,1.784504235176873,2.681910569105684,2.564875823618851,1.40415019762846,2.56487582361885,0.0277777777777773,1.249384539635652,0.2162097162097176,0.09040767386091268,2.471674253920081,0.1322611617858858,1.161425061425059,0.8996091841719611,0.3004819277108438,0.7914230019493167,0.7267639902676402,1.205361534677814,0.2162097162097167,1.649528067560855,0.4275012083131947,0.8562713518789699,2.309475806451609,2.309475806451623,0.7052529182879365,0.00694112015318344,0.7698490014612778,0.9430317848410796,3.036610343061962,1.117574864997549,1.649528067560855,0.04863440344992923,1.161425061425059,0.1951923076923081,0.2583052479537804,2.752417302798983,0.09040767386091361,0.3638996138996126,2.194318753142292,0.9865394028389656,1.515354135710743,1.404150197628459,1.515354135710755,1.205361534677815,0.89960918417196,0.726763990267639,10.12005899705018,0.9865394028389686,1.559990084283587,0.3427399903521441,0.342739990352145,2.125502008032132,1.649528067560859,2.518227848101255,0.04863440344992916,0.2583052479537797,0.5339147286821706,0.3638996138996149,0.555259331071258,0.6408450704225374,2.989002557544766,1.381975308641977,0.04863440344992807,0.8779296875000047,0.8996091841719579,0.5339147286821732,1.117574864997548,0.4487427466150868,0.111324376199617,1.604714640198518,0.1741950985103337,0.1951923076923096,0.1322611617858873,2.681910569105685,0.3427399903521474,2.681910569105689,2.102609131961862,0.9430317848410764,0.470004837929368,1.205361534677821,0.7267639902676398,2.681910569105681,0.3638996138996135,2.37884906612822,0.7914230019493139,1.649528067560863,1.293494332183343,0.1322611617858854,0.6837627613028691,0.7052529182879361,0.8779296875000007,0.533914728682175,0.006941120153183173,1.739422598307621,0.09040767386091146,1.117574864997539,0.4275012083131999,0.09040767386091242,0.8779296875000014,0.1951923076923082,0.4700048379293674,4.511621764395142,1.404150197628458,1.761952191235067,2.799541518084568,0.1113243761996156,0.640845070422539,0.7698490014612777,0.6837627613028673,2.681910569105682,1.559990084283587,1.784504235176882,1.76195219123507,0.5552593310712566,0.6837627613028707,0.94303178484108,1.11757486499755,0.8779296874999972,0.7914230019493169,0.5339147286821732,0.006941120153183247,2.011266900350529,1.249384539635644,0.0486344034499291,2.518227848101264,0.8562713518789673,0.7052529182879352,0.7267639902676376,0.5125907990314774,0.4487427466150893,1.051960784313726,0.7052529182879361,0.7267639902676366,1.96573286643321,0.09040767386091288,0.7267639902676393,0.4700048379293694,0.4487427466150915,0.3638996138996137,0.1741950985103341,0.2583052479537818,0.2162097162097145,1.381975308641976,0.5125907990314807,0.3427399903521487,0.7267639902676379,0.6837627613028653,1.227362204724414,0.3638996138996115,0.5339147286821685,2.518227848101264,1.249384539635643,0.04863440344992862,1.073810691515454,1.117574864997548,0.2583052479537803,0.7267639902676416,0.3004819277108425,3.036610343061975,0.02777777777777797,4.972533333333338,0.3638996138996136,0.342739990352147,0.2162097162097172,1.227362204724409,4.259327377824496,0.7698490014612809,1.117574864997548,0.4275012083131962,0.9430317848410762,1.559990084283591,1.205361534677816,0.09040767386091175,0.4700048379293659,0.4487427466150885,2.125502008032119,0.4487427466150886,0.2583052479537779,2.194318753142284,0.3427399903521471,0.3004819277108436,1.493069306930686,0.9430317848410797,0.7267639902676462,1.07381069151544,0.2583052479537796,2.870408163265304,0.1951923076923084,2.102609131961868,0.2162097162097152,1.649528067560852,0.1113243761996169,1.227362204724397,0.9430317848410819,0.4700048379293673,0.5339147286821713,0.5339147286821738,1.739422598307614,0.512590799031479,0.04863440344992838,2.98900255754476,0.9430317848410841,0.9430317848410825,2.658456069070593,0.2583052479537778,0.1113243761996151,0.09040767386091131,3.861125586242833,1.404150197628464,0.6408450704225311,0.006941120153183909,2.965235173824135,2.752417302798985,0.1322611617858855,0.4700048379293634,0.6408450704225346,0.006941120153183334,0.1322611617858861,0.8779296875000048,0.0486344034499275,0.5125907990314793,0.5125907990314807,0.3427399903521443,0.363899613899616,1.051960784313726,0.1951923076923057,1.493069306930694,0.1951923076923088,2.378849066128221,2.941492079713845,0.174195098510332,2.681910569105688,0.1322611617858849,1.874937593609594,0.1951923076923094,1.515354135710754,0.0904076738609103,2.011266900350533,0.2162097162097155,1.852295409181638,0.7698490014612808,1.874937593609592,1.293494332183342,0.2583052479537758,1.051960784313727,0.3638996138996161,3.036610343061967,2.194318753142286,1.293494332183348,4.84361702127661,1.784504235176885,0.4700048379293675,0.2583052479537801,0.4487427466150882,1.381975308641972,0.4700048379293633,0.1322611617858858,1.117574864997549,0.4275012083131947,0.2583052479537807,0.4275012083131918,1.515354135710743,0.7914230019493191,0.7052529182879461,2.752417302798987,0.09040767386091314,4.234243697479,0.4487427466150889,0.258305247953781,1.87493759360959,0.6408450704225357,0.4487427466150856,0.3427399903521448,0.09040767386091,0.8779296875000012,0.1322611617858852,0.2583052479537796,2.194318753142281,2.194318753142281,3.960052219321156,0.9430317848410773,2.240312028183199,0.1113243761996141,1.965732866433218,1.559990084283595,2.056892230576438,0.3427399903521444,0.3638996138996162,0.3427399903521458,1.227362204724415,0.3638996138996142,1.117574864997547,1.649528067560851,0.7914230019493186,0.09040767386091311,1.205361534677818,1.293494332183336,0.3004819277108448,1.205361534677817,0.6837627613028704,0.342739990352149,2.194318753142272,1.51535413571076,0.4275012083131977,4.20918635170603,1.249384539635656,0.04863440344992866,1.784504235176876,0.1113243761996159,1.604714640198513,1.739422598307621,0.04863440344992926,0.4275012083131941,1.784504235176885,0.3004819277108439,0.3427399903521469,0.2583052479537797,0.132261161785886,0.4275012083131948,0.1113243761996159,0.09040767386091149,0.342739990352148,0.3427399903521496,1.161425061425059,0.3004819277108438,0.34273999035215,1.051960784313728,0.899609184171957,0.9865394028389646,0.986539402838964,0.8779296875000017,3.060450819672146,4.5369978858351,0.7267639902676394,0.9430317848410743,0.3638996138996161,1.073810691515449,0.6408450704225367,0.4700048379293651,2.286397984886652,1.604714640198512,0.7267639902676362,1.161425061425054,0.3638996138996128,0.04863440344992857,0.04863440344992945,1.965732866433218,0.2162097162097146,0.9430317848410783,0.0486344034499284,1.161425061425063,1.874937593609586,0.5125907990314783,0.470004837929368,0.1113243761996152,1.559990084283599,0.640845070422536,0.5552593310712559,1.205361534677819,0.3427399903521471,2.056892230576448,0.1741950985103321,0.8779296875,1.761952191235071,0.8996091841719587,0.6837627613028668,1.404150197628461,0.04863440344992819,0.1322611617858847,1.07381069151545,0.04863440344992714,1.874937593609587,0.7698490014612733,1.784504235176881,0.02777777777777703,0.02777777777777819,2.518227848101276,1.426347009391993,0.0486344034499282,3.276119402985075,0.5125907990314801,0.3638996138996143,2.989002557544772,0.04863440344992651,0.3004819277108414,1.051960784313727,0.7698490014612737,0.3004819277108448,0.7914230019493111,2.309475806451616,0.6837627613028695,0.6408450704225386,1.965732866433212,1.205361534677817,0.5125907990314811,0.09040767386090916,0.7052529182879443,0.342739990352146,2.870408163265312,0.9430317848410704,2.309475806451621,2.752417302798995,0.1322611617858853,0.6837627613028713,0.3638996138996144,1.965732866433217,0.6837627613028708,0.7267639902676395,0.363899613899614,0.1951923076923074,0.5339147286821753,0.3427399903521485,3.762610504420188,1.249384539635651,0.1951923076923098,0.640845070422537,0.4275012083131951,1.205361534677818,1.649528067560865,0.2583052479537779,0.1322611617858866,2.518227848101271,0.1113243761996166,0.1951923076923066,0.1322611617858858,0.1113243761996158,0.09040767386091196,0.6408450704225335,0.9865394028389681,1.559990084283585,1.493069306930696,0.342739990352147,0.1951923076923085,0.7267639902676413,0.9430317848410841,2.194318753142281,0.2162097162097164,4.0096706743335,1.76195219123506,0.9430317848410807,0.6408450704225398,0.006941120153183387,0.006941120153183702,0.111324376199616,4.8436170212766,0.02777777777777822,0.5552593310712481,0.9865394028389595,0.5125907990314812,0.1322611617858872,1.073810691515448,0.427501208313194,1.22736220472441,1.249384539635647,0.2162097162097182,1.60471464019851,0.4487427466150885,1.874937593609591,3.738045738045729,0.7267639902676387,0.1741950985103325,0.4700048379293671,0.04863440344992853,0.7052529182879372,0.1113243761996148,0.1741950985103332,0.5125907990314811,1.761952191235056,0.6837627613028694,0.132261161785886,1.943000000000001,0.1951923076923098,1.404150197628462,1.493069306930696,0.04863440344992755,1.559990084283593,0.5125907990314776,0.5339147286821703,0.448742746615087,1.943000000000003,0.4275012083131936,0.006941120153183615,0.3638996138996143,1.404150197628464,0.4275012083131944,0.174195098510332,1.604714640198514,1.761952191235057,0.943031784841074,0.8562713518789618,1.117574864997552,0.3004819277108449,1.051960784313727,0.09040767386090891,1.249384539635653,0.1322611617858852,1.161425061425057,1.559990084283593,0.5125907990314816,0.04863440344992577,0.006941120153183112,1.381975308641976,0.09040767386090889,2.194318753142285,0.5125907990314784,0.006941120153183225,0.4275012083131947,0.1741950985103333,0.7914230019493167,1.604714640198514,2.194318753142294,1.493069306930694,0.7914230019493145,0.3638996138996179,0.5552593310712554,0.7914230019493159,0.7267639902676373,0.3004819277108453,0.3638996138996139,2.87040816326531,1.55999008428359,0.5125907990314774,1.073810691515449,0.04863440344992695,1.515354135710746,1.426347009391995,0.09040767386091028,0.3427399903521484,1.404150197628457,0.6837627613028715,0.3427399903521456,4.664281928987829,0.09040767386091253,1.965732866433219,0.5552593310712558,0.3427399903521495,2.752417302798982,2.681910569105697,0.5125907990314753,0.5125907990314766,3.421011874032009,0.3427399903521464,1.249384539635646,0.3638996138996134,0.5552593310712547,0.8779296875000029,1.117574864997546,0.6408450704225346,0.25830524795378,2.518227848101269,0.1322611617858858,0.5125907990314743,0.2583052479537798,1.227362204724409,2.658456069070592,0.8996091841719603,2.681910569105697,0.3004819277108406,0.3427399903521444,1.227362204724407,0.4275012083131952,1.205361534677816,0.09040767386091267,2.217303822937627,0.4275012083131949,0.640845070422539,1.404150197628459,0.3004819277108419,0.1741950985103325,0.3427399903521471,1.051960784313725,0.1741950985103321,1.161425061425064,0.9865394028389702,0.7052529182879427,0.5125907990314795,0.5125907990314755,0.3004819277108444,0.5125907990314775,0.4700048379293636,0.006941120153183765,1.161425061425058,2.681910569105693,3.615603939865228,0.2162097162097162,1.559990084283587,0.09040767386091084,0.2162097162097174,0.1951923076923086,0.195192307692307,0.1322611617858848,0.9865394028389548,2.752417302798985,0.7267639902676405,0.4700048379293664,0.512590799031479,1.051960784313725,0.555259331071253,0.9430317848410795,0.3004819277108435,1.965732866433215,1.515354135710755,0.4487427466150827,0.2583052479537786,0.04863440344992827,1.249384539635645,0.3004819277108404,0.3004819277108448,2.378849066128227,0.2162097162097155,0.9865394028389626,0.2162097162097189,0.09040767386091288,1.249384539635644,2.011266900350528,0.2162097162097189,0.6408450704225314,0.7267639902676395,0.9430317848410742,0.111324376199616,0.533914728682172,4.259327377824496,0.300481927710844,0.4275012083132006,1.51535413571075,0.342739990352148,0.769849001461277,0.216209716209716,0.6408450704225378,1.381975308641967,0.2583052479537805,0.5552593310712552,1.161425061425057,3.132119035402785,0.5552593310712577,0.1951923076923084,0.5339147286821728,1.649528067560851,2.752417302798987,1.404150197628452,2.564875823618857,3.566804764370794,2.705388917132697,0.5125907990314789,0.1741950985103316,0.02777777777777873,0.9430317848410763,0.9430317848410773,0.3638996138996158,0.6837627613028705,1.559990084283595,0.02777777777777686,0.3638996138996132,0.3427399903521503,1.073810691515447,1.874937593609578,0.09040767386091099,0.5125907990314779,1.073810691515451,0.3638996138996147,2.518227848101272,1.117574864997547,0.04863440344992739,0.6837627613028707,2.19431875314229,0.512590799031476,0.2583052479537799,0.04863440344992727,0.9430317848410781,0.3427399903521474,2.56487582361886,0.2162097162097178,0.02777777777777813,0.3004819277108447,1.051960784313726,0.1741950985103315,0.6408450704225375,0.2583052479537814,0.5125907990314775,1.161425061425056,2.309475806451615,0.1322611617858869,0.006941120153183451,0.006941120153183161,1.073810691515447,2.05689223057643,0.9430317848410763,0.7698490014612794,1.739422598307625,0.7698490014612835,0.258305247953781,0.195192307692308,2.194318753142294,1.381975308641979,1.293494332183337,0.4275012083131961,1.205361534677816,0.3004819277108474,2.309475806451615,0.7267639902676359,0.6837627613028722,0.1951923076923082,0.5552593310712567,0.1951923076923056,2.870408163265307,0.3427399903521468,0.09040767386091078,0.3638996138996159,0.8562713518789653,0.4275012083131945,0.2162097162097133,1.874937593609585,0.2162097162097172,0.899609184171951,0.9430317848410739,0.6837627613028674,0.0277777777777779,0.6837627613028698,1.493069306930684,1.649528067560855,2.989002557544762,0.04863440344992877,0.1322611617858853,0.1322611617858858,1.293494332183339,0.7052529182879429,0.04863440344992826,0.1951923076923094,0.0486344034499268,0.4700048379293673,0.9865394028389625,0.8996091841719654,0.3004819277108456,0.9430317848410789,1.649528067560857,1.874937593609591,0.1322611617858842,1.161425061425067,0.9430317848410771,1.051960784313728,2.056892230576442,0.04863440344992971,1.117574864997543,0.9865394028389634,3.25205761316873,0.1113243761996158,0.6837627613028697,2.378849066128231,2.286397984886656,3.252057613168721,0.04863440344992716,0.6408450704225291,1.227362204724408,0.09040767386091189,0.1951923076923058,0.4275012083131954,2.102609131961859,2.564875823618857,1.227362204724419,0.2583052479537793,1.515354135710754,0.3427399903521503,0.2162097162097179,0.8779296875000002,2.564875823618859,1.117574864997544,3.252057613168733,0.5339147286821662,0.4275012083131977,0.132261161785886,0.3004819277108419,0.98653940283896,0.3427399903521455,0.5552593310712572,0.5339147286821694,0.9430317848410787,2.425214754926728,0.7914230019493225,0.048634403449929,0.6408450704225329,0.132261161785885,1.117574864997551,0.986539402838968,1.07381069151545,0.4275012083131962,0.132261161785886,0.3427399903521487,0.6408450704225374,0.1322611617858854,0.7914230019493168,0.4275012083131974,0.4275012083131958,2.681910569105687,1.07381069151545,0.7914230019493184,0.342739990352148,4.511621764395129,1.051960784313725,0.5552593310712552,0.5552593310712575,0.6837627613028719,0.6837627613028608,1.649528067560857,0.258305247953779,2.217303822937626,0.1322611617858855,0.6408450704225361,0.1113243761996164,0.2162097162097149,1.117574864997546,0.448742746615091,1.40415019762846,1.161425061425064,0.1951923076923076,3.664504411001563,0.5125907990314755,0.3427399903521484,0.0904076738609116,0.7914230019493245,1.559990084283592,1.293494332183343,0.5339147286821756,1.205361534677824,0.6408450704225366,1.205361534677815,0.2162097162097194,3.276119402985078,2.471674253920087,1.761952191235057,0.006941120153183474,0.640845070422529,2.425214754926731,0.1741950985103325,2.24031202818319,1.381975308641972,1.117574864997542,1.426347009391999,0.363899613899613,0.3004819277108424,0.2162097162097175,0.363899613899614,0.1951923076923084,0.5552593310712569,1.852295409181636,1.381975308641973,1.965732866433215,0.09040767386091167,2.870408163265307,0.6837627613028729,0.5552593310712542,0.258305247953781,1.051960784313721,1.493069306930695,0.3427399903521501,0.7914230019493232,0.5552593310712576,0.1322611617858849,0.470004837929367,0.6408450704225372,6.908208541320028,2.6819105691057,1.11757486499755,0.533914728682171,0.3427399903521468,0.1951923076923076,0.1322611617858849,0.04863440344992882,0.2583052479537787,0.4275012083131958,0.3427399903521471,0.02777777777777762,3.34845360824743,1.073810691515457,0.877929687500004,2.240312028183198,0.3638996138996177,1.293494332183338,2.125502008032125,2.011266900350529,3.518106570098313,0.3638996138996126,0.5552593310712546,0.5552593310712556,2.011266900350535,0.7698490014612782,0.8779296875000012,2.011266900350519,1.073810691515446,0.769849001461275,0.6408450704225375,0.2162097162097172,1.761952191235055,0.1741950985103324,1.784504235176883,0.04863440344992718,0.4700048379293709,0.7698490014612772,1.205361534677804,0.7914230019493173,1.559990084283594,2.681910569105696,1.205361534677816,1.64952806756086,0.1951923076923097,2.309475806451621,0.1741950985103338,2.309475806451601,4.715384615384616,1.604714640198514,0.4275012083131916,0.2583052479537775,0.6408450704225356,1.227362204724414,0.1113243761996159,0.2583052479537798,0.2162097162097166,0.2583052479537776,0.3638996138996189,0.791423001949317,1.073810691515448,0.856271351878974,0.512590799031475,2.240312028183192,0.342739990352148,0.8996091841719615,1.739422598307619,0.4275012083131945,1.784504235176888,0.7698490014612813,0.640845070422537,0.7052529182879401,0.4275012083131952,0.6408450704225348,1.784504235176891,0.2162097162097153,0.512590799031483,0.5125907990314765,3.518106570098304,2.011266900350518,0.7267639902676408,0.02777777777777678,0.6408450704225361,0.1741950985103304,0.5552593310712546,0.0277777777777784,0.4487427466150869,0.9865394028389667,0.5552593310712605,0.6408450704225298,1.739422598307622,1.22736220472441,0.6408450704225368,0.1741950985103329,4.209186351706028,1.426347009391992,0.4700048379293711,1.161425061425061,0.2583052479537798,0.3004819277108459,0.6408450704225392,0.04863440344992755,1.205361534677819,1.426347009391988,0.216209716209716,0.4700048379293683,0.5125907990314779,1.426347009391991,1.604714640198506,2.378849066128224,1.381975308641974,0.4487427466150894,2.056892230576439,0.5125907990314736,0.856271351878965,0.04863440344992876,1.249384539635648,0.09040767386091079,0.1113243761996163,1.942999999999999,2.125502008032138,0.02777777777777795,1.381975308641985,0.6408450704225367,0.3004819277108458,0.8996091841719596,0.00694112015318313,0.5339147286821713,0.5339147286821743,0.8562713518789663,0.2162097162097158,0.363899613899614,1.943000000000007,2.518227848101269,2.518227848101265,0.9430317848410752,0.2162097162097155,0.9430317848410735,1.649528067560854,0.6408450704225359,0.04863440344992769,1.161425061425063,2.240312028183199,1.60471464019851,0.4275012083131938,0.9430317848410786,0.3004819277108398,0.6408450704225371,0.8779296874999992,0.3427399903521491,0.4487427466150897,0.8779296874999974,2.989002557544762,1.942999999999997,0.2583052479537807,0.4700048379293671,1.051960784313726,0.1951923076923076,0.1741950985103323,0.0486344034499285,2.965235173824137,0.7267639902676395,3.06045081967214,0.5552593310712555,0.9430317848410766,0.4487427466150893,0.9430317848410742,0.3638996138996187,0.8562713518789694,0.3427399903521487,0.7267639902676436,0.2583052479537775,0.9865394028389578,2.194318753142294,0.7914230019493195,1.249384539635643,0.258305247953779,0.006941120153183198,0.04863440344992724,0.3638996138996158,0.1951923076923112,0.6408450704225372,0.1951923076923077,1.943000000000001,0.195192307692307,0.09040767386091179,0.1322611617858887,0.1951923076923077,0.3427399903521456,1.784504235176867,0.02777777777777802,2.989002557544749,0.2583052479537816,1.784504235176883,0.4700048379293684,0.3427399903521475,0.9430317848410766,0.7052529182879422,2.681910569105687,0.09040767386091189,1.784504235176886,1.161425061425058,2.056892230576446,0.04863440344992825,1.784504235176887,0.1322611617858863,1.051960784313726,0.1322611617858856,0.1322611617858873,0.6408450704225361,1.604714640198516,1.11757486499755,0.4700048379293658,0.5125907990314783,0.3427399903521466,0.8562713518789575,0.3638996138996176,0.3638996138996162,1.205361534677819,0.9865394028389649,0.2162097162097146,0.8996091841719547,0.04863440344992811,0.1951923076923086,0.1322611617858855,1.559990084283589,0.4275012083131958,1.761952191235062,0.7267639902676414,1.11757486499754,0.2162097162097162,0.2162097162097147,0.2583052479537785,0.1741950985103313,0.9430317848410756,1.051960784313726,1.739422598307614,0.6408450704225366,1.11757486499754,1.404150197628458,2.799541518084566,1.249384539635652,0.5339147286821709,0.09040767386091136,0.1322611617858866,0.5125907990314816,0.555259331071256,1.761952191235063,0.7698490014612751,0.09040767386091085,0.4275012083131973,0.1741950985103313,0.216209716209718,0.5125907990314765,0.7914230019493177,0.04863440344992937,1.784504235176882,0.7698490014612813,0.7698490014612809,0.8779296875000007,1.874937593609581,3.252057613168723,1.649528067560848,2.102609131961867,1.249384539635644,1.739422598307621,2.102609131961867,2.705388917132693,4.259327377824483,1.604714640198512,2.240312028183189,0.4487427466150894,0.470004837929367,1.943000000000005,0.7698490014612818,0.3638996138996104,1.381975308641973,2.194318753142278,0.3638996138996139,0.09040767386091204,1.852295409181637,0.7914230019493166,0.04863440344992798,1.227362204724409,0.1741950985103331,0.1322611617858844,3.180020544427333,1.604714640198512,0.726763990267639,0.09040767386091086,0.174195098510329,0.5339147286821706,1.784504235176884,0.25830524795378,1.604714640198519,1.761952191235068,2.217303822937633,0.5125907990314744,0.5339147286821699,0.1951923076923057,0.1113243761996158,0.5339147286821724,0.7698490014612748,0.3638996138996133,0.7698490014612827,0.8996091841719601,1.739422598307608,0.09040767386091024,0.5552593310712577,1.381975308641975,1.07381069151545,0.04863440344992824,0.1322611617858849,0.2162097162097189,2.705388917132679,1.761952191235062,1.559990084283593,0.5339147286821717,0.1113243761996176,1.051960784313727,0.3638996138996142,1.559990084283586,0.3427399903521452,1.649528067560855,1.227362204724412,0.006941120153183396,0.8779296875000043,3.276119402985068,2.471674253920091,0.1322611617858865,0.9865394028389607,0.1113243761996156,0.9430317848410774,1.205361534677819,1.965732866433211,0.2162097162097158,2.102609131961868,0.5125907990314713,0.9430317848410835,0.8996091841719517,0.9430317848410764,0.3427399903521481,0.7267639902676443,0.342739990352146,1.22736220472441,0.8996091841719589,0.2162097162097168,1.604714640198514,0.09040767386091156,1.404150197628452,1.073810691515447,0.533914728682172,0.1741950985103278,1.051960784313725,1.404150197628459,0.1322611617858859,1.117574864997547,1.249384539635653,0.8562713518789681,0.470004837929367,1.493069306930693,0.1322611617858853,0.342739990352148,1.965732866433216,1.85229540918165,0.8779296874999999,0.8779296875000042,2.564875823618865,0.8779296874999976,0.216209716209717,0.6837627613028689,1.426347009391995,1.227362204724411,0.7914230019493206,0.7052529182879386,0.4487427466150876,1.227362204724409,1.381975308641966,0.2162097162097155,2.752417302798991,1.20536153467782,0.02777777777777774,0.3427399903521485,0.6408450704225352,0.5552593310712548,1.493069306930688,0.006941120153183733,1.784504235176885,0.5552593310712524,2.217303822937629,0.5125907990314764,1.649528067560857,0.2162097162097154,0.5552593310712569,0.7914230019493195,0.2583052479537805,0.5339147286821647,1.515354135710759,0.04863440344992871,1.559990084283589,0.04863440344992866,0.8562713518789661,0.7914230019493147,1.293494332183333,0.5552593310712578,0.4275012083131944,1.515354135710752,1.205361534677821,0.8779296874999973,1.874937593609585,2.799541518084572,0.899609184171965,1.55999008428359,1.404150197628453,1.94300000000001,0.3004819277108444,0.3004819277108448,0.2583052479537818,1.117574864997553,1.649528067560853,0.6837627613028687,0.9430317848410775,5.548030221262815,0.09040767386091217,1.227362204724417,0.4700048379293655,3.348453608247416,0.8996091841719572,0.1741950985103314,0.5125907990314784,0.132261161785886,0.09040767386091228,1.761952191235059,1.404150197628463,0.8779296875000008,0.8562713518789657,0.1741950985103319,1.117574864997543,1.784504235176871,1.205361534677815,0.0486344034499281,2.194318753142278,0.006941120153183234,0.7698490014612788,0.6837627613028658,3.61560393986522,0.7698490014612654,1.874937593609591,0.3638996138996153,0.3427399903521481,1.649528067560859,1.874937593609583,0.3004819277108467,1.739422598307617,1.05196078431372,1.117574864997549,1.426347009391993,0.09040767386091272,0.3638996138996173,2.799541518084567,1.559990084283588,0.1322611617858848,1.227362204724413,5.284755770263041,0.3427399903521431,0.1951923076923078,0.8996091841719613,0.7914230019493218,4.10921948664221,2.425214754926727,0.6837627613028664,0.1741950985103306,1.40415019762846,0.6837627613028713,0.3427399903521485,0.3638996138996166,1.965732866433216,0.09040767386091296,0.4275012083131939,4.410384818133902,0.2583052479537778,0.8996091841719581,0.3638996138996122,1.11757486499755,0.9430317848410753,0.6408450704225384,1.559990084283602,0.1322611617858867,0.427501208313192,0.02777777777777744,1.051960784313724,2.125502008032138,0.9430317848410773,3.615603939865236,0.8562713518789594,0.4275012083131963,0.7052529182879396,1.051960784313729,1.739422598307621,0.6408450704225368,1.78450423517689,0.5125907990314771,0.1113243761996165,1.426347009391997,0.5339147286821707,2.125502008032135,0.9865394028389702,0.1951923076923079,0.9430317848410789,1.227362204724406,0.2162097162097168,1.404150197628461,4.159150498164666,0.3427399903521469,1.293494332183345,3.615603939865215,2.658456069070612,0.3638996138996136,1.784504235176887,0.4275012083132018,1.404150197628466,1.426347009391995,1.073810691515446,0.2583052479537791,0.5125907990314775,2.989002557544762,0.986539402838969,0.9865394028389667,0.1322611617858856,0.3427399903521452,0.1322611617858855,0.8996091841719586,0.6837627613028704,0.7267639902676385,0.09040767386091107,0.1322611617858864,1.073810691515447,0.9430317848410783,2.79954151808457,0.258305247953778,0.02777777777777775,1.515354135710748,0.7052529182879383,0.3004819277108445,1.249384539635646,6.246031746031764,0.5125907990314779,0.006941120153183546,1.249384539635644,1.161425061425062,0.7267639902676396,0.3427399903521427,0.4700048379293678,0.3638996138996142,1.943000000000003,0.300481927710843,0.5552593310712567,0.7698490014612762,0.9430317848410802,1.784504235176881,0.1322611617858879,2.056892230576443,0.9430317848410736,0.2162097162097172,0.1951923076923072,0.6408450704225379,0.04863440344992738,0.877929687500006,0.1322611617858859,1.493069306930691,0.2583052479537796,0.1322611617858848,0.006941120153183287,2.989002557544748,0.1951923076923057,0.8996091841719552,0.7914230019493181,0.04863440344992893,0.6408450704225395,0.9430317848410769,0.1113243761996156,0.04863440344992911,0.8779296874999997,0.1741950985103315,1.559990084283591,0.1113243761996153,0.1951923076923079,0.3638996138996096,0.3004819277108415,0.5125907990314773,0.4487427466150889,0.4487427466150886,0.5125907990314783,0.877929687500008,1.404150197628457,0.2583052479537807,1.604714640198508,0.006941120153183235,0.6408450704225359,0.5552593310712557,0.09040767386090932,0.09040767386091002,0.1322611617858865,0.09040767386091104,1.559990084283591,1.227362204724409,1.965732866433218,1.739422598307613,0.04863440344992771,1.073810691515456,0.8996091841719649,0.9430317848410777,1.94300000000001,1.381975308641983,0.2583052479537796,0.9430317848410823,1.205361534677816,0.1951923076923092,1.649528067560856,3.960052219321141,0.3427399903521435,0.7267639902676332,0.4275012083131936,0.8996091841719639,0.5339147286821706,1.874937593609582,0.5125907990314764,1.381975308641981,0.6837627613028709,1.161425061425053,1.24938453963565,2.989002557544762,0.5125907990314758,1.426347009391995,1.24938453963565,0.04863440344992711,0.2583052479537775,0.3004819277108427,0.1951923076923095,0.3004819277108383,1.515354135710746,0.470004837929367,0.640845070422534,0.1951923076923075,0.943031784841076,0.3638996138996118,0.5552593310712539,0.2162097162097159,0.195192307692309,0.9430317848410771,0.6837627613028682,0.6408450704225349,0.04863440344992811,1.227362204724416,0.5552593310712508,0.640845070422534,2.989002557544757,1.965732866433218,0.640845070422538,0.1951923076923076,0.04863440344992743,0.6408450704225357,2.286397984886658,1.073810691515448,1.205361534677816,0.1951923076923081,0.5339147286821722,0.3427399903521466,0.02777777777777837,0.6408450704225414,1.051960784313731,4.869345396487496,0.5125907990314817,1.381975308641974,1.40415019762846,2.870408163265304,0.5552593310712542,0.04863440344992864,0.8996091841719625,1.205361534677821,2.309475806451619,0.09040767386091317,0.6408450704225308,2.309475806451615,0.1741950985103324,0.5125907990314735,0.6408450704225352,1.073810691515461,0.363899613899614,2.217303822937629,0.04863440344992794,0.5339147286821708,1.205361534677821,0.4275012083131955,0.04863440344992938,4.209186351706025,1.161425061425055,3.836458333333336,0.5339147286821715,0.9430317848410766,1.073810691515441,2.011266900350533,0.04863440344992868,0.132261161785886,0.1951923076923087,0.4487427466150852,0.1951923076923103,0.5125907990314796,0.3427399903521447,0.5339147286821709,0.6408450704225346,0.02777777777777765,0.1322611617858857,0.5125907990314815,0.8996091841719628,0.5339147286821709,0.09040767386091021,0.8779296875000012,3.036610343061958,0.1951923076923081,0.640845070422533,1.784504235176884]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>replicate<\\/th>\\n      <th>stat<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":10,\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"replicate\",\"targets\":1},{\"name\":\"stat\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n\n.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n##\nnull_dist_infer %>%\n  visualise(method = \"simulation\") +\n  shade_p_value(obs_stat = observed_infer$stat, direction = \"right\") +\n  scale_x_continuous(trans = \"log10\", expand = c(0, 0)) +\n  coord_cartesian(xlim = c(0.2, 500), clip = \"off\") +\n  annotation_logticks(outside = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in transformation$transform(x): NaNs produced\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in scale_x_continuous(trans = \"log10\", expand = c(0, 0)): log-10\ntransformation introduced infinite values.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n\n.\n\n-   The infer based permutation test shows that the observed F-statistic falls within the permutationally generated F-statistics, and the small red region indicates that the probability of obtaining a test statistic as extreme as, or more extreme than, the observed statistic under the null hypothesis is present and **not negligible.**\n\n.\n\n.\n\n## Conclusion\n\n.\n\nThe null hypothesis is rejected, but not completely - that is, the difference in the means of the Scores across the three Bachelors Degrees is sometimes statistically significant .\n\n> Does this mean all cases in the hypothesis ring true until a bigger sample is obtained?\n\n.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.8.1/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.33/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.1/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.1/js/crosstalk.min.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}